rpm-software-management/dnf5

test/libdnf/system/test_state.cpp

Ignore stray newlines from the `toml` file as `toml::format` output has changed for `toml` library versions between fedora-35 and fedora-36.

test: Compare trimmed toml output

---

libdnf/system/state.cpp
libdnf/system/state.hpp

Also adds a new APIs:
- get_package_groups(na)
- get_packages_by_reason(reason)

System state: correctly calculate the GROUP reason

---

libdnf/transaction/db/archs.cpp
libdnf/transaction/db/archs.hpp
libdnf/transaction/db/rpm.cpp
libdnf/transaction/db/sql/create_tables.sql

Please review and merge firstly PR https://github.com/rpm-software-management/dnf5/pull/34
Then I will rebase this PR.

 HistoryDB: Create table with archs, use them as foreign keys in rpm table

---

libdnf-cli/output/transactioninfo.cpp
libdnf/base/transaction.cpp
test/libdnf/base/test_goal.cpp

Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1161

Print reason in transaction info, use reason from system state for Replaced packages

---

test/libdnf/base/test_base.cpp
test/libdnf/base/test_base.hpp
test/libdnf/base_test_case.cpp
test/libdnf/base_test_case.hpp
test/libdnf/conf/test_conf.cpp
test/libdnf/conf/test_conf.hpp
test/libdnf/conf/test_vars.cpp
test/libdnf/conf/test_vars.hpp
test/libdnf/repo/test_repo_query.cpp
test/libdnf/repo/test_repo_query.hpp
test/libdnf/rpm/test_reldep.cpp
test/libdnf/rpm/test_reldep.hpp
test/libdnf/test_case_fixture.cpp
test/libdnf/test_case_fixture.hpp
test/perl5/libdnf5/rpm/test_package_query.t
test/python3/libdnf5/base_test_case.py
test/ruby/libdnf5/base_test_case.rb

Otherwise, it works with host root files, which influence the tests.

Make sure to set installroot when Base is used in tests

---

dnf5/commands/advisory/advisory_list.cpp
include/libdnf/advisory/advisory_package.hpp
include/libdnf/rpm/package_set.hpp
libdnf/advisory/advisory_package.cpp
libdnf/advisory/advisory_package_private.hpp
libdnf/base/goal.cpp

Related bz to noarch <-> arch upgrades:
https://bugzilla.redhat.com/show_bug.cgi?id=2124483
Marking as `blocked` until it is resolved in dnf4.

Advisory: obsoletes and noarch <-> arch upgrades

---

libdnf/base/goal.cpp

In case the spec fails to resolve to a package,
add_reason_change_to_goal() method returns problem. As a result also `dnf5 mark` command returns exit code 1 in case the specified package does not exist.

goal: Reason change correctly returns resolve problems

---

dnf5.spec
dnf5daemon-server/CMakeLists.txt
dnf5daemon-server/dbus/dnf5daemon-server.service
dnf5daemon-server/dbus/org.rpm.dnf.v0.service

Also mark dnf5daemon-server config file as config
Fixes for: https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2120661#c13

Move dnf5daemon-server executable to /usr/sbin

---

dnf5/commands/download/download.cpp
dnf5/commands/download/download.hpp

tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1167

Add resolve, alldeps to download

---

dnf5.spec

= changelog =
msg:           Add libdnf5/plugins directory to dnf5 package
type:          bugfix
resolves:      https://bugzilla.redhat.com/show_bug.cgi?id=2135338

Add libdnf5/plugins dir to dnf5 package

---

bindings/go/CMakeLists.txt
bindings/libdnf5/common.i
bindings/python3/CMakeLists.txt
bindings/ruby/CMakeLists.txt

There are several issues with Fedora rawhide builds that we've started to see recently. This should hopefully fix them.

Fix Fedora rawhide builds

---

dnf5-plugins/changelog_plugin/changelog.cpp
dnf5/commands/history/transaction_id.cpp
dnf5daemon-server/callbacks.cpp
libdnf-cli/output/transactioninfo.cpp
libdnf-cli/output/transactionlist.cpp
libdnf/system/state.cpp
test/libdnf-cli/utils/test_utf8.cpp
test/libdnf/advisory/test_advisory.cpp
test/libdnf/advisory/test_advisory_query.cpp
test/libdnf/base/test_goal.cpp
test/libdnf/comps/test_environment.cpp
test/libdnf/comps/test_group.cpp
test/libdnf/module/test_module.cpp
test/libdnf/repo/test_package_downloader.cpp
test/libdnf/rpm/test_nevra.cpp
test/libdnf/rpm/test_package_query.cpp
test/libdnf/system/test_state.cpp
test/libdnf/transaction/MergedTransactionTest.cpp
test/libdnf/transaction/test_comps_environment.cpp
test/libdnf/transaction/test_comps_group.cpp
test/libdnf/transaction/test_query.cpp
test/libdnf/transaction/test_rpm_package.cpp
test/libdnf/transaction/test_transaction.cpp
test/libdnf/utils/test_fs.cpp

Fix issues discovered in koji rawhide builds https://koji.fedoraproject.org/koji/taskinfo?taskID=93628360.

Fix rawhide builds

---

dnf5-plugins/builddep_plugin/builddep.cpp
include/libdnf/rpm/reldep.hpp
libdnf/base/goal.cpp
libdnf/rpm/reldep.cpp

It also requires test in our CI for following arguments
install '(available_package if not_installed)' => expected nothing to do
install '(available_package if package_installed)' => expected install available_package
install '(available_package if not_installed)' not_installed => expected install available_package and `not_installed`

Improve handling of rich dependencies

---

libdnf/base/goal.cpp

We do not want to add all installed packages to upgrade job. Only installed packages with matching names are relevant.
https://bugzilla.redhat.com/show_bug.cgi?id=2142257
Test: https://github.com/rpm-software-management/ci-dnf-stack/pull/1180

goal: Filter all_installed for requested names

---

bindings/libdnf5/base.i
bindings/libdnf5/rpm.i

Fixes related to discovered issues when trying to replicate the cpp tutorials with Python bindings.
This addresses the SWIG issues in:
- https://github.com/rpm-software-management/dnf5/pull/102
- https://github.com/rpm-software-management/dnf5/issues/66

swig: Fix issues with transactions in Python bindings

---

dnf5.spec

from: https://src.fedoraproject.org/rpms/dnf5/pull-request/1

 Remove perl(MODULE_COMPAT), it will be replaced by generators

---

libdnf/module/module_metadata.cpp
libdnf/module/module_sack_impl.hpp
test/libdnf/module/test_module.cpp

Discovered by running with sanitizers.

Fix a couple of memory leaks

---

include/libdnf-cli/output/transaction_table.hpp

There are expected CI test failures fixed by https://github.com/rpm-software-management/ci-dnf-stack/pull/1237

output: Print resolve logs to stderr

---

test/python3/libdnf5/base/test_goal.py
test/python3/libdnf5/repo/test_repo.py

pre-commit starts failing on this.

pep8 fix in the tests

---

dnf5/commands/download/download.cpp

Resolves https://github.com/rpm-software-management/dnf5/issues/472 and [bz2187981](https://bugzilla.redhat.com/show_bug.cgi?id=2187981).
The download command should make selections following repo priority and favoring the latest available versions.

download command: filter by priority, latest

---

dnf5/context.cpp
dnf5/include/dnf5/context.hpp
include/libdnf/base/transaction.hpp
include/libdnf/rpm/rpm_signature.hpp
libdnf/base/transaction.cpp
libdnf/base/transaction_impl.hpp
libdnf/rpm/rpm_signature.cpp
test/libdnf/base/test_transaction.cpp
test/libdnf/base/test_transaction.hpp
test/python3/libdnf5/base/test_transaction.py

Includes handling of recovery process when new keys are automatically tried to be imported. Also some refactoring was done with intention for a better code readability + switching to translatable strings.
Closes #386.

API for GPG signature checking of transaction packages

---

libdnf/base/transaction.cpp

Fixes inconsistency in the system state after group removal.

transaction: Delete removed groups from system state

---

dnf5/commands/group/group.cpp
dnf5/commands/group/group_upgrade.cpp
dnf5/commands/group/group_upgrade.hpp
include/libdnf-cli/output/transaction_table.hpp
include/libdnf/base/goal.hpp
libdnf/base/goal.cpp
libdnf/comps/group/group.cpp

Implements ability to upgrade a group.
For https://github.com/rpm-software-management/dnf5/issues/138

dnf5: group upgrade command

---

.pre-commit-config.yaml
dnf5-plugins/builddep_plugin/builddep.cpp
libdnf/repo/repo_downloader.cpp
libdnf/utils/on_scope_exit.hpp
test/shared/private_accessor.hpp

Couple minor clang-format fixes
For: https://github.com/rpm-software-management/dnf5/issues/482

Update clang-format to 16.0.1 to match f38

---

dnf5/commands/clean/clean.cpp

https://bugzilla.redhat.com/show_bug.cgi?id=2192854

Fix handling of incorrect argument (RhBug:2192854)

---

dnf5/commands/repoquery/repoquery.cpp
dnf5/commands/repoquery/repoquery.hpp
doc/commands/repoquery.8.rst

Resolves: https://github.com/rpm-software-management/dnf5/issues/454

Implement repoquery --unneeded option

---

dnf5-plugins/builddep_plugin/builddep.cpp
dnf5/commands/downgrade/downgrade.cpp
dnf5/commands/group/group_install.cpp
dnf5/commands/group/group_upgrade.cpp
dnf5/commands/install/install.cpp
dnf5/commands/reinstall/reinstall.cpp
dnf5/commands/upgrade/upgrade.cpp
dnf5/include/dnf5/shared_options.hpp
dnf5/shared_options.cpp
include/libdnf/conf/config_main.hpp
libdnf/base/goal.cpp
libdnf/conf/config_main.cpp

Resolves: https://github.com/rpm-software-management/dnf5/issues/388
Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1274

Implement Allow downgrade

---

dnf5-plugins/CMakeLists.txt
dnf5-plugins/repoclosure_plugin/CMakeLists.txt
dnf5-plugins/repoclosure_plugin/repoclosure.cpp
dnf5-plugins/repoclosure_plugin/repoclosure.hpp
dnf5-plugins/repoclosure_plugin/repoclosure_cmd_plugin.cpp
dnf5.spec
doc/CMakeLists.txt
doc/changes.rst
doc/conf.py.in
doc/dnf5.8.rst
doc/dnf5_plugins/index.rst
doc/dnf5_plugins/repoclosure.8.rst
doc/index.rst
include/libdnf/rpm/package_query.hpp
libdnf/rpm/package_query.cpp

Resolves: https://github.com/rpm-software-management/dnf5/issues/397
It's an equivalent of the dnf4 implementation.

Repoclosure plugin

---

libdnf/base/goal.cpp

https://bugzilla.redhat.com/show_bug.cgi?id=2196818

Respect skip_unavailable for reinstall command (RHBug:2196818)

---

dnf5/main.cpp

It prevents core dump of dnf5 when --setopt or --setvars is used with incorrect values.
Resolves: https://github.com/rpm-software-management/dnf5/issues/534

Replace runtime_error by libdnf5 error

---

dnf5/commands/remove/remove.cpp
dnf5/commands/remove/remove.hpp
libdnf/base/goal.cpp

To allow `dnf5 remove @group_id` which is also supported by dnf4.

Remove command accepts "remove specs"

---

libdnf/base/goal.cpp

Later the method will be enhanced to resolve also environmental groups specs.

goal: Split group specs resolution to separate method

---

dnf5daemon-client/wrappers/dbus_environment_wrapper.cpp
dnf5daemon-client/wrappers/dbus_environment_wrapper.hpp
dnf5daemon-client/wrappers/dbus_goal_wrapper.cpp
dnf5daemon-client/wrappers/dbus_goal_wrapper.hpp
dnf5daemon-client/wrappers/dbus_transaction_environment_wrapper.hpp
dnf5daemon-server/environment.cpp
dnf5daemon-server/environment.hpp
dnf5daemon-server/services/goal/goal.cpp
include/libdnf-cli/output/transaction_table.hpp
include/libdnf/base/transaction.hpp
include/libdnf/base/transaction_environment.hpp
include/libdnf/transaction/comps_environment.hpp
include/libdnf/transaction/transaction.hpp
libdnf/base/transaction.cpp
libdnf/base/transaction_impl.hpp
libdnf/rpm/solv/goal_private.hpp
libdnf/transaction/transaction.cpp

This adds support for correctly saving environmental groups from the transaction into the history database and the system state.
Also support for environments in the transaction is added to the daemon.

transaction: Support for environmental groups

---

dnf5/commands/download/download.cpp

Fix use case when the same package is available in multiple repositories.
We resolve the dependencies separately for each matching package and construct a set of packages instead of a vector to avoid having duplicates in the result.
This is a follow-up to the https://github.com/rpm-software-management/dnf5/pull/488.
Parent issue: https://github.com/rpm-software-management/dnf5/issues/494.
CI tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1262.

download: Resolve goal separately for each package

---

libdnf/rpm/transaction.cpp

When an error occurred during the scriptlet, but RPM evalutes it as non-critical, zero exit code is returned. In this case, we don't want to pass this confusing information to the user as we don't have any additional information about what happened there.
Closes #462.

transaction: Don't use callback for non-critical script errors

---

dnf5/commands/module/module_enable.cpp
dnf5/commands/module/module_enable.hpp
dnf5/context.cpp
dnf5daemon-client/wrappers/dbus_goal_wrapper.cpp
dnf5daemon-client/wrappers/dbus_goal_wrapper.hpp
dnf5daemon-client/wrappers/dbus_transaction_module_wrapper.hpp
dnf5daemon-server/transaction.cpp
include/libdnf-cli/output/transaction_table.hpp
include/libdnf/base/transaction.hpp
include/libdnf/base/transaction_module.hpp
include/libdnf/module/module_sack.hpp
include/libdnf/transaction/transaction.hpp
include/libdnf/transaction/transaction_item_action.hpp
libdnf/base/base.cpp
libdnf/base/goal.cpp
libdnf/base/transaction.cpp
libdnf/base/transaction_impl.hpp
libdnf/module/module_db.cpp
libdnf/module/module_db.hpp
libdnf/module/module_goal_private.cpp
libdnf/module/module_goal_private.hpp
libdnf/module/module_sack.cpp
libdnf/module/module_sack_impl.hpp
libdnf/rpm/transaction.cpp
libdnf/transaction/transaction_item_action.cpp

Related issue: https://github.com/rpm-software-management/dnf5/issues/126

modules: Implement module enable

---

libdnf/rpm/rpm_signature.cpp

libdnf: fix typo in comment

---

dnf5/commands/reinstall/reinstall.cpp
dnf5/commands/reinstall/reinstall.hpp

It was clearly forgotten to implement for reinstall command.

dnf5: --allowerasing for reinstall command

---

doc/commands/group.8.rst
include/libdnf5/advisory/advisory_collection.hpp
include/libdnf5/advisory/advisory_module.hpp
include/libdnf5/advisory/advisory_package.hpp
libdnf5-cli/output/advisoryinfo.cpp
libdnf5/advisory/advisory_package_private.hpp
libdnf5/base/goal.cpp
libdnf5/comps/group/group.cpp
libdnf5/module/module_sack.cpp
libdnf5/rpm/package_query.cpp

There are only two occurences actually visible to the user, but still...

Typo: pacakge -> package

---

dnf5/commands/history/history.cpp
dnf5/commands/module/module.cpp

Closes: https://github.com/rpm-software-management/dnf5/issues/642

Drop unsupported

---

libdnf5/advisory/advisory_package_private.hpp
libdnf5/advisory/advisory_query.cpp
libdnf5/rpm/package_query.cpp

Some more findings while reading source code

libdnf: fix typos in comments

---

bindings/libdnf5/common.i
dnf5/cmdline_aliases.cpp
dnf5/commands/repoquery/repoquery.cpp
dnf5/commands/upgrade/upgrade.cpp
dnf5/context.cpp
libdnf5-cli/argument_parser.cpp
test/libdnf5/logger/test_loggers.cpp
test/python3/libdnf5/logger/test_loggers.py
test/ruby/libdnf5/logger/test_loggers.rb

Some more findings while reading source code

Fix typos in comments

---

dnf5/include/dnf5/context.hpp
dnf5/main.cpp
doc/dnf5.8.rst
include/libdnf5/repo/repo_sack.hpp
libdnf5/repo/repo_sack.cpp

The option behave the same way as in dnf4.
Resolves: https://github.com/rpm-software-management/dnf5/issues/549
Resolves: https://github.com/rpm-software-management/dnf5/issues/168

Implementation of --repofrompath option for dnf5

---

doc/changes.rst

Closes: https://github.com/rpm-software-management/dnf5/issues/139
Closes: https://github.com/rpm-software-management/dnf5/issues/638

Document dropping of commands and aliases

---

dnf5/commands/repoquery/repoquery.cpp
dnf5daemon-client/commands/repoquery/repoquery.cpp
dnf5daemon-client/wrappers/dbus_package_wrapper.hpp
dnf5daemon-server/package.cpp
dnf5daemon-server/package.hpp
include/libdnf5-cli/output/package_info_sections.hpp
include/libdnf5-cli/output/pkg_colorizer.hpp
include/libdnf5-cli/output/repoquery.hpp
libdnf5-cli/output/package_info_sections.cpp
libdnf5-cli/output/pkg_colorizer.cpp

Closes: https://github.com/rpm-software-management/dnf5/issues/690
Closes: https://github.com/rpm-software-management/dnf5/issues/479
Test update: https://github.com/rpm-software-management/ci-dnf-stack/pull/1334

Unify package info printing and add Vendor

---

dnf5/commands/clean/clean.cpp
dnf5/main.cpp

The current implementation blindly believes that each entry under the
cache dir is a directory representing a repository cache. Unfortunately
that's not always true, libdnf5 stores also files here (e.g.
fastestmirror.cache or temporary_files.toml).
In such case it leads to a coredump on attempt to create a
subdirectory `attrs` of this file.
Fixes: https://github.com/rpm-software-management/dnf5/issues/711

dnf5: Fix core dump on --refresh switch usage

---

dnf5-plugins/copr_plugin/copr_config.cpp

copr: detect "rawhide" releasever

---

dnf5.spec

The spec for DNF 5 doesn't build properly on ELN/RHEL10. These conditionals get it building correctly, but there are test failures and I haven't figured out what's causing them yet.

spec: Fix conditional for dnf-data

---

doc/changes.rst

Remove couple of outdated dnf4/5 change descriptions

Remove couple of outdated dnf4/5 change descriptions

---

libdnf5/base/goal.cpp

Resolves https://github.com/rpm-software-management/dnf5/issues/766
The issue was assuming that the `std::vector` `tmp_solvables` has at least one element. Sometimes it is empty, such as when installing with both (1) a glob pattern and (2) an advisory filter that filters out all packages matched by the glob, e.g. this command:
```dnf5 install --advisories=nonexistent \*```

Fix out-of-bounds access in Goal::Impl::add_install_to_goal

---

libdnf5/conf/vars.cpp

Rpm's rpmExpand() API returns malloc'ed memory that needs to be freed.
See also: https://github.com/rpm-software-management/dnf5/pull/805

vars: Fix memory leak in detect_arch

---

dnf5/config/usr/share/dnf5/aliases.d/compatibility.conf

Add `dsync` alias for `distro-sync`

---

dnf5/commands/module/module.cpp
dnf5/commands/module/module_disable.cpp
dnf5/commands/module/module_disable.hpp
dnf5/commands/module/module_enable.cpp
dnf5/commands/module/module_reset.cpp
dnf5/commands/module/module_reset.hpp
include/libdnf5/base/goal.hpp
include/libdnf5/base/goal_elements.hpp
libdnf5/base/goal.cpp
libdnf5/base/goal_elements.cpp
libdnf5/base/transaction.cpp
libdnf5/module/module_sack.cpp
libdnf5/module/module_sack_impl.hpp
test/libdnf5/module/test_module.cpp
test/libdnf5/module/test_module.hpp

Resolves: https://github.com/rpm-software-management/dnf5/issues/649
Resolves: https://github.com/rpm-software-management/dnf5/issues/650

Implement module disable and reset

---

libdnf5/rpm/nevra.cpp

It enhances glob support for NEVRA
Closes: https://github.com/rpm-software-management/dnf5/issues/614
CI-test - https://github.com/rpm-software-management/ci-dnf-stack/pull/1371

Modify parsing parsing algorithm

---

COPYING.md

https://github.com/rpm-software-management/dnf5/issues/863

doc: Add libdnf5-plugins to lgpl-2.1-or-later list in COPYING.md

---

libdnf5/base/.idea/.gitignore
libdnf5/base/.idea/base.iml
libdnf5/base/.idea/modules.xml
libdnf5/base/.idea/vcs.xml

Delete files that were pushed by mistake during refactoring.

Remove accidentally pushed files

---

dnf5.spec
doc/CMakeLists.txt
doc/conf.py.in
doc/dnf5.8.rst

forcearch: Fix man pages deployment

---

doc/commands/group.8.rst

This patch documents "dnf5 group upgrade" subcommand.
Completes: #491

doc: Add "group upgrade"

---

include/libdnf5-cli/output/modulelist.hpp
include/libdnf5/module/module_item.hpp
libdnf5/module/module_item.cpp

Follow-up to https://github.com/rpm-software-management/dnf5/pull/918
Closes: https://github.com/rpm-software-management/dnf5/issues/938

modules: Show default profiles in module list

---

.github/workflows/ci.yml
.github/workflows/package-build.yml

Verified that copr now builds.
https://github.com/rpm-software-management/dnf5/actions/runs/6470177028/job/17565778807?pr=968

Fix COPR builds

---

doc/changes.rst

Closes: https://github.com/rpm-software-management/dnf5/issues/919

advisory: document advisory command changes and few clean ups

---

doc/changes.rst
doc/dnf5.8.rst
doc/misc/aliases.7.rst

Closes: https://github.com/rpm-software-management/dnf5/issues/131

doc: Document aliases for command line arguments

---

.github/workflows/weblate-sync-pot.yml

It would most likely fail anyway.

github: Do not run scheduled workflow on forks

---

.github/actions/weblate-pull-translations/action.yml

When there are no changes in weblate, do not attempt to add a commit.

action: Only commit translations on change

---

AUTHORS.md
dnf5/config/usr/share/dnf5/aliases.d/compatibility.conf

dnf5: Add "mc" alias for "makecache"

---

libdnf5/base/log_event.cpp

Resolves: https://github.com/rpm-software-management/dnf5/issues/1113

log_event: Correct message for HINT_ICASE

---

doc/changes.rst

Fixes [issue945](https://github.com/rpm-software-management/dnf5/issues/945)

document: Global Option --help-cmd dropped

---

dnf5.spec
doc/CMakeLists.txt
doc/changes.rst
doc/conf.py.in
doc/dnf5.8.rst
doc/misc/caching.7.rst
doc/misc/index.rst

- Man page with summary around caching functionality
- Fixes on the main page
- Add changes to the DNF4 vs DNF5 document
Closes #668.

Caching overview man page

---

dnf5-plugins/needs_restarting_plugin/needs_restarting.cpp

For https://github.com/rpm-software-management/dnf5/issues/1184
Following the reproducers in that issue, `UnitsLoadStartTimestamp` seems to consistently have the correct boot time even when `UserspaceTimestamp` is incorrect due to `set-local-rtc 1`. The two times are within a few seconds of each other. I have no idea why `UnitsLoadStartTimestamp` is correct, maybe systemd reads `/etc/adjtime` and adjusts the clock after setting `UserspaceTimestamp` but before setting `UnitsLoadStartTimestamp`.

needs-restarting: get systemd boot time from UnitsLoadStartTimestamp

---

dnf5daemon-server/services/rpm/rpm.cpp

I messed up the merge, so i created a new fork, with the fixed signatures from PR #1232

 register missing dbus transaction signals

---

dnf5.spec

required for https://github.com/rpm-software-management/dnf5/actions/runs/7973173112

Typo in dnf5.spec

---

dnf5-plugins/automatic_plugin/email_message.cpp
dnf5/commands/versionlock/utils.cpp
libdnf5-cli/output/transactioninfo.cpp

Replace `std::format` with `fmt::format`

---

dnf5-plugins/automatic_plugin/automatic.cpp
dnf5-plugins/automatic_plugin/config_automatic.hpp
dnf5-plugins/automatic_plugin/emitters.hpp
dnf5daemon-server/session_manager.cpp
include/libdnf5-cli/output/provides.hpp
libdnf5-cli/output/provides.cpp

Fix for https://github.com/rpm-software-management/dnf5/issues/1312

Fix Clang compilation errors

---

dnf5-plugins/copr_plugin/copr.cpp
dnf5-plugins/copr_plugin/copr_repo.hpp
include/libdnf5/conf/option_bool.hpp
include/libdnf5/conf/option_number.hpp
include/libdnf5/conf/option_path.hpp
include/libdnf5/conf/option_string.hpp
include/libdnf5/conf/option_string_list.hpp
libdnf5/conf/option_bool.cpp
libdnf5/conf/option_number.cpp
libdnf5/conf/option_path.cpp
libdnf5/conf/option_string.cpp
libdnf5/conf/option_string_list.cpp
libdnf5/conf/option_string_private.hpp

Add pImpl to libdnf5::Options*

---

include/libdnf5-cli/output/transaction_table.hpp
libdnf5-cli/output/transaction_table.cpp
libdnf5/repo/repo_downloader.cpp
libdnf5/rpm/package_query.cpp

Closes https://github.com/rpm-software-management/dnf5/issues/1387

Fix: Do not use VLAs in C++ code, do not use `static` func in header files

---

dnf5/bash-completion/dnf5

DNF5: improve bash completion, support for bash-completion >=2.12

---

dnf5.spec
libdnf5-cli/CMakeLists.txt
libdnf5/CMakeLists.txt

This should have been done during 5.2 branch merge.

Bump libdnf5/libdnf5-cli so version

---

doc/changes.rst
doc/dnf5.conf.5.rst
doc/dnf5_plugins/config-manager.8.rst

resolves: https://github.com/rpm-software-management/dnf5/issues/883

Document repo dirs

---

dnf5daemon-client/commands/repoquery/repoquery.cpp
dnf5daemon-server/utils.cpp

Fixes clang compilation errors:
4 x error: implicit conversion changes signedness
1 x error: variable 'total_bytes_read' set but not used

Fix: implicit conversion changes signedness, unused value

---

dnf5daemon-server/dbus/interfaces/org.rpm.dnf.v0.rpm.Rpm.xml

For: https://github.com/rpm-software-management/dnf5/pull/1284

dnfdaemon: Fix Rpm interface introspection file

---

doc/api/changes_dnf5.2.diff
doc/api/changes_dnf5.2.rst
doc/api/index.rst

To better communicate the changes introduced with the new major version.
This will be then also referenced on the 5.2.0.0 GitHub release page.

docs: Add a page about public API changes in dnf 5.2.0.0

---

libdnf5/conf/vars.cpp

These use-out-of-scope leaks were discovered in libdnf (see https://github.com/rpm-software-management/libdnf/pull/1661). That code was copied from DNF 5, so the same errors exist here and should be fixed.

Vars::substitute: fix use-out-of-scope leaks

---

libdnf5-cli/argument_parser.cpp

Fixes: https://github.com/rpm-software-management/dnf5/issues/1484

Fix a typo in the message

---

.github/workflows/prepare-release.yml
.packit.yaml

- Use new [v1.2](https://github.com/inknos/prepare-release/tree/v1.2) prepare-release action with 4-digits version format
- Create dist-git PR only for Rawhide

Fix Packit releases

---

doc/changes.rst

docs: Document changes to repoinfo and repolist

---

dnf5.spec
libdnf5/CMakeLists.txt
libdnf5/repo/librepo.cpp

Closes: https://github.com/rpm-software-management/dnf5/issues/1556
Requires librepo version >= 1.18.0 (https://github.com/rpm-software-management/librepo/pull/316)

Support colon in username, use LRO_USERNAME and LRO_PASSWORD

---

include/libdnf5/base/goal_elements.hpp
libdnf5/base/goal.cpp
libdnf5/base/log_event.cpp

It provides additional description about result of debug_install.
Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1524

Add reports when corresponding debug package is not available

---

dnf5/main.cpp

Improve "After this operation" disk usage messages

---

dnf5.spec

Follow up for: https://github.com/rpm-software-management/dnf5/pull/1582

spec: fix cmake focus_new arg

---

doc/dnf5.conf.5.rst
include/libdnf5/repo/repo_sack.hpp

Resolves: https://github.com/rpm-software-management/dnf5/issues/1355

doc: Naming of source and debug repos

---

libdnf5/transaction/offline.cpp

Resolves https://github.com/rpm-software-management/dnf5/issues/1693.

offline: Update usage of toml11-devel

---

test/python3/libdnf5/comps/test_comps_iterators.py

Broken in 00615105e commit ("test python3: improve comps tests").

test: Normalize Python code

---

dnf5/commands/download/download.cpp

Closes: https://github.com/rpm-software-management/dnf5/issues/1904

Download cmd: Require at leats one argument/package to download

---

libdnf5-cli/libdnf5-cli.pc.in

Incorrect library name in libdnf5-cli.pc

---

dnf5/commands/versionlock/versionlock_add.cpp

There’s a bug in how the `dnf5 versionlock add <spec>` command handles
package specifications when the `spec` contains a wildcard and matches
multiple package names with the same version (EVR). In such cases, only
the first package is considered, while the rest are quietly skipped.
For example there are three packages matching 'aws-checksums*' pattern,
but only one is actually locked:
❯ dnf repoquery 'aws-checksums*'
Repositories loaded.
aws-checksums-0:0.2.2-1.fc40.i686
aws-checksums-0:0.2.2-1.fc40.x86_64
aws-checksums-devel-0:0.2.2-1.fc40.i686
aws-checksums-devel-0:0.2.2-1.fc40.x86_64
aws-checksums-libs-0:0.2.2-1.fc40.i686
aws-checksums-libs-0:0.2.2-1.fc40.x86_64
❯ dnf versionlock add 'aws-checksums*'
Repositories loaded.
Adding versionlock on "aws-checksums = 0.2.2-1.fc40".
With this …

versionlock: Fix wildcards handling in `add` command

---

libdnf5/repo/repo_sack.cpp

Closes: https://github.com/rpm-software-management/dnf5/issues/1605
The `OnScopeExit` class is used to ensure proper termination of the `thread_sack_loader` in case of unexpected exit of the `update_and_load_repos` method due to an exception.
If the `thread_sack_loader` is not terminated (joined) before the method exits, the program will crash. Before this fix, the program crashed, for example, on an exception generated during pgp key import.

Fix: RepoSack::update_and_load_repos: properly terminate thread_sack_loader on exception

---

bindings/libdnf5/comps.i
doc/dnf5.conf.5.rst
include/libdnf5/base/base.hpp
include/libdnf5/comps/comps_sack.hpp
include/libdnf5/comps/environment/query.hpp
include/libdnf5/comps/group/query.hpp
include/libdnf5/conf/config_main.hpp
libdnf5/base/base.cpp
libdnf5/base/base_impl.hpp
libdnf5/comps/comps_sack.cpp
libdnf5/comps/comps_sack_impl.hpp
libdnf5/comps/environment/query.cpp
libdnf5/comps/group/query.cpp
libdnf5/conf/config_main.cpp
libdnf5/repo/repo_sack.cpp
test/libdnf5/comps/test_environment_query.cpp
test/libdnf5/comps/test_environment_query.hpp
test/libdnf5/comps/test_group_query.cpp
test/libdnf5/comps/test_group_query.hpp

Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1643

Add group and environment excludes

---

libdnf5-plugins/expired-pgp-keys/expired-pgp-keys.cpp

Resolves: https://github.com/rpm-software-management/dnf5/issues/2142

expired-pgp-keys: Respect install root

---

dnf5/commands/repoquery/repoquery.cpp
doc/commands/repoquery.8.rst

resolves: https://github.com/rpm-software-management/dnf5/issues/1835

Add `-i` and `-f` shoft options for repoquery

---

doc/commands/offline.8.rst
doc/commands/system-upgrade.8.rst

The name was intentionally retained for compatibility with DNF4.

doc: DNF_SYSTEM_UPGRADE_NO_REBOOT environment variable

---

dnf5.spec

- fix building without man pages
- fix building without dnf5 plugins
- fix building without any libdnf5 plugin

Various fixes for the dnf5.spec file

---

dnf5/commands/history/history_redo.cpp
dnf5/commands/history/history_rollback.cpp
dnf5/commands/history/history_undo.cpp

resolves: https://github.com/rpm-software-management/dnf5/issues/2026

Ask for superuser privileges on `history <undo|redo|rollback>`

---

libdnf5-cli/argument_parser.cpp

resolves: https://github.com/rpm-software-management/dnf5/issues/1881

Fix invalid hint for unknown short argument

---

dnf5daemon-server/services/base/base.cpp

As long as the cache can be reloaded without admin privileges, it might be possible to expire it without the privileges too. That way it's possible to do a full refresh of the repos without admin privileges.
Fixes https://github.com/rpm-software-management/dnf5/issues/1659

dnfdaemon: Allow Base::clean("expire-cache") without admin privileges

---

libdnf5-cli/output/transactionlist.cpp

resolves: https://github.com/rpm-software-management/dnf5/issues/2025

Fix `history list` with unknown terminal size

---

dnf5/commands/clean/clean.cpp
include/libdnf5/repo/repo_cache.hpp
libdnf5/repo/repo_cache.cpp
libdnf5/repo/repo_cache_private.hpp

resolves: https://github.com/rpm-software-management/dnf5/issues/817

Show cleaned space bytes for `dnf clean`

---

libdnf5/comps/environment/environment.cpp
libdnf5/comps/group/group.cpp
test/data/repos-repomd/repomd-comps-minimal-environment-v2/repodata/comps.xml
test/data/repos-repomd/repomd-comps-minimal-environment-v2/repodata/repomd.xml
test/libdnf5/comps/test_environment.cpp
test/libdnf5/comps/test_group.cpp

Resolves: https://github.com/rpm-software-management/dnf5/issues/183
Resolves: https://github.com/rpm-software-management/dnf5/issues/881
Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1653

comps: Merging packagelists, grouplists and optionlists

---

README.md

Our IRC channel should be easy to find. Matches https://github.com/rpm-software-management/dnf/pull/2232 and https://github.com/rpm-software-management/dnf-plugins-core/pull/584.

README: Mention #dnf IRC channel in first section

---

.packit.yaml
dnf5.spec
include/libdnf5/repo/repo.hpp
libdnf5/CMakeLists.txt
libdnf5/repo/download_data.cpp
libdnf5/repo/download_data.hpp
libdnf5/repo/file_downloader.cpp
libdnf5/repo/package_downloader.cpp
libdnf5/repo/repo.cpp
libdnf5/repo/repo_downloader.cpp
libdnf5/repo/repo_downloader.hpp
libdnf5/repo/repo_sack.cpp
libdnf5/repo/solv_repo.cpp
libdnf5/repo/solv_repo.hpp

Requires: https://github.com/rpm-software-management/librepo/pull/336
For https://github.com/rpm-software-management/dnf5/issues/307
I have also created a testing COPR: https://copr.fedorainfracloud.org/coprs/amatej/dnf5-parallel/
I am afraid this will be hard to review because the commits are quite interconnected and they don't really work separately.
I was considering making them more standalone but then the PR would contain code that is added just to be removed.

Enable parallel downloading of main repository metadata 

---

doc/dnf_daemon/dnf5daemon_dbus_api.8.rst
doc/dnf_daemon/dnf5daemon_server.8.rst
doc/dnf_daemon/examples.rst
doc/dnf_daemon/index.rst

Closes: https://github.com/rpm-software-management/dnf5/issues/1396

Expose dnf5daemon D-Bus Python examples in the docs

---

libdnf5/base/base.cpp
libdnf5/system/state.cpp
libdnf5/system/state.hpp
test/libdnf5/system/test_state.cpp

Closes: https://github.com/rpm-software-management/dnf5/issues/1609

Make system state files writing more robust

---

dnf5daemon-client/commands/command.cpp

We need to call server methods without blocking the current thread. Otherwise, the dnf5daemon-client cannot handle signals reporting progress of repository/package downloading and RPM transactions. Unfortunately, the repository key import confirmation workflow also depends on signal handling.
Curiously, blocking calls used to work with sdbus-cpp v1, but with v2 any signal handler was blocked until the call finished.
Hopefully, thish should resolve dnfdaemon CI tests failures.

dnfdaemon-client: Call server methods asynchronously

---

dnf5daemon-server/session.cpp

The compiler decides when the variables are freed and the end of the function and when the `user_data` is freed before the `downloader`, then the `downloader` uses just freed `user_data` in the callbacks.
Fixes https://github.com/rpm-software-management/dnf5/issues/2015

dnfdaemon: Crash under dnf5daemon::DownloadCB::create_signal_download()

---

libdnf5/repo/package_downloader.cpp

See the comment for more info.
For: https://bugzilla.redhat.com/show_bug.cgi?id=2381859
Test: https://github.com/rpm-software-management/ci-dnf-stack/pull/1709

Disable fastest_mirror callback for package downloading

---

doc/changes_from_dnf4.7.rst
doc/index.rst
doc/tutorial/api-changes/index.rst
doc/tutorial/api-changes/queries.rst
doc/tutorial/api-changes/repos.rst
doc/tutorial/api-changes/session.rst
doc/tutorial/api-changes/transaction.rst
test/python3/libdnf5/tutorial/api_changes_from_dnf4/configure_base.py
test/python3/libdnf5/tutorial/api_changes_from_dnf4/create_base.py
test/python3/libdnf5/tutorial/api_changes_from_dnf4/group_query.py
test/python3/libdnf5/tutorial/api_changes_from_dnf4/load_repos.py
test/python3/libdnf5/tutorial/api_changes_from_dnf4/package_query.py
test/python3/libdnf5/tutorial/api_changes_from_dnf4/transaction.py
test/python3/libdnf5/tutorial/test_api_changes_from_dnf4.py
test/python3/libdnf5/tutorial/test_tutorial.py
test/tutorial/api_changes_from_dnf4/configure_base.cpp
test/tutorial/api_changes_from_dnf4/create_base.cpp
test/tutorial/api_changes_from_dnf4/group_query.cpp
test/tutorial/api_changes_from_dnf4/load_repos.cpp
test/tutorial/api_changes_from_dnf4/package_query.cpp
test/tutorial/api_changes_from_dnf4/transaction.cpp
test/tutorial/test_api_changes_from_dnf4.cpp
test/tutorial/test_api_changes_from_dnf4.hpp

It's not an exhaustive list, rather a comparison of the most common use cases.

Document API changes between DNF and DNF5

---

doc/tutorial/api-changes/transaction.rst
test/python3/libdnf5/tutorial/api_changes_from_dnf4/download_callbacks.py
test/python3/libdnf5/tutorial/api_changes_from_dnf4/transaction_callbacks.py
test/python3/libdnf5/tutorial/test_api_changes_from_dnf4.py
test/tutorial/api_changes_from_dnf4/download_callbacks.cpp
test/tutorial/api_changes_from_dnf4/transaction_callbacks.cpp
test/tutorial/test_api_changes_from_dnf4.cpp
test/tutorial/test_api_changes_from_dnf4.hpp

This is a follow-up to https://github.com/rpm-software-management/dnf5/pull/2399

Document API changes in callbacks between DNF and DNF5

---

doc/libdnf5_plugins/actions.8.rst

- extends documentation with description of "json" communication mode
- adds information about the loading order of ".action" files
- minor fixes (typos, articles the, a, an; commas in sentences)
- unifies indentation
Closes: https://github.com/rpm-software-management/dnf5/issues/2083

libdnf5 actions plugin: Document "json" communication mode, polishing
