CMakeLists.txt
libdnf-plugins/CMakeLists.txt
libdnf-plugins/actions/CMakeLists.txt
libdnf-plugins/actions/actions.cpp
libdnf5.spec

Libdnf plugin that allows to run actions (external executables) on hooks.
CI tests PR https://github.com/rpm-software-management/ci-dnf-stack/pull/1133
Original PR https://github.com/rpm-software-management/libdnf/pull/1550 was pushed (and reviewed) to the libdnf git repository. After creating the new DNF5 git repository, the PR was pushed here.

Actions plugin

---

dnf5daemon-server/threads_manager.hpp

sdbus-cpp-1.2 is landing in rawhide and one of changes was making used
sdbus::Error constructor explicit. Therefore not usable for copy-initialization.

Fix building against sdbus-cpp-1.2

---

dnf5/main.cpp
include/libdnf/base/base.hpp
libdnf/base/base.cpp

We want the libdnf library to load the plugins automatically without the need for a call in the application.

Move call to load libdnf plugins from application to base.setup()

---

libdnf/repo/solv_repo.cpp

The checksum is not a string, but a byte array.
Convert it to a hexadecimal string.

Fix formating of solv_userdata->checksum in logging message

---

dnf5/commands/advisory/advisory_subcommand.cpp
dnf5/commands/install/install.cpp
dnf5/commands/repoquery/repoquery.cpp
dnf5/commands/upgrade/upgrade.cpp

Follow up for: https://github.com/rpm-software-management/libdnf/pull/1556
I discovered this while working on enabling advisory CI tests.

Load updateinfo when needed + filelists in upgrade command

---

dnf5/commands/repoquery/repoquery.cpp

Instead of the exact versions that match advisory packages show all
exact matches plus higher versions (which also resolve the advisory).
dnf4 shows equal or if there is none then the first higher. Given that
this is not documented anywhere I think we could change it to show equal
plus all higher. Which seems to make more sense to me for repoquery.
For: https://github.com/rpm-software-management/ci-dnf-stack/pull/1101

Repoquery: show all packages that resolve selected advisories

---

.github/workflows/clang-format.yml

Currently the workaround for Fedora 36 clang-format issue
(https://github.com/llvm/llvm-project/issues/55260) is in the
dnf-ci-host container (see
https://github.com/rpm-software-management/ci-dnf-stack/commit/23e4400f4f66441f1c604e4aa4ce37d7fc814050
for details).
This PR makes the workaround local to "Clang Format" job. It enables us
to move "DNF Integration Tests" job back to the latest Fedora.

Run clang-format check on vanilla Fedora 35

---

.github/workflows/ci.yml

Let's use the default taken from ci-dnf-stack Dockerfile.

Do not set explicit Fedora release for CI

---

dnf5-plugins/builddep_plugin/builddep.cpp

Follows up fix from dnf4 from https://github.com/rpm-software-management/dnf-plugins-core/pull/461.
Originally reported in https://bugzilla.redhat.com/show_bug.cgi?id=2077820.

builddep: Warning when using macros with source rpms

---

dnf5.spec

According to Fedora packaging guidelines
<https://docs.fedoraproject.org/en-US/packaging-guidelines/#_packaging_header_only_libraries>,
header-only libraries must be pulled in with a -static RPM dependency
symbol. A rationale is that this form of static linking must be
tracked for security purposes.
This patch fixes it.

Depend on toml11 via toml11-static

---

dnf5.spec

With the repository move the %{name} changed the meaning to `dnf5`. We
need requirement on libdnf5.

spec: Fix libdnf requirements

---

include/libdnf-cli/output/environmentinfo.hpp
include/libdnf-cli/output/groupinfo.hpp
libdnf-cli/output/argument_parser.hpp
libdnf-cli/output/key_value_table.cpp
libdnf-cli/progressbar/widgets/number.cpp
libdnf/comps/environment/query.cpp
libdnf/comps/group/query.cpp
libdnf/repo/solv_repo.cpp
libdnf/solv/solv_map.hpp
test/libdnf/module/test_module.cpp

Even with these patches running with sanitizers still doesn't pass cleanly. However I believe the remaining reports are not problems with dnf5 or I wasn't able to figure it out at this time.
Couple of notes for future reference:
Note 1
---
Just about every run of dnf5 binary produces:
```
==16==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 8 byte(s) in 1 object(s) allocated from:
#0 0x7f2bebc2e68f in __interceptor_malloc (/lib64/libasan.so.8+0xba68f)
#1 0x7f2be83a373c  (<unknown module>)
```
I am not sure to what does this refer to but it is somehow connected to dynamic loading of plugins (`dlopen()` - `dlclose()`) because when the `dlclose()` is commented out the reported leak disappears. I was able to find that running sanitizers with dynamic library loading is problematic …

Fix issues find by running with sanitizers

---

libdnf/transaction/db/arch.cpp
libdnf/transaction/db/arch.hpp
libdnf/transaction/db/comps_group_package.cpp
libdnf/transaction/db/pkg_name.cpp
libdnf/transaction/db/pkg_name.hpp
libdnf/transaction/db/rpm.cpp
libdnf/transaction/db/sql/create_tables.sql

To be consistent with other table names.

HistoryDB: Rename tables "pkg_names" and "archs" to singular form

---

libdnf-cli/progressbar/multi_progress_bar.cpp
libdnf/module/module_item_container_impl.hpp

Also fixes a memory leak of `pool`.

Fix clang rawhide build by removing unused variable

---

dnf5/commands/remove/remove.cpp
dnf5/main.cpp
dnf5daemon-server/services/goal/goal.cpp
include/libdnf/base/goal.hpp
libdnf/base/goal.cpp
test/libdnf/base/test_goal.cpp
test/libdnf/rpm/test_transaction.cpp
test/tutorial/transaction/transaction.cpp

It is more transparent to have a setter then a bool argument for resolve. The setter does not accept the value because it prevents unwanted reset of already set value.

Add setter for allow_erasing to Goal

---

dnf5/commands/distro-sync/distro-sync.cpp
dnf5/commands/downgrade/downgrade.cpp
dnf5/commands/downgrade/downgrade.hpp
dnf5/commands/install/install.cpp
dnf5/commands/install/install.hpp
dnf5/commands/shared_options.hpp
dnf5/commands/swap/swap.cpp
dnf5/commands/swap/swap.hpp
dnf5/commands/upgrade/upgrade.cpp
dnf5/commands/upgrade/upgrade.hpp

The option was added to commands for which it makes sense.
This was a global option in dnf4, though it was ignored for many commands.

dnf5: Add option "--allowerasing"

---

bindings/libdnf5/conf.i
bindings/libdnf5/repo.i
include/libdnf/base/base.hpp
include/libdnf/conf/config.hpp
include/libdnf/conf/config_main.hpp
include/libdnf/repo/config_repo.hpp
libdnf/base/base.cpp
libdnf/conf/config.cpp
libdnf/conf/config_main.cpp
libdnf/config.h.in
libdnf/repo/config_repo.cpp

The default configuration is loaded from "INSTALL_PREFIX/lib/dnf5/libdnf.conf" file.

Base: Load default (distribution-specific) configuration

---

dnf5/commands/history/arguments.hpp
dnf5/commands/history/history_info.cpp
dnf5/commands/history/history_info.hpp
dnf5/commands/history/history_list.cpp
dnf5/commands/history/history_list.hpp
dnf5/commands/history/transaction_id.cpp
dnf5/commands/history/transaction_id.hpp
dnf5/main.cpp
include/libdnf/transaction/comps_environment.hpp
include/libdnf/transaction/comps_group.hpp
include/libdnf/transaction/rpm_package.hpp
include/libdnf/transaction/transaction_history.hpp
include/libdnf/transaction/transaction_item.hpp
libdnf/transaction/comps_environment.cpp
libdnf/transaction/comps_group.cpp
libdnf/transaction/db/trans.cpp
libdnf/transaction/db/trans.hpp
libdnf/transaction/rpm_package.cpp
libdnf/transaction/transaction_history.cpp
libdnf/transaction/transaction_item.cpp

Comes without tests as of now, they'll require parsing the `history list` output, which is not that easy, as column separators are spaces, which can also appear in a lot of the column values.

Implement history transaction ID ranges and `last`

---

libdnf/base/transaction.cpp
libdnf/utils/locker.cpp
libdnf/utils/locker.hpp

Just a small commit that adds read/write locking support to the `Locker` class I did in preparation for locking the system state.

libdnf/utils/locker: Add support for read/write locking

---

dnf5/context.cpp
dnf5/include/dnf5/context.hpp
dnf5/main.cpp
dnf5daemon-server/session.cpp
dnf5daemon-server/session.hpp
dnf5daemon-server/session_manager.cpp
include/libdnf/base/base.hpp
include/libdnf/logger/log_router.hpp
libdnf/base/base.cpp

We want to capture all messages from the context in the log.

dnf5: Create MemoryBufferLogger before Context 

---

bindings/libdnf5/base.i
include/libdnf/base/base.hpp
libdnf/base/base.cpp
libdnf/base/base_impl.hpp
libdnf/solv/pool.hpp

The "get_pool(const libdnf::BaseWeakPtr & base)" function is only intended for internal use within the libdnf library. That's why the Base class didn't have a public "get_pool()" method. Which didn't solve anything. The "get_pool" is still on the public API, only it is not a method of the Base class, but a function in the "libdnf" namespace. And disallowing the export of this function for other languages in SWIG is just a crutch. It does not address the C++ API.
This PR moves "pool" to p_impl and removes the "get_pool" function from the public API.

Base: Hide "pool" from public

---

dnf5daemon-server/dbus/org.rpm.dnf.v0.conf

Let's use simple best-practice policy file from dbus documentation.

Fix rpmlint dbus-policy-allow-without-destination errors

---

dnf5.spec

Provides are auto-generated
https://docs.fedoraproject.org/en-US/packaging-guidelines/Perl/#_build_dependencies
Testing on copr...

remove Provides for perl

---

include/libdnf/conf/const.hpp
libdnf/conf/config_main.cpp

/usr/lib/sysimage/dnf/ -> /usr/lib/sysimage/libdnf5/
/var/cache/libdnf/ -> /var/cache/libdnf5/
~/.cache/dnf/ -> ~/.cache/libdnf5/
Requests a change in the CI. PR: https://github.com/rpm-software-management/ci-dnf-stack/pull/1165

Better consistency of libdnf5 library file locations

---

dnf5/context.cpp
include/libdnf/rpm/transaction_callbacks.hpp
libdnf/base/transaction.cpp
libdnf/rpm/transaction.cpp

The output of the RPM scriptlets was  written to the "scriptlet.out" file in the current working directory and was owerwritten every time dnf5 was run.
Now there is a thread that processes output from the RPM scriptlets and writes it to the logger.
Logging of RPM transaction callbacks was also added. It is possible to read from the log which scriptlet the given output is from.

Write output of RPM scriptlets to logger

---

include/libdnf/common/xdg.hpp
libdnf/common/xdg.cpp
libdnf/conf/config_main.cpp

It is a question of where to save the logger files in XDG. Basically, there are 2 options - STATE category and DATA category.
Following this proposal https://wiki.debian.org/XDGBaseDirectorySpecification I moved the logger file to the STATE category.

Add "get_user_state_dir" func,  move non-root user log file to "~/.local/state/" ($XDG_STATE_HOME) 

---

include/libdnf/module/module_sack.hpp
libdnf/module/module_sack.cpp
libdnf/module/module_sack_impl.hpp
test/libdnf/module/test_module.cpp

Removal supporting and unnecessary functions from API will improve clarity of API and allows further modifications in future.
As an consequence of movement and resolving accessing private methods, the movement resolves auto processing of modules without static context.

modules: Move code to private section or Impl

---

include/libdnf/base/transaction.hpp
include/libdnf/base/transaction_group.hpp
include/libdnf/base/transaction_package.hpp
include/libdnf/rpm/transaction_callbacks.hpp
libdnf/base/transaction.cpp
libdnf/base/transaction_impl.hpp
test/libdnf/base/test_goal.cpp
test/libdnf/rpm/test_transaction.cpp
test/libdnf/utils.hpp

Method `set_reason()` was removed from the public API and also a visibility of related members was fixed to (hopefully) originally planned level. Due to these changes also some header includes reordering and other small refactoring was necessary.

Remove set_reason() from transaction public API

---

libdnf/rpm/transaction.cpp

The repackage callbacks are 15 years gone upstream, they are best treated as unknown events. As for RPMCALLBACK_UNKNOWN, this is a nice little rpm-side WTF: an enum whose value is 0 isn't exactly unknown, so the value doesn't make any sense whatsoever.
Replace these with a default case to warn on all actually unknown events.

libdnf: handle unknown events in the rpm transaction callback

---

test/libdnf/base_test_case.cpp

Simpler solution than: https://github.com/rpm-software-management/dnf5/pull/94

Force test arch to x86_64

---

test/libdnf/base_test_case.cpp
test/libdnf/private_accessor.hpp

There are now two macros available to create a getter:
* `create_getter` - A macro that uses automatic member type deduction.
* `create_getter_type` - Macro that gets the type of a member as an argument. Needed in case of overloaded members.
The getter generating structure is now also created by the macro. This makes the structure no longer global. The user can create it in their own namespace or in an unnamed namespace.

[unit tests] Support accessing overloaded private members, unnamed namespace

---

include/libdnf/transaction/comps_environment.hpp
include/libdnf/transaction/comps_group.hpp
include/libdnf/transaction/rpm_package.hpp
include/libdnf/transaction/transaction.hpp
libdnf/transaction/db/comps_environment.cpp
libdnf/transaction/db/comps_environment.hpp
libdnf/transaction/db/comps_environment_group.cpp
libdnf/transaction/db/comps_environment_group.hpp
libdnf/transaction/db/comps_group.cpp
libdnf/transaction/db/comps_group.hpp
libdnf/transaction/db/comps_group_package.cpp
libdnf/transaction/db/comps_group_package.hpp
libdnf/transaction/db/rpm.cpp
libdnf/transaction/db/rpm.hpp
libdnf/transaction/transaction.cpp
test/libdnf/transaction/test_comps_environment.cpp
test/libdnf/transaction/test_comps_group.cpp
test/libdnf/transaction/test_rpm_package.cpp
test/libdnf/transaction/test_workflow.cpp

This is a follow up for: https://github.com/rpm-software-management/dnf5/pull/97
It uses the same approach to make API private and test it using the `create_getter()` hack.

Make private not used parts of transaction API

---

include/libdnf/transaction/comps_group.hpp
include/libdnf/transaction/transaction_item.hpp
libdnf/transaction/db/comps_environment.cpp
libdnf/transaction/db/comps_group.cpp
libdnf/transaction/db/rpm.cpp
libdnf/transaction/db/trans_item.cpp
libdnf/transaction/db/trans_item.hpp
test/libdnf/transaction/test_comps_group.cpp
test/libdnf/transaction/test_workflow.cpp

I wanted to include this in https://github.com/rpm-software-management/dnf5/pull/106 but I was too slow and I didn't properly mark the PR.

Make `TransactionItem` parts unused from outside `private`

---

include/libdnf/base/base.hpp
include/libdnf/comps/environment/environment.hpp
include/libdnf/comps/group/group.hpp
include/libdnf/repo/repo.hpp
libdnf/base/goal.cpp
libdnf/base/transaction.cpp
libdnf/comps/environment/environment.cpp
libdnf/comps/group/group.cpp
libdnf/repo/repo.cpp
libdnf/repo/solv_repo.cpp
libdnf/repo/solv_repo.hpp
libdnf/system/state.cpp
libdnf/system/state.hpp
test/libdnf/comps/test_environment.cpp
test/libdnf/comps/test_environment.hpp
test/libdnf/comps/test_group.cpp
test/libdnf/comps/test_group.hpp

Comps metadata for each installed group is now stored in the system state and loaded into libsolv pool from there.

state: Store and load system repo groups metadata

---

dnf5/commands/remove/remove.cpp
dnf5/config/usr/lib/dnf5/aliases.d/compatibility.conf

`--unneeded` option is not yet implemented in `remove` command, therefore commenting it out for now.

commands: Remove unimplemented unneeded option

---

include/libdnf/base/goal.hpp
include/libdnf/base/log_event.hpp
libdnf/base/goal.cpp
libdnf/base/log_event.cpp
libdnf/base/transaction.cpp
libdnf/base/transaction_impl.hpp

To correctly print LogEvent messages we need to distinguish what object type the `spec` attibute was matched against.

Extend LogEvent with new attribute spec_type

---

dnf5/context.cpp
include/libdnf-cli/progressbar/progress_bar.hpp
libdnf-cli/progressbar/progress_bar.cpp

There are some uninteresting progress events with zero values coming at the beginning of the metadata download which causes the percent widget to show `100%` before the actual downloading starts.
As there is already implemented showing the `???%`, I assume this was the original intention, so I fixed the incorrectly initialized members in the `ProgressBar` class.
This is a follow-up of https://github.com/rpm-software-management/dnf5/pull/130

Fix showing full percentage progress before metadata download start

---

.clang-tidy

Previously, the clang-tidy configuration enables all checks and then disables a few undesired ones. This enables a lot of checks that are specific to certain kinds of code and aren't relevant for this project. For example, I noticed several errors from checks specific to LLVM libc. It makes more sense to enable only the checks that we want instead of enabling everything and then disabling the checks that we don't want.

Disable irrelevant clang-tidy checks

---

CHANGES-DNF-5.md

Add main heading with links to dnf components to be clear about the
documents subject.
Split the doc to two main sectiosn:
- Changes on the API
- Changes on the command line
to make it more readable.
Also document several Repoquery options as dropped.

dnf5-changes-doc: Add more structure and document dropped repoquery options

---

dnf5/commands/repoquery/repoquery.cpp
dnf5/commands/repoquery/repoquery.hpp
include/libdnf/rpm/package_query.hpp
libdnf/rpm/package_query.cpp

Adds `filter_duplicates()` method to `PackageQuery`.
Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1187

Repoquery: Add --duplicates option

---

dnf5.spec
dnf5/CMakeLists.txt
dnf5/include/CMakeLists.txt
dnf5/include/dnf5/CMakeLists.txt

Files in dnf5/include are necessary to build plugins. This commit adds header files to cmake installed files and dnf5-devel package in the dnf5 specfile.

Add dnf5-devel package

---

dnf5/commands/download/download.cpp
dnf5/main.cpp
include/libdnf-cli/argument_parser.hpp

Add catch condition in main for
libdnf::cli::ArgumentParserConflictingArgumentsError. When exception is caught the help should be printed to show the correct arguments usage.

Throw Exception if alldeps used without resolve

---

dnf5.spec
dnf5/context.cpp
dnf5/main.cpp
dnf5daemon-client/callbacks.cpp
dnf5daemon-server/callbacks.cpp
dnf5daemon-server/callbacks.hpp
include/libdnf-cli/output/repo_info.hpp
include/libdnf/repo/repo_callbacks.hpp
include/libdnf/repo/repo_errors.hpp
include/libdnf/rpm/rpm_signature.hpp
libdnf/CMakeLists.txt
libdnf/repo/repo_downloader.cpp
libdnf/repo/repo_downloader.hpp
libdnf/repo/repo_gpgme.cpp
libdnf/repo/repo_gpgme.hpp
libdnf/repo/repo_pgp.cpp
libdnf/repo/repo_pgp.hpp
libdnf/rpm/rpm_signature.cpp
test/libdnf/repo/test_repo.cpp

Librepo internally uses gpgme to work with PGP keys. Libdnf used the librepo keyring directly via gpgme instead of using the librepo API. It had to, the librepo API was insufficient.
Librepo in version 1.15.0 extended the PGP API.
This commmit uses the extended librepo PGP API and removes libdnf's dependency on gpgme.
PR also adds support for any number of user IDs in a PGP key.
This PR requires new librepo PGP API PR https://github.com/rpm-software-management/librepo/pull/266 .

PGP: Use new librepo PGP API, remove gpgme dependency

---

common/utils/url.cpp

`std::tolower()` takes an `int` instead of a `char`, and it's undefined behavior if the `int` value is not representable as an `unsigned char` or equal to `EOF`. Therefore, casting the argument to `unsigned char` is necessary to avoid potential UB if `char` is signed and `ch` is not an ASCII character. See https://en.cppreference.com/w/cpp/string/byte/tolower#Notes.

Cast std::tolower() argument to unsigned char to avoid possible UB

---

dnf5/commands/group/group.cpp
dnf5/commands/group/group_install.cpp
dnf5/commands/group/group_remove.cpp
dnf5/commands/group/group_remove.hpp
include/libdnf/base/base.hpp
include/libdnf/base/goal.hpp
libdnf/base/goal.cpp
libdnf/rpm/solv/goal_private.hpp

Implement the `dnf5 group remove` command.
While removing the group also packages that meet all following criteria are removed from the system:
- package is installed with GROUP reason
- package is not part of any other installed group
- package is not required by any other package. In such case the package is left on the system, but its reason is changed to DEPENDENCY.

Group remove command

---

dnf5/context.cpp
dnf5/include/dnf5/context.hpp
include/libdnf/utils/patterns.hpp
libdnf/advisory/advisory_query.cpp
libdnf/base/goal.cpp
libdnf/module/module_query.cpp
libdnf/rpm/package_query.cpp
libdnf/utils/convert.hpp

Move the function for detecting file patterns to the API and use it consistently across the codebase. Also other functions for the `utils_internal.hpp` were moved to the API as I think we can consider them generic.

Unify matching file patterns

---

libdnf/repo/repo_downloader.cpp
libdnf/repo/repo_downloader.hpp

Before downloading files (packages) from the repository, Librepo itself downloads a metalink/mirrorlist file to a temporary file (if the metalink/mirrorlist url was defined in the configuration) and parses it. An unexpected call to the progress callback occurred while doing so. This fix ensures that the progress callback will not be called.
This fix is not ideal. We should know that librepo is downloading an extra file in the background. For example, in case of network problems, the program may hang for some time and we will not know why. It's just a quick fix for the crash.
The question is, do we even want librepo to download metalink/mirrorlist files itself every time before downloading files from the repository? Why are the metalink/mirrorlist files in the cache?

Fix: RepoDownloader::get_cache_handle: Don't set callbacks in LibrepoHandle

---

dnf5/context.cpp
libdnf-cli/progressbar/download_progress_bar.cpp

- Moves finished (downloaded) packages up (fixes/removes repeating download progress bars of currently downloaded packages).
- Removes empty lines between progress bars.

[dnf5] Fix progress bars during downloading packages

---

dnf5/main.cpp

- Fix: Do not pass formatted message as the first parameter to the logger
fixes "terminate called after throwing an instance of 'fmt::v9::format_error'". 
- Catch only exceptions inherited from std::runtime_error

[dnf5] Fix: Handling of unknown exceptions

---

dnf5/context.cpp
dnf5daemon-client/callbacks.cpp
dnf5daemon-client/callbacks.hpp
include/libdnf-cli/progressbar/multi_progress_bar.hpp
libdnf-cli/progressbar/multi_progress_bar.cpp

In current implementation MultiProgressBar only keeps raw pointers to its encapsulated ProgressBar instances.
I think the ownership of progress bars should be transfered to MultiProgressBar and their lifecycles kept tied together.

MultiProgressBar: Take ownership of included ProgressBars

---

bindings/libdnf5/comps.i
bindings/libdnf5/rpm.i
test/python3/libdnf5/rpm/test_package_query.py

Include transaction module prior to dependent modules, otherwise enum wrappers are not ready for these modules.
Resolves #216.

swig: Fix TransactionItemReason wrappers

---

CHANGES-DNF-5.md
include/libdnf/conf/config_main.hpp
include/libdnf/repo/config_repo.hpp
libdnf/conf/config_main.cpp
libdnf/conf/option_string.cpp
libdnf/conf/option_string_list.cpp
libdnf/repo/config_repo.cpp
libdnf/repo/librepo.cpp
test/libdnf/conf/test_option.cpp

The "proxy_auth_method" option accepted exactly one value from the enum "none", "basic", "digest", "negotiate", "ntlm", "digest_ie", "ntlm_wb", "any".
It is now possible to enter a combination of several authentication methods, for example "basic, digest".

Support for specifying set of allowed proxy authentication methods

---

bindings/perl5/CMakeLists.txt

Perl's config value `ccflags`: https://perldoc.perl.org/Config#ccflags
is defined during its build. Presumably the current build still uses old
settings `-D_FORTIFY_SOURCE=2`.
Once Perl is recompiled with the new `-D_FORTIFY_SOURCE=3` setting this
commit could be reverted.

Fix rawhide build by removing Perl's `-D_FORTIFY_SOURCE=2`

---

test/libdnf/conf/test_option.cpp
test/libdnf/conf/test_option.hpp

Unit tests for newly added methods for option string containers based on the #123.

conf: Add tests for option string lists

---

bindings/perl5/CMakeLists.txt

Outside of fedora build infrastructure `_FORTIFY_SOURCE` is not defined but the perl bindings require it.

Fix build of perl bindings without external `_FORTIFY_SOURCE` define

---

dnf5/context.cpp
dnf5/download_callbacks.cpp
dnf5/download_callbacks.hpp
dnf5/main.cpp
dnf5daemon-client/callbacks.cpp
dnf5daemon-server/callbacks.cpp
dnf5daemon-server/callbacks.hpp
dnf5daemon-server/services/goal/goal.cpp
dnf5daemon-server/session.cpp
include/libdnf/base/base.hpp
include/libdnf/repo/download_callbacks.hpp
include/libdnf/repo/file_downloader.hpp
include/libdnf/repo/package_downloader.hpp
include/libdnf/rpm/package.hpp
libdnf/repo/download_callbacks.cpp
libdnf/repo/file_downloader.cpp
libdnf/repo/package_downloader.cpp
libdnf/rpm/package.cpp
libdnf/rpm/rpm_signature.cpp
test/libdnf/repo/test_package_downloader.cpp
test/libdnf/rpm/test_transaction.cpp
test/python3/libdnf5/repo/test_package_downloader.py
test/python3/libdnf5/tutorial/transaction/transaction.py
test/ruby/libdnf5/repo/test_package_downloader.rb
test/tutorial/transaction/transaction.cpp

Before the change, a unique instance of the `DownloadCallbacks` class was passed for each downloaded object - in the `downloader.add` call. Which was a problem when implicitly adding the necessary downloadable objects in the library (unavailable instance of `DownloadCallbacks`).
Only one instance of `DownloadCallbacks` is now used, which is passed to an instance of the `Base` class. Now we don't need to have an instance of `DownloadCallbacks` available when `downloader.add` is called.
Requires https://github.com/rpm-software-management/ci-dnf-stack/pull/1209

Rework download callbacks

---

dnf5/commands/downgrade/downgrade.cpp
dnf5/commands/downgrade/downgrade.hpp
dnf5/commands/install/install.cpp
dnf5/commands/install/install.hpp
dnf5/commands/reinstall/reinstall.cpp
dnf5/commands/reinstall/reinstall.hpp
dnf5/commands/repoquery/repoquery.cpp
dnf5/commands/repoquery/repoquery.hpp
dnf5/commands/swap/swap.cpp
dnf5/commands/swap/swap.hpp
dnf5/commands/upgrade/upgrade.cpp
dnf5/commands/upgrade/upgrade.hpp
dnf5/context.cpp
dnf5/download_callbacks.cpp
dnf5/download_callbacks.hpp
dnf5/include/dnf5/context.hpp
include/libdnf/base/goal.hpp
include/libdnf/base/goal_elements.hpp
include/libdnf/repo/repo_sack.hpp
libdnf/base/goal.cpp
libdnf/base/goal_elements.cpp
libdnf/base/log_event.cpp
libdnf/repo/repo_sack.cpp
test/libdnf/base_test_case.cpp
test/libdnf/rpm/test_package_query.cpp

New high level API for installing any artifact using the same simple call goal.add_install(spec).
The spec here can be
- a repository package specification matched against NEVRA, provides, and file provides, e.g. "wget", "vim-*"
- a local rpm file (/the/location/package.rpm)
- a URL of remote rpm package
- by using '@' prefix also a group can be specified - @rpm-development-tools
- TODO: once installation of environmental groups and modules is  implemented, also these artifact will be able to be installed

Install spec implementation

---

libdnf/rpm/solv/goal_private.hpp

DNF provides all candidates for transaction to libsolv, therefore we have to force libsolv to use only those candidates for the job solution => to make job TARGETED. If distrosync or upgrade job is not marked as TARGETED explicitly, libsolv mark as TARGETED job without installed package in the set of candidates.
The patch unify upgrade and distrosync flags in DNF5 => using SOLVER_TARGETED.
Resolves: https://github.com/rpm-software-management/dnf5/issues/222

Make distrosync as a targeted operation

---

bindings/libdnf5/conf.i
dnf5/context.cpp
include/libdnf/conf/const.hpp
include/libdnf/conf/option_string_list.hpp
libdnf/conf/config_main.cpp
libdnf/conf/option_string_list.cpp
libdnf/repo/repo_downloader.cpp
libdnf/repo/repo_downloader.hpp
test/libdnf/conf/test_option.cpp

Because `std::unordered_set` is not supported in some bindings yet (even in new SWIG 4.1), moving to `std::set`. We don't expect lot of stored values in these options, so there should be no performance regression.
Also added a commit with some small refactoring to reference defined `OptionStringSet::ValueType` where it makes sense to avoid possible changes in future when internal container implementation is changed.

conf: Change OptionStringSet implementation to std::set

---

test/python3/libdnf5/conf/test_option.py

Basic python binding tests for configuration options covering some of the #226 and #123 functionality.
Requires: #230

Add python binding tests for configuration options

---

libdnf/common/sack/match_int64.cpp
libdnf/common/sack/match_string.cpp
libdnf/rpm/package_sack.cpp

rq.filter_id(disable_excludes, libdnf::sack::QueryCmp::NOT_GLOB) in case of empty `disable_excludes` filters out all repositories.
Resolves https://github.com/rpm-software-management/dnf5/issues/233

Fix repository specific excludes

---

include/libdnf/repo/repo_sack.hpp
libdnf/repo/repo_sack.cpp

Calculating checksums of a package in libsolv is pretty expensive and we do not need this feature for cmdline repo packages.
Related: https://github.com/rpm-software-management/dnf5/issues/237

reposack: No checksums for cmdline repo packages

---

libdnf/rpm/transaction.cpp

Once the transaction is filled, it must be sorted correctly. Otherwise the transaction (especially the "pre" scriptlets) may end up with unsatisfied dependencies.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2164378

rpm: Correctly order rpm transaction items

---

dnf5/commands/clean/clean.cpp
dnf5/plugins.cpp
libdnf-plugins/python_plugins_loader/python_plugins_loader.cpp
libdnf/base/base.cpp
libdnf/repo/repo_sack.cpp
libdnf/rpm/solv/goal_private.cpp

Setting *dir config options to non-existing or non-accessible directory leads to unnecessary crash.
In case of reposdir also a warning is written to the log.
Resolves: https://github.com/rpm-software-management/dnf5/issues/249

Handle std::filesystem::directory_iterator errors

---

bindings/libdnf5/base.i
bindings/libdnf5/common.i
bindings/libdnf5/transaction.i
include/libdnf/repo/download_callbacks.hpp

Allow accessing methods from `TransactionItem` base class and iterating over transaction history items.

swig: Fixes for transaction related bindings

---

include/libdnf/rpm/package_query.hpp
libdnf/rpm/package_query.cpp

Filter installed "extra" packages - packages which are installed, but not available in any repository.

PackageQuery: Add `filter_extras`

---

libdnf/CMakeLists.txt

It's not possible to build the project when the librepo is built in a non-standard prefix, especially when no other project is build with that custom prefix.
Using the returned include directories and whole LDFLAGS fixes it.

libdnf: Add include directories and LDFLAGS from librepo

---

libdnf/module/module_sack_impl.hpp
libdnf/solv/pool.hpp

POOL_FLAG_WHATPROVIDESWITHDISABLED ensures that excluded packages are not taken as candidates for solver. This is specific behavior is unique for DNF, because we runs make provides ready on top of all packages including excluded packages.
Resolves: https://github.com/openSUSE/libsolv/issues/518

Set POOL_FLAG_WHATPROVIDESWITHDISABLED to libsolv pool

---

dnf5/commands/advisory/advisory_subcommand.cpp
dnf5/commands/advisory_shared.hpp
dnf5/commands/group/group_install.cpp
dnf5/commands/install/install.cpp
dnf5/commands/mark/mark.cpp
dnf5/commands/upgrade/upgrade.cpp
dnf5/context.cpp
dnf5daemon-server/services/goal/goal.cpp
include/libdnf/advisory/advisory_query.hpp
include/libdnf/base/goal.hpp
include/libdnf/base/goal_elements.hpp
include/libdnf/base/log_event.hpp
include/libdnf/base/transaction.hpp
include/libdnf/base/transaction_package.hpp
libdnf/advisory/advisory_query.cpp
libdnf/base/goal.cpp
libdnf/base/log_event.cpp
libdnf/base/transaction.cpp
libdnf/base/transaction_impl.hpp
test/libdnf/advisory/test_advisory_query.cpp
test/libdnf/base/test_goal.cpp
test/libdnf/rpm/test_transaction.cpp
test/python3/libdnf5/tutorial/transaction/transaction.py
test/tutorial/transaction/transaction.cpp

SWIG bindings don't support the `std::optional` type wrappers, so this PR aims to drop all these references away from the public API.
Closes #186.

SWIG: drop the std::optional from the public API

---

include/libdnf/module/module_item.hpp
libdnf/conf/config_main.cpp
libdnf/module/module_item.cpp
libdnf/module/module_sack.cpp
libdnf/module/module_sack_impl.hpp

Platform ID for modules is automatically detected based on the following values in given order sorted by priority:
1. Use `module_platform_id` configuration option value, if it is explicitly set up.
2. Parse `Provides` value from the latest available package in enabled repositories.
3. Parse `Provides` value from the latest installed package on the local system.
4. Parse `PLATFORM_ID` value from `os-release` files on the local system.
The logic is implemented based on the original [PR](https://github.com/rpm-software-management/libdnf/pull/712) from `libdnf` component.

Implementation of autodetecting modular platform ID

---

libdnf/solv/reldep_parser.cpp

Passing a very long package name triggered a segfault:
Updating and loading repositories:
Repositories loaded.
Segmentation fault (core dumped)
This is caused by a known bug in GCC std::regex_match().
This patch prevents from the crash by rejecting strings longer than 1 KB. Another solution would be to move to a heap-based regular expression engine, like PCRE2.
<https://bugzilla.redhat.com/show_bug.cgi?id=2164792> <https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86164>

ReldepParser: Reject overlong dependency strings

---

include/libdnf/rpm/nevra.hpp
test/libdnf/rpm/test_nevra.cpp
test/libdnf/rpm/test_nevra.hpp

Current implementation used rpmvercmp() on the whole EVR. But unfortunatelly rpmvercmp does not do any NEVRA parsing, it just compares two strings, which led to incorrect results.
For example these packages are in the current code ordered wrong:
firefox-0:100.0-2.fc36.x86_64
firefox-0:109.0.1-1.fc36.x86_64
the reason is that rmpvercmp() correctly returns that '0:100.0-2.fc36' version string is higher than '0:109.0.1-1.fc36'. But what is true for strings is not true for EVR. We need to compare each part (epoch, version, and release) separately.
For this a new evrcmp() function is introduced.

nevra: Fix cmp_* comparators

---

include/libdnf/rpm/package_query.hpp
libdnf/rpm/package_query.cpp
test/libdnf/rpm/test_package_query.cpp
test/libdnf/rpm/test_package_query.hpp

Current implementation of filter_nevra(PackageSet) accepts only EQ and NEQ comparators.
This change enhances this filter to accept also GT, GTE, LT, and LTE comparators.

PackageQuery: filter_nevra to accept more comparators

---

dnf5.spec

Own dirs and files that dnf5 creates on runtime inside spec file so rpm can be aware of that fles

Own dirs and files that dnf5 creates on runtime

---

include/libdnf/base/transaction.hpp
libdnf/base/transaction.cpp
libdnf/base/transaction_impl.hpp

Allows dry running a transaction using `RPMTRANS_FLAG_TEST` by calling `transaction.verify()`, regardless of what tsflags are set on the base config. So you could run:
```
libdnf::Goal goal(base);
auto transaction = goal.resolve();
auto result = transaction.verify()
// check result of verification, possibly change the transaction
transaction.run(...)
```
without creating a whole new `base` with the RPMTRANS_FLAG_TEST flag set.
Example use case: https://bugzilla.redhat.com/show_bug.cgi?id=2109660

Add `transaction.test()`

---

dnf5.spec

DNF5 will replace microdnf. To provide an upgrade path we need to add obsoletes, provide and symlink to ensure replacement and microdnf and compatibility. When user will try to install microdnf, dnf5 will be automatically installed.

Add obsoletes of microdnf

---

include/libdnf/rpm/package_query.hpp
libdnf/rpm/package_query.cpp

Recent packages are those packages, that were built after the given timestamp.
Needed for `dnf list --recent` implementation.

PackageQuery: Add `filter_recent(timestamp)`

---

dnf5.spec

Some files got added twice in https://github.com/rpm-software-management/dnf5/commit/f8e861b56a3e7c1b2b81a45f8dec86c94b404c1a

Fix path for files in /usr/share

---

bindings/libdnf5/rpm.i

RPM transaction API exposes `Repo` object, so it needs to be wrapped before that.

swig: Include dependent repo module for rpm

---

include/libdnf/rpm/package_query.hpp
libdnf/module/module_goal_private.cpp
libdnf/module/module_goal_private.hpp
libdnf/repo/repo_sack.cpp
libdnf/rpm/package_query.cpp
libdnf/rpm/solv/goal_private.cpp
libdnf/rpm/solv/goal_private.hpp
libdnf/solv/solver.cpp
libdnf/solv/solver.hpp
libdnf/transaction/Swdb.cpp
libdnf/transaction/Swdb.hpp

- introduces new filter_unneeded for package queries. This is important for implementation of  `autoremove` and `list --autoremove` commands
- also wraps libsolv `Solver` class into `libdnf::solv::Solver`. This enables safer memory management and sharing the debugdata writing code.

PackageQuery::filter_unneeded() and wrapper for libsolv Solver class

---

dnf5.spec

The change was suggested by rpminspect. See the description bellow.
Add the indicated explicit Requires to the spec file for the named subpackage. Subpackages depending on shared libraries in another subpackage must carry an explicit
'Requires: SUBPACKAGE_NAME = %{version}-%{release}' in the spec file. VERIFY Subpackage dnf5 on s390x carries
'Requires: libdnf-cli.so.1()(64bit)' which comes from subpackage libdnf5-cli but does not carry an explicit package version requirement. Please add 'Requires: libdnf5-cli = %{version}-%{release}' to the spec file to avoid the need to test interoperability between various combinations of old and new subpackages.

Add explicit package version for libdnf5-cli

---

include/libdnf/base/transaction.hpp
libdnf/base/transaction.cpp
test/libdnf/rpm/test_transaction.cpp
test/python3/libdnf5/tutorial/transaction/transaction.py
test/tutorial/transaction/transaction.cpp

`transaction.download()` downloads all inbound packages on the transaction, equivalent to the following:
```
libdnf::repo::PackageDownloader downloader;
for (auto & tspkg : transaction.get_transaction_packages()) {
if (transaction_item_action_is_inbound(tspkg.get_action())) {
downloader.add(tspkg.get_package());
}
}
downloader.download(true, true);
```
Resolves https://github.com/rpm-software-management/dnf5/issues/277

Add transaction.download()

---

dnf5/context.cpp
dnf5daemon-server/services/goal/goal.cpp
include/libdnf/base/transaction.hpp
libdnf/base/transaction.cpp
test/libdnf/rpm/test_transaction.cpp
test/python3/libdnf5/tutorial/transaction/transaction.py
test/tutorial/transaction/transaction.cpp

All the `transaction.run()` arguments could be optional, therefore changing the API to pass the arguments with class setters.

transaction: Change API to run transaction without args

---

common/utils/regex.hpp
libdnf/module/nsvcap.cpp
libdnf/solv/reldep_parser.cpp
test/libdnf/module/test_module.cpp

There is a known bug in GCC std::regex_match() that exhausts a stack on very long strings.
This patch prevents this by rejecting strings longer than 2 KB. Another solution would be to move to a heap-based regular expression engine, like PCRE2.
<https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86164>

modules: Reject overlong nsvcap strings

---

bindings/libdnf5/conf.i
test/python3/libdnf5/conf/test_vars.py

Throw a Python exception instead of C++ one when undefined variable is being accessed.
Closes #292.

swig: Throw Python exception on undefined var

---

bindings/libdnf5/comps.i
test/python3/libdnf5/comps/test_comps_iterators.py

`EnvironmentQuery` and `GroupQuery` iterators and related wrappers fixed.
Closes #296.

swig: Fix comps iterator wrappers

---

bindings/libdnf5/base.i

As `std::optional` was dropped from the public API, these typemaps for Python are not needed anymore.

swig: Drop unused Python-specific typemaps

---

include/libdnf/base/base.hpp
libdnf/base/base.cpp

The methods is required in some applications with not exactly transparent work-flows.
Resolves: https://github.com/rpm-software-management/dnf5/issues/310

Add a new method whether base was correctly initialized

---

bindings/libdnf5/base.i
bindings/libdnf5/comps.i
bindings/libdnf5/rpm.i
include/libdnf/common/exception.hpp
libdnf/base/base.cpp
libdnf/base/base_impl.hpp
libdnf/common/exception.cpp
test/libdnf/base/test_base.cpp
test/libdnf/base/test_base.hpp
test/python3/libdnf5/base/test_base.py
test/python3/libdnf5/comps/test_group.py
test/python3/libdnf5/rpm/test_package_query.py

Introducing a new `UserAssertionError` to be thrown when clients are using our public API in a bad way.
This one is intended to be handled on the SWIG layer as opposed to the `AssertionError` which is supposed to terminate the process and collect coredump.
Closes #290.

Introduce a new API assertion

---

bindings/CMakeLists.txt
bindings/libdnf5/advisory.i
bindings/libdnf5/base.i
bindings/libdnf5/rpm.i
include/libdnf/advisory/advisory.hpp
include/libdnf/advisory/advisory_collection.hpp
include/libdnf/advisory/advisory_package.hpp
include/libdnf/advisory/advisory_query.hpp
include/libdnf/advisory/advisory_reference.hpp
include/libdnf/advisory/advisory_set.hpp
libdnf/advisory/advisory_query.cpp
test/python3/libdnf5/advisory/test_advisory.py
test/python3/libdnf5/tutorial/transaction/transaction.py

Generate bindings for `Advisory` objects.
This is needed for example for Ansible module, to apply security filters in `GoalJobSettings`.

SWIG: Add advisory bindings

---

bindings/libdnf5/rpm.i
test/data/repos-repomd/repomd-repo1/repodata/other.xml
test/data/repos-repomd/repomd-repo1/repodata/repomd.xml
test/python3/libdnf5/rpm/test_package_query.py

Add bindings for `libdnf::rpm::Package::get_changelogs()` and provide related unit tests.
Closes #320.

SWIG: Add wrapper for package changelogs

---

CHANGES-DNF-5.md

It's a difference between dnf4 and dnf5 and we should forget to mention it in the docs.

Document --strict deprecation

---

dnf5/context.cpp
test/python3/libdnf5/tutorial/transaction/transaction.py

Use the new [transaction.download()](https://github.com/rpm-software-management/dnf5/pull/294) in a couple places instead of using PackageDownloader directly. 
Not sure whether it's worth it to use it [here](https://github.com/rpm-software-management/dnf5/blob/adfdfb0535b62b96a8a4015dedbae663483f2ba9/dnf5daemon-server/services/goal/goal.cpp#L157) since download callbacks need to be set up.

Prefer transaction.download() over directly using PackageDownloader

---

libdnf/rpm/solv/goal_private.hpp

The copy of the solved GoalPrivate is used to detect skipped jobs or usage of non-best candidate in the solution.
Without user_installed_packages set the results of the copy resolving are invalid.

GoalPrivate: Copy ctor to set user_installed_packages

---

include/libdnf/conf/config_main.hpp
include/libdnf/repo/repo.hpp
include/libdnf/repo/repo_sack.hpp
libdnf/conf/config_main.cpp
libdnf/repo/repo_sack.cpp
test/libdnf/base_test_case.cpp
test/libdnf/repo/test_repo.cpp
test/libdnf/repo/test_repo_query.cpp
test/perl5/libdnf5/rpm/test_package_query.t
test/python3/libdnf5/base_test_case.py
test/python3/libdnf5/repo/test_repo.py
test/ruby/libdnf5/base_test_case.rb
test/ruby/libdnf5/repo/test_repo.rb

- New configuration option "disable_multithreading".
- `RepoSack::update_and_load_repos`: Added single-threaded mode (used when multi-threaded mode is disabled
by configuration option "disable_multithreading".
- Makes `repo::RepoSack` ctors and `repo::Repo::fetch_metadata` method private.
- Unit tests: Use `RepoSack::update_and_load_repos` method instead of `repo::Repo::fetch_metadata` and `repo::Repo::load` 
- Unit tests: Fix: Use "base.get_repo_sack" in all places

Option "disable_multithreading", `repo::RepoSack` ctors and `repo::Repo::fetch_metadata` method private, fix/adjust unit tests

---

test/dnf5daemon-server/CMakeLists.txt
test/libdnf/CMakeLists.txt
test/perl5/CMakeLists.txt
test/python3/libdnf5/CMakeLists.txt
test/ruby/CMakeLists.txt
test/tutorial/CMakeLists.txt

It's because of librpm. Testing CLI utilities can run in parallel.
Fixes an issue that often appeared in unit tests in the COPR build when using the multi-threaded version of the `RepoSack::update_and_load_repos`:
```
TRACE [rpm] entering chroot /tmp/libdnf5_unittest.wkCbFF/installroot/
ERROR [rpm] Unable to change root directory: Operation not permitted
```

Disable parallel running of some unit tests

---

dnf5/main.cpp
doc/misc/installroot.7.rst
include/libdnf/common/sack/sack.hpp
include/libdnf/conf/config_main.hpp
include/libdnf/conf/option.hpp
libdnf/base/base.cpp
libdnf/conf/config_main.cpp
libdnf/conf/vars.cpp

Loads dnf.conf and reposdir from the installroot, unless --use_root_config is passed. Resolves https://github.com/rpm-software-management/dnf5/issues/257 and https://github.com/rpm-software-management/dnf5/issues/248.
This behavior is different from the current behavior of DNF4. When given an installroot, DNF4 will look for a config file and reposdir in the installroot, but if they are not present it will fall back to the default config file and/or reposdir. In this PR we only consider the config file and reposdir in the installroot, regardless of whether the files are there.
When `--use_root_config` is passed, the setting of installroot will not affect the config file path or reposdir.
The reposdir taken from the installroot is given priority greater than that specified in dnf.conf, but …

Load config and reposdir from installroot

---

libdnf/repo/solv_repo.cpp

There was a bug when creating a cache solver file for `comps` repos, an incorrect repo id was passed to `libsolv`. It was not always reproducible as it depends on the set of metadata being loaded.
Closes #341.

solv_repo: Fix creating solver cache for comps (RhBug:2173929)

---

libdnf/base/goal.cpp

This commit fixes a problem where group packages were not being removed along with their respective groups. The issue was caused by the algorithm for determining whether another installed package requires the group package. Previously, it took into account all packages that were installed, regardless of whether they were part of any group being removed.
To address the issue, the algorithm now only takes into account packages that are not part of any group currently being removed. For example, if there are two groups installed on the system:
Grp1 with packages
Pkg1 which requires Dep1
Grp2 with packages
Dep1
The new algorithm will correctly remove both Pkg1 and Dep1 packages when both Grp1 and Grp2 are being removed.
This situation can even occur with only one group being removed - in case …

goal: Fix group packages removal (RhBug:2173927)

---

bindings/libdnf5/logger.i
dnf5/main.cpp
include/libdnf/logger/factory.hpp
libdnf/logger/factory.cpp
test/libdnf/logger/test_file_logger.cpp
test/libdnf/logger/test_file_logger.hpp
test/python3/libdnf5/logger/test_file_logger.py

Create helper method for easily creating a file logger based on configured file path. The logic was separated from the `main` to its own file in order to be usable for API users.
Also added bindings for `GlobalLogger` class to setup libraries logging in API scripts.

logger: Add support for logging in API scripts

---

include/libdnf/base/goal_elements.hpp
include/libdnf/rpm/package_query.hpp
libdnf/rpm/package_query.cpp

It will enhance UX when usel want to install package according to binary name without additional search steps.
It will allow to install open-ssh using `dnf5 install ssh`.
Resolves: https://github.com/rpm-software-management/dnf5/issues/338

Add capability to find binaries to resolve_spec

---

dnf5daemon-client/context.cpp
dnf5daemon-client/context.hpp
dnf5daemon-server/session.cpp

There are paths in dbus workflows that will cause system repo to be
loaded twice resulting in assertion error:
```
libdnf/./solv/pool.hpp:228: void libdnf::solv::Pool::swap_considered_map(libdnf::solv::SolvMap&): Assertion 'other_considered_map.allocated_size() == 0 || other_considered_map.allocated_size() >= get_nsolvables()' failed: The considered map is smaller than the number of solvables in the pool
```
Resolves: https://github.com/rpm-software-management/dnf5/issues/229

dnfdaemon: Fix double loading of system repo

---

doc/commands/download.8.rst

Just small fix in man pages following up the comment from DNF5 Fedora Test Days.

man: Add info about download command destination

---

dnf5.spec
libdnf/CMakeLists.txt

Installing a package on a system with sqlite-3.34.1 failed with:
Running transaction
SQL statement compilation failed: "
INSERT INTO
"pkg_name" (
"name"
)
VALUES
(?)
ON CONFLICT DO NOTHING
RETURNING "id"
": (1) - SQL logic error
The cause is that libdnf5 uses "RETURNING" clause in sqlite queries. A support for this clause was added in sqlite-3.35.0. (Figured out experimentally and by reading sqlite sources. Sqlite news file only mentions "adds a number of new language features".)
This patch constrains the minial sqlite version to 3.35.0.

Set a minimal sqlite version

---

dnf5.spec

Introduced with commit bcc12c612379bbba665768bc2e3e3c3c1f5e55f5 (Set a minimal sqlite version).

Fix a typo in sqlite Requires in dnf5.spec

---

dnf5/commands/list/list.cpp
dnf5/commands/list/list.hpp
dnf5/commands/search/search.cpp
dnf5/commands/search/search.hpp
dnf5/commands/search/search_processor.cpp
dnf5/commands/search/search_processor.hpp
include/libdnf/conf/config_main.hpp
libdnf/conf/config_main.cpp

- the option is not documented even for dnf4
- the name is kind of cryptic
For commands that use it (list, info, search), the functionality is replaced by --showduplicates command line option.

Remove showdupesfromrepos config option

---

dnf5/commands/search/search.cpp

Fix search command to work after previous changes related to `show_duplicates` option.

search: Fix typo from the previous commit

---

include/libdnf/rpm/package_query.hpp
libdnf/base/goal.cpp
libdnf/rpm/package_query.cpp

In situation where a package exists in multiple versions and some older version is being obsoleted, any of obsoleters was considered a valid solution.
The result could be really misleading. For example let's have this package set:
systemd-udev-1.0
systemd-udev-2.0
Obsoletes: systemd-udev < 2
systemd-boot-unsigned-2.0
Obsoletes: systemd-udev < 2
In this case `dnf install systemd-udev` may lead to installation of systemd-boot-unsigned which is probably not what the user expected. The reason is the split in the upgrade-path created by obsolete and both branches - systemd-udev-2.0 and systemd-boot-unsigned-2.0 are considered valid.
With this patch install command takes into account only obsoleters of the best version of the package so the `dnf install systemd-udev` results in correct …

goal: Better handling of obsoleted pkg installation

---

libdnf/rpm/solv/goal_private.cpp

The detected running kernel was not used in GoalPrivate::limit_installonly_packages() call.
Test: https://github.com/rpm-software-management/ci-dnf-stack/pull/1241

GoalPrivate: Fix protecting the running kernel

---

libdnf/base/transaction_impl.hpp

Fix missing `groups` object copy in constructor.
Closes #384.

transaction: Fix impl constructor

---

bindings/libdnf5/advisory.i
bindings/libdnf5/base.i
bindings/libdnf5/comps.i
bindings/libdnf5/conf.i
bindings/libdnf5/logger.i
bindings/libdnf5/repo.i
bindings/libdnf5/rpm.i
bindings/libdnf5/transaction.i
include/libdnf/conf/option.hpp
libdnf/base/goal.cpp
libdnf/logger/global_logger.cpp
libdnf/repo/repo.cpp
test/libdnf/conf/test_option.cpp
test/python3/libdnf5/base/test_base.py
test/python3/libdnf5/base/test_goal.py
test/python3/libdnf5/conf/test_option.py
test/python3/libdnf5/logger/test_global_logger.py
test/python3/libdnf5/repo/test_repo.py

Try to use API assertions wherever it makes sense and for bindings translate those to standard SWIG runtime exceptions. All usages should be supported by unit tests.
Note: like I've written in some previous SWIG-related PR, it would be nice to have a better solution translating those exceptions on the level where they are actually thrown. Now all methods in generated bindings have their own try-catch blocks.
Closes #345.

Using API assertions and converting them in SWIG

---

dnf5/context.cpp
dnf5/download_callbacks.cpp
dnf5/download_callbacks.hpp
dnf5/main.cpp
dnf5daemon-server/callbacks.cpp
dnf5daemon-server/callbacks.hpp
dnf5daemon-server/session.cpp
include/libdnf-cli/progressbar/download_progress_bar.hpp
include/libdnf-cli/progressbar/multi_progress_bar.hpp
include/libdnf-cli/progressbar/widgets/widget.hpp
include/libdnf/repo/download_callbacks.hpp
include/libdnf/repo/repo.hpp
include/libdnf/repo/repo_callbacks.hpp
libdnf-cli/progressbar/multi_progress_bar.cpp
libdnf/repo/download_callbacks.cpp
libdnf/repo/file_downloader.cpp
libdnf/repo/package_downloader.cpp
libdnf/repo/repo.cpp
libdnf/repo/repo_downloader.cpp
libdnf/repo/repo_downloader.hpp
test/libdnf/repo/test_package_downloader.cpp
test/libdnf/repo/test_repo.cpp
test/libdnf/rpm/test_transaction.cpp
test/python3/libdnf5/repo/test_repo.py
test/ruby/libdnf5/repo/test_repo.rb
test/tutorial/transaction/transaction.cpp

Previously, methods from repo::RepoCallbacks were used for repository metadata download.

Use repo::DownloadCallbacks for all downloads

---

dnf5daemon-server/services/goal/goal.cpp
test/dnf5daemon-server/test_goal.py

Client can call `goal.do_transaction()` before the transaction is created by calling `goal.resolve()`.
This patch handles such error by returning dbus error reply instead of dnf5daemon-server segfault.

dnfdaemon: Handle errors when transaction is not created

---

dnf5daemon-client/commands/distro-sync/distro-sync.cpp
dnf5daemon-client/commands/distro-sync/distro-sync.hpp
dnf5daemon-client/commands/downgrade/downgrade.cpp
dnf5daemon-client/commands/downgrade/downgrade.hpp
dnf5daemon-client/commands/install/install.cpp
dnf5daemon-client/commands/install/install.hpp
dnf5daemon-client/commands/reinstall/reinstall.cpp
dnf5daemon-client/commands/reinstall/reinstall.hpp
dnf5daemon-client/commands/remove/remove.cpp
dnf5daemon-client/commands/remove/remove.hpp
dnf5daemon-client/commands/shared_options.cpp
dnf5daemon-client/commands/shared_options.hpp
dnf5daemon-client/commands/upgrade/upgrade.cpp
dnf5daemon-client/commands/upgrade/upgrade.hpp
dnf5daemon-client/exception.cpp
dnf5daemon-client/main.cpp
dnf5daemon-server/services/goal/goal.cpp
dnf5daemon-server/services/rpm/rpm.cpp
test/dnf5daemon-server/support.py
test/dnf5daemon-server/test_install.py

Now it's possible to install a package from local rpm file.

dnfdaemon: Transaction commands can work with rpm files

---

libdnf/repo/repo_sack.cpp

The *.repo file name will be needed to implement the 'dnf5 copr' logic in the future.

RepoSack: remember the repo file path

---

dnf5/context.cpp
dnf5/include/dnf5/context.hpp
dnf5/main.cpp
include/libdnf-cli/output/transaction_table.hpp
include/libdnf-cli/utils/units.hpp
include/libdnf/rpm/package.hpp
libdnf-cli/output/package_info_sections.cpp
libdnf-cli/progressbar/widgets/common.cpp
libdnf-cli/utils/units.cpp
libdnf/rpm/package.cpp
libdnf/utils/on_scope_exit.hpp

Solves issue https://github.com/rpm-software-management/dnf5/issues/342

dnf5: Statistics: total and downloaded pkgs size, installed and freed space

---

include/libdnf/base/base.hpp
libdnf/base/base.cpp
libdnf/repo/repo_sack.cpp

Fixes a bungle in https://github.com/rpm-software-management/dnf5/pull/271; `create_repos_from_config_file` was not reading the config file from the installroot.
Resolves https://github.com/rpm-software-management/dnf5/issues/248

Correctly load repos from installroot config file

---

dnf5/context.cpp
include/libdnf-cli/progressbar/multi_progress_bar.hpp
include/libdnf/base/transaction.hpp
libdnf-cli/progressbar/multi_progress_bar.cpp
libdnf/base/transaction.cpp

- dnf5: Hides total transaction progress bar - It was showing nonsensical information.
- dnf5: Fixes total number of actions (steps) in transaction progress - It shows [x/max], before fix [x/x+1].
Solves: https://bugzilla.redhat.com/show_bug.cgi?id=2180229

dnf5: Transaction progress: Fix total number of actions, hide total transaction progress bar

---

include/libdnf/logger/null_logger.hpp

The type of the argument in the parent method was changed some time ago. But the NullLogger descendant was forgotten.
The bug is not detected until someone uses the header file with NullLogger.

NullLogger::write: Fix type of time argument

---

dnf5/config/usr/share/dnf5/aliases.d/compatibility.conf

"update" is a deprecated alias for the "upgrade". But we will keep it for compatibility.  https://github.com/rpm-software-management/dnf5/issues/156

[dnf5] Add "up" and "update" aliases for "upgrade" command

---

bindings/libdnf5/base.i
bindings/libdnf5/common.i
test/python3/libdnf5/base/test_goal.py

Allow API users to access wrappers for `libdnf::base::LogEvent` class and `get_resolve_logs()` method on the `libdnf::base::Transaction`.
Python API unit tests for the wrappers are included.

swig: Add bindings for LogEvent

---

bindings/libdnf5/common.i
bindings/python3/CMakeLists.txt

Since swig-4.1 (from f38) message warning about memory leak can be
printed when libdnf5 python api is used. It is reproducible with just:
```
import libdnf5.base
def asd():
pass
base = libdnf5.base.Base()
```
But also happens in our ci-dnf-stack python API tests, therefore it is
blocking our switch to f38 as a base for CI: https://github.com/rpm-software-management/ci-dnf-stack/pull/1226
Currenly it happens due to a bug in SWIG therefore we wan't to silent
the message.
Unfortunately this might hide some real problems.

Hide swig/python detected a memory leak message

---

include/libdnf/module/module_sack.hpp
libdnf/module/module_sack.cpp
libdnf/system/state.cpp
libdnf/system/state.hpp
libdnf/utils/dnf4convert/dnf4convert.cpp
test/libdnf/system/test_state.cpp
test/shared/utils.hpp

The reason is that the name was the same as the ModuleState class in libdnf::state and it was confusing especially when both were used next to each other.

modules: Rename ModuleState enum to ModuleStatus

---

dnf5/config/usr/share/dnf5/aliases.d/compatibility.conf

It provides a compatibility with DNF.
Part of:
https://github.com/rpm-software-management/dnf5/issues/137
https://github.com/rpm-software-management/dnf5/issues/149
https://github.com/rpm-software-management/dnf5/issues/148
https://github.com/rpm-software-management/dnf5/issues/142

Add 4 aliases for dnf5 commands

---

dnf5/commands/advisory_shared.hpp
dnf5/commands/repoquery/repoquery.cpp
dnf5/commands/repoquery/repoquery.hpp

- Add `--latest-limit` option
- Unify all descriptions across repoquery and also shared advisory options.

repoquery: add --latest-limit option and unify descriptions

---

libdnf/rpm/package_sack.cpp

Attempt to convert package id to string returns "random" results. Log full nevra of the package instead.

package_sack: Fix running kernel logging

---

bindings/python3/CMakeLists.txt
dnf5.spec

fixes #446 
* ensures that `libdnf5` and `libdnf5_cli` Python bindings include minimal distribution metadata (per https://packaging.python.org/en/latest/specifications/core-metadata/#core-metadata). This makes the presence of the binding and its version visible to standard Python tools like `pip`, and makes it easier for, eg, Ansible users to discover if the bindings are available to the current Python.
Note that `python3-rpm` and `python3-gpg` are already doing something similar (just using the older and largely deprecated `egg-info` metadata instead of `dist-info`).
After build/install with this change:
```
(dnf5) [root@690bb604ca02 build]# pip list
Package     Version
----------- -------
libdnf5     5.0.7
libdnf5_cli 5.0.7
pip         22.2.2
setuptools  62.6.0
```
I've also reserved …

generate dist-info for Python bindings

---

dnf5/commands/download/download.cpp
dnf5/main.cpp

- if the user wants help (--help/-h argument is present) -> print help and only help without errors and the application ends with the return code libdnf::cli::ExitCode::SUCCESS.
- if user doesn't want help (--help/-h argument is not present) and argument parser detects missing/bad argument -> print an error message with a note about '--help' and application exits with return code libdnf::cli::ExitCode::ARGPARSER_ERROR
Solves: https://github.com/rpm-software-management/dnf5/issues/317
Requires modification of CI tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1247

[dnf5] Fix help in case argument parser detect error

---

.clang-format
doc/contributing/coding_style_cpp.rst
doc/contributing/project_layout.rst

- Fix .clang-format: Replace Cpp11 with c++20
- [doc] Coding style: Use C++20
- [doc] project layout: Add dnf5-plugins directory

Small fixes in doc and formating

---

libdnf-cli/progressbar/widgets/progress.cpp

In case the current ticks in the progress bar are not set (default to -1), the `std::string(progress, '=')` might result in throwing std::length_error exception:
terminate called after throwing an instance of 'std::length_error'
what():  basic_string::_M_create
Aborted (core dumped)
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2184271

progressbar: Prevent length_error exception (RhBug:2184271)

---

dnf5/commands/repoquery/repoquery.cpp
dnf5/commands/repoquery/repoquery.hpp
doc/commands/repoquery.8.rst

Part of https://github.com/rpm-software-management/dnf5/issues/122

[dnf5] Support for "--userinstalled" argument in repoquery

---

include/libdnf/base/base.hpp
include/libdnf/repo/repo_sack.hpp
libdnf/comps/group/group.cpp
libdnf/repo/repo.cpp
libdnf/repo/repo_sack.cpp
libdnf/repo/solv_repo.cpp
libdnf/repo/solv_repo.hpp

This is alternative solution to https://github.com/rpm-software-management/dnf5/pull/406
Advantage of this PR is that there is no change in system state, therefore no duplicated information.
Installed group xml is now taken from available repositories, with a fall-back to generating minimal solvable from system state information in case the group is not available in repos.
Fixes: https://github.com/rpm-software-management/dnf5/issues/420

Fix installed groups loading to libsolv - take 2

---

include/libdnf/base/transaction_group.hpp
include/libdnf/comps/group/package.hpp
libdnf/base/goal.cpp
libdnf/base/transaction.cpp
libdnf/comps/group/package.cpp
libdnf/rpm/solv/goal_private.hpp
libdnf/system/state.cpp
libdnf/system/state.hpp
libdnf/utils/dnf4convert/dnf4convert.cpp
test/libdnf/system/test_state.cpp
test/libdnf/system/test_state.hpp
test/shared/utils.hpp

To correctly implement `dnf5 group upgrade` command we need to now which types of packages were installed along with the group.
E.g. in case the group was installed without `optional` packages, upgrade also should not install new optional packages and vice versa - if the group was installed with optionals, then any new optional package gets also installed.

system state: Add package_types to the GroupState

---

clang-format

The GNU grep installation on Fedora 38 throws this warning: egrep: warning: egrep is obsolescent; using grep -E

clang-format: use grep -E instead of egrep

---

dnf5-plugins/builddep_plugin/builddep.cpp
dnf5-plugins/builddep_plugin/builddep.hpp

This PR closes #461, by adding support for the --allowerasing option for the builddep command.

[dnf5-plugins] --allowerasing support for builddep command.

---

dnf5-plugins/builddep_plugin/builddep.cpp
dnf5/commands/download/download.cpp
dnf5/commands/download/download.hpp
doc/commands/download.8.rst

It fixes the issue when `dnf download pkg-1 pkg-2` where the previous implementation will download only pkg-2.

Filter latest per argument for download command

---

include/libdnf/base/base.hpp
libdnf/module/module_db.cpp
libdnf/module/module_db.hpp
libdnf/module/module_sack.cpp
libdnf/module/module_sack_impl.hpp
libdnf/system/state.cpp
libdnf/system/state.hpp
test/libdnf/module/test_module.cpp
test/libdnf/module/test_module.hpp

Contains also the same commit as in https://github.com/rpm-software-management/dnf5/pull/387 , because it requires it.

modules: Add ModuleDB to store the runtime states of all modules

---

dnf5/commands/group/arguments.hpp
dnf5/commands/group/group_install.cpp
dnf5/commands/group/group_install.hpp
dnf5/commands/group/group_remove.cpp
dnf5/commands/group/group_remove.hpp
doc/changes.rst
doc/commands/group.8.rst
include/libdnf/base/goal_elements.hpp
libdnf/base/goal.cpp

This is replacement of "dnf group mark install/remove" commands. I certainly can implement those as standalone commands, but it would introduce a lot of code duplicity. `dnf group mark install` is basically the same command (including all command line switches) as `dnf group install`. The only difference is that the former needs to set one GoalJobSettings flag more (`settings.group_no_packages = true`). This will ensure, that only groups are going to be part of the transaction and no packages are changed (and similarly the `dnf group mark remove`).
If needed, I think a compatible alias can be introduced later - `dnf group mark install` -> `dnf group install --no-packages`.
For https://github.com/rpm-software-management/dnf5/issues/138

dnf5: Replacement of old "dnf group mark install/remove" commands

---

bindings/libdnf5/conf.i
include/libdnf/conf/vars.hpp
libdnf/conf/vars.cpp

There is a use case where they need to detect releasever before setting cachedir and calling base.setup()
Resolves: https://github.com/rpm-software-management/dnf5/issues/281

Add detect_release to public API

---

.github/workflows/ci.yml

~~This pr is currently opened against not-the-main branch to test the merge-queue feature which has to be enabled in GH settings.~~
Open against master now.
By enabling the feature, all the checks will run once more before the pr gets automatically merged by GitHub.
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request-with-a-merge-queue

Add merge group to workflows

---

libdnf/base/transaction.cpp
libdnf/rpm/transaction.hpp

Iterator needs to be moved using the next function after the initialization in order to work properly. Also simplified iterator usage in order to use the range-based for loop.
CI tests PR: https://github.com/rpm-software-management/ci-dnf-stack/pull/1275.
Closes https://github.com/rpm-software-management/dnf5/issues/515.

transaction: Fix iterator over RPM problems

---

dnf5daemon-client/callbacks.cpp
dnf5daemon-client/callbacks.hpp
dnf5daemon-client/commands/command.cpp
dnf5daemon-client/context.cpp
dnf5daemon-client/context.hpp
dnf5daemon-server/callbacks.cpp
dnf5daemon-server/callbacks.hpp
dnf5daemon-server/dbus.hpp
dnf5daemon-server/dbus/interfaces/org.rpm.dnf.v0.Base.xml
dnf5daemon-server/dbus/interfaces/org.rpm.dnf.v0.rpm.Repo.xml
dnf5daemon-server/services/base/base.cpp
dnf5daemon-server/services/goal/goal.cpp
dnf5daemon-server/services/repo/repo.cpp
dnf5daemon-server/session.cpp

This patch adapts dnfdaemon callbacks to unified repo::DownloadCallbacks introduced in commit d24cad69.
The new implementation is much simpler and resolves several segfaults in the dnf5daemon-server.
- specialized RepoCB and PackageDownloadCB are replaced with shared DownloadCB
- since repository and package downloads now share the same callbacks, signals are moved from REPO to BASE interface
- added new "download_add_new" signal for the new download callback "add_new_download"
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2184276

dnfdaemon: Fix download callbacks

---

dnf5/commands/download/download.cpp
dnf5/commands/download/download.hpp
dnf5/include/dnf5/shared_options.hpp
dnf5/shared_options.cpp

It unify approach how to use destdir variable inside dnf5. Using only configuration value is more transparent.

Connect destdir cmd option with configuration

---

.github/workflows/prepare-release.yml

dnf5 uses global macros at the beginning of dnf5.spec that need to be updated with version numbers.
VERSION.cmake needs also to be updated

update release action with custom dnf5 scripts

---

dnf5/commands/group/arguments.hpp
dnf5/commands/group/group_info.cpp
dnf5/commands/group/group_info.hpp
dnf5/commands/group/group_list.cpp
dnf5/commands/group/group_list.hpp
doc/changes.rst
doc/commands/group.8.rst
include/libdnf/comps/group/query.hpp
libdnf/comps/group/query.cpp
test/libdnf/comps/test_group_query.cpp
test/libdnf/comps/test_group_query.hpp

The option is moved from `repoquery` to group info/list commands.
It fits much better into the group sub-commands.

group info/list: add `--contains-pkgs` option

---

test/libdnf/base/test_transaction.cpp
test/python3/libdnf5/base/test_transaction.py
test/python3/libdnf5/base_test_case.py

Following up to the fix from https://github.com/rpm-software-management/dnf5/pull/95, I've also set up a `x86_64` arch for Python API tests as we use these packages there.
Also some small refactoring and unification in unit tests included.

Fix nightly builds on different archs than x86_64

---

libdnf-cli/libdnf-cli.pc.in
libdnf/libdnf.pc.in

On Fedora 38, /usr/lib64/pkgconfig/libdnf.pc has a "Version:" field with no value.  I'm guessing that this is an indication that PROGRAM_VERSION is undefined and that PROJECT_VERSION is the appropriate replacement.
(I have not tested the result of this PR.  Please treat is as a bug report and a suggestion.)

Use PROJECT_VERSION in pc.in files.

---

include/libdnf/comps/environment/query.hpp
libdnf/comps/environment/query.cpp

Sometimes we need to build a resulting query as a union of other queries. We might need to start with an empty one.

comps: Possibility to create an empty EnvironmentQuery

---

CHANGELOG.md
dnf5/commands/download/download.cpp
dnf5/context.cpp
dnf5/include/dnf5/context.hpp
dnf5daemon-server/services/goal/goal.cpp
include/libdnf/base/transaction.hpp
include/libdnf/repo/package_downloader.hpp
libdnf/base/transaction.cpp
libdnf/repo/package_downloader.cpp
libdnf/repo/temp_files_memory.cpp
libdnf/repo/temp_files_memory.hpp
test/libdnf/repo/test_package_downloader.cpp
test/libdnf/repo/test_package_downloader.hpp
test/libdnf/repo/test_temp_files_memory.cpp
test/libdnf/repo/test_temp_files_memory.hpp
test/libdnf/rpm/test_transaction.cpp
test/libdnf/rpm/test_transaction.hpp
test/python3/libdnf5/repo/test_package_downloader.py
test/ruby/libdnf5/repo/test_package_downloader.rb

This is a follow-up to previous "simple" solution from https://github.com/rpm-software-management/dnf5/pull/377.
Current behavior should be more robust compared to the original PR. Now all package files that were downloaded when user requested the `keepcache=False` mode are tracked in the special TOML file and they are removed after the next successful transaction run.
Download command has an exception with overridden behavior to always keep downloaded packages on the system as this is matching the existing DNF behavior.
The list of the packages is created before the actual download begins, so then if any error is encountered and any data has been already downloaded, they are still removed after the next transaction.
Additionally, when user runs the `dnf5 clean all` command, all metadata …

Implement keepcache functionality (RhBug:2176384)

---

doc/changes.rst
libdnf/base/goal.cpp
test/libdnf/base/test_goal.cpp

After the change, upgrade, downgrade, distrosync will not ignore broken argument.

Make strict behavior for several command

---

dnf5/commands/downgrade/downgrade.cpp
dnf5/commands/group/group_install.cpp
dnf5/commands/install/install.cpp
dnf5/commands/reinstall/reinstall.cpp
dnf5/commands/upgrade/upgrade.cpp
dnf5/context.cpp
dnf5/include/dnf5/shared_options.hpp
dnf5/main.cpp
dnf5/shared_options.cpp

Resolve: https://github.com/rpm-software-management/dnf5/issues/537

Add support for downloadonly in DNF5

---

dnf5/context.cpp

dnf5: fix unpack_error typo (errro -> error)

---

dnf5.spec

It fixes an issue of not installed dnf.conf for Fedora < 39.

Exclude dnf.conf when not installed

---

.packit.yaml

Without this change, the version number will be replaced explicitly.
See here.
https://src.fedoraproject.org/rpms/dnf5/pull-request/13
This is not a big deal, but to keep all the specfles in sync it is required.

packit: keep rpm macros in specfile

---

CHANGELOG.md
dnf5-plugins/copr_plugin/download_file.cpp
dnf5/commands/download/download.cpp
dnf5daemon-server/services/goal/goal.cpp
include/libdnf/repo/file_downloader.hpp
include/libdnf/repo/package_downloader.hpp
libdnf/base/transaction.cpp
libdnf/repo/file_downloader.cpp
libdnf/repo/package_downloader.cpp
libdnf/repo/repo_sack.cpp
libdnf/rpm/rpm_signature.cpp
test/libdnf/repo/test_package_downloader.cpp
test/python3/libdnf5/repo/test_package_downloader.py
test/ruby/libdnf5/repo/test_package_downloader.rb

To make the API and code usages more explicit.
Closes #528.
CI tests fix: https://github.com/rpm-software-management/ci-dnf-stack/pull/1297.

downloaders: Pass fail_fast and resume by setters

---

dnf5/main.cpp
dnf5daemon-client/commands/repoquery/repoquery.cpp
dnf5daemon-client/wrappers/dbus_package_wrapper.hpp
dnf5daemon-server/package.cpp
dnf5daemon-server/package.hpp
dnf5daemon-server/services/goal/goal.cpp
dnf5daemon-server/services/repo/repo.cpp
doc/changes.rst
include/libdnf-cli/output/repoquery.hpp
include/libdnf/rpm/package.hpp
libdnf-cli/output/package_info_sections.cpp
libdnf-cli/output/repoqueryformat.cpp
libdnf/repo/package_downloader.cpp
libdnf/rpm/package.cpp
test/dnf5daemon-server/support.py
test/libdnf/rpm/test_package.cpp
test/libdnf/rpm/test_package.hpp

Since we have `rpm::Package::get_install_size()` it seems clearer to have `rpm::Package::get_download_size()` to complement it.
Also
- libsolv is using SOLVABLE_DOWNLOADSIZE
- dnf4 used Package.downloadsize
- queryformat uses `downloadsize` tag
Follow up for: https://github.com/rpm-software-management/dnf5/pull/508#discussion_r1203741313

rpm::Package: rename get_package_size() to get_download_size()

---

dnf5/config/usr/share/dnf5/aliases.d/compatibility.conf

No other 2-character aliases are completed.  To be consistent, don't complete the `ls` alias either.
In #568, it was noted that completion is not generally enabled for these shortcut aliases.  That seems like a good reason to disable completion of the `ls` alias as well.

aliases: don't complete ls alias

---

dnf5/commands/repoquery/repoquery.cpp
dnf5/commands/repoquery/repoquery.hpp
doc/changes.rst

Add several repoquery options.

Add a bunch of repoquery options

---

dnf5/commands/check-upgrade/check-upgrade.cpp
dnf5/context.cpp
include/libdnf-cli/exception.hpp
libdnf-cli/exception.cpp

When an error occurred during the RPM transaction, dnf command should return non-zero exit code.
CI tests fix: https://github.com/rpm-software-management/ci-dnf-stack/pull/1305.
Closes #525.

cli: Return error exit code on RPM transaction failure

---

bindings/libdnf5/comps.i
test/python3/libdnf5/comps/test_group.py

Add wrapper for a vector of `libdnf::comps::Package`. Unit test is included.
Closes #590.

swig: Fix group packages getter

---

libdnf/repo/repo_sack.cpp
libdnf/repo/solv_repo.cpp
libdnf/repo/solv_repo.hpp
libdnf/system/state.cpp
libdnf/system/state.hpp

Uses similar approach we already have for groups.
System repo environments are loaded from xml files saved in the system state. In case the xml file with environment definition is missing (e.g. after upgrade from dnf4), a new one is created from available environmental group of the same id (with fallback to create a simple solvable based only on system state data).

state: Load environmental groups to system repo

---

.github/workflows/ci.yml

This is needed because since rpm-software-management/dnf#1937 new dnf-data (in dnf-nightly) requires `/etc/dnf/dnf.conf` but in rawhide and dnf-nightly nothing provides that. It is provided by new libdnf5 currently only present in dnf5-unstable.
It should make the CI Copr builds pass on rawhide.

Add dnf5-unstable copr repo to dnf5 CI copr builds

---

dnf5.spec
libdnf/CMakeLists.txt
libdnf/libdnf5.pc.in

It also allow parallel installation of libdnf5-devel and libdnf-devel.

Modify libdnf5-devel to generate pkgconf(libdnf5)

---

doc/changes.rst

The `*` glob character is used now to disable all configuration file excludes instead of the `all` value as before in DNF.

Document change in disable_excludes option

---

test/python3/libdnf5/tutorial/session/create_base.py
test/python3/libdnf5/tutorial/test_tutorial.py

Without setting cachedir to a temporary directory, when testing the python3 bindings tutorial, the user cache directory is used and the test repository rpm-repo1 is cached there. When dnf5 is then built second time, the newly created repository metadata differ from the cached ones and the tests fail with:
terminate called after throwing an instance of 'Swig::DirectorMethodException'
what():  SWIG director method error. Error detected when calling 'DownloadCallbacks.mirror_failure'
Resolves: https://github.com/rpm-software-management/dnf5/issues/572

test: Add cachedir to python3 bindings tutorial

---

dnf5/commands/distro-sync/distro-sync.cpp
dnf5/commands/download/download.cpp
dnf5/commands/group/group.cpp
dnf5/commands/install/install.cpp
dnf5/commands/list/list.cpp
dnf5/commands/makecache/makecache.cpp
dnf5/commands/repo/repo.cpp
dnf5/commands/repoquery/repoquery.cpp
dnf5/commands/search/search.cpp
dnf5/commands/swap/swap.cpp
dnf5/include/dnf5/shared_options.hpp
dnf5/shared_options.cpp
doc/commands/distro-sync.8.rst
doc/commands/download.8.rst
doc/commands/group.8.rst
doc/commands/install.8.rst
doc/commands/makecache.8.rst
doc/commands/repo.8.rst
doc/commands/repoquery.8.rst
doc/commands/search.8.rst
doc/commands/swap.8.rst
doc/misc/forcearch.7.rst
doc/misc/index.rst
libdnf5/rpm/transaction.cpp

Added --forcearch to:
- `dnf5 distro-sync`
- `dnf5 download`
- `dnf5 group`
- `dnf5 install`
- `dnf5 makecache`
- `dnf5 repo`
- `dnf5 repoquery`
- `dnf5 search`
- `dnf5 swap`
The --forcearch=<arch> argument overrides the "arch" and "basearch" substitution vars and tells librpm to allow installations of packages not matching the architecture of the host system. It enables several use cases, including:
- Install packages to be used with something like qemu-user-static
- Search repos for packages built for a different architecture
- Download packages to be installed on another system
Resolves https://github.com/rpm-software-management/dnf5/issues/112.
A good Fedora package to test this with is `Random123-doc` since it has a version for `x86_64` and `aarch64` (though it probably should be …

Support --forcearch for many commands

---

bindings/libdnf5/conf.i
test/python3/libdnf5/conf/test_option.py

When using Python bindings, return a `None` value when accessing values of unset configuration options.
The solution is simplified to do so if any runtime error occurred within the `get_value()` option call.
API unit tests included.
Closes #594.

swig: Return None for unset options in Python

---

dnf5-plugins/changelog_plugin/changelog.cpp
dnf5/commands/check-upgrade/check-upgrade.cpp
dnf5/commands/repoquery/repoquery.cpp
dnf5/commands/repoquery/repoquery.hpp
doc/changes.rst
include/libdnf5-cli/output/changelogs.hpp
libdnf5-cli/output/changelogs.cpp

repoquery: add --srpm and --sourcerpm

---

dnf5-plugins/changelog_plugin/CMakeLists.txt
dnf5-plugins/changelog_plugin/changelog.cpp

Use the `libdnf::cli::ArgumentParserError` exception instead of the generic runtime error for invalid date format with `--since` option. This way it is processed in `main` instead of aborting and dumping the core.
Also initialize the `time_m` struct with default values, otherwise it results in returning random values.
Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1322.
Closes: #627.

changelog: Fix handling of the --since option

---

dnf5/context.cpp
dnf5/include/dnf5/context.hpp
dnf5daemon-client/callbacks.cpp
dnf5daemon-server/callbacks.cpp
dnf5daemon-server/callbacks.hpp
include/libdnf5/base/transaction.hpp
include/libdnf5/repo/repo.hpp
include/libdnf5/repo/repo_callbacks.hpp
include/libdnf5/rpm/rpm_signature.hpp
libdnf5/base/transaction.cpp
libdnf5/base/transaction_impl.hpp
libdnf5/repo/repo.cpp
libdnf5/repo/repo_pgp.cpp
libdnf5/repo/repo_pgp.hpp
libdnf5/rpm/rpm_signature.cpp
test/libdnf5/repo/test_repo.cpp

Currently signatures verification requires to manually call `transaction.check_gpg_signatures()` API.
This PR removes the API and changes the workflow so that the signature verification is done automatically during the transaction run.
Resolves: https://github.com/rpm-software-management/dnf5/issues/556
Resolves: https://github.com/rpm-software-management/dnf5/issues/574
Resolves: https://github.com/rpm-software-management/dnf5/issues/557
Tests adujstments: https://github.com/rpm-software-management/ci-dnf-stack/pull/1314

Verify transaction PGP signatures automatically

---

doc/changes.rst
doc/commands/remove.8.rst

Improve the documentation around the dropped `--noautoremove` option.

remove: Document removal of --noautoremove option

---

doc/changes.rst
libdnf5/conf/config_main.cpp
test/data/cmdline-rpms/cmdline-1.2-3.spec
test/data/repos-rpm/rpm-repo1/one-1-1.spec
test/data/repos-rpm/rpm-repo1/one-2-1.spec
test/data/repos-rpm/rpm-repo2/two-2-2.spec
test/data/repos-solv/solv-distrosync.repo

Requires: https://github.com/rpm-software-management/dnf5/pull/621

Change of default for allow_vendor_change

---

libdnf5/base/log_event.cpp
libdnf5/po/libdnf5.pot

downgrade: Adjust stderr message when the lowest available version is already installed.
NOTE: upstream tests dnf/downgrade.feature and  dnf/shell-downgrade.feature has to be updated accordingly.

downgrade: Adjust stderr message

---

test/python3/libdnf5_cli/test_placeholder.py

The tests started failing after updating to Python 3.12 because of this change in unittest:
https://discuss.python.org/t/unittest-fail-if-zero-tests-were-discovered/21498 If no tests are discovered, unittest now fails with a nonzero exit code.
This adds a "placeholder" test that does nothing, just to get unittest to succeed.

Add placeholder test to test/python3/libdnf5_cli

---

.packit.yaml

The `fix-spec-file action`, it isn't called during `propose_downstream`.
More info on this change here https://src.fedoraproject.org/rpms/dnf5/pull-request/16

packit: remove fix-spec-file action

---

dnf5/main.cpp
doc/dnf5.8.rst
include/libdnf5/conf/config_main.hpp
include/libdnf5/repo/repo_errors.hpp
libdnf5/conf/config_main.cpp
libdnf5/repo/file_downloader.cpp
libdnf5/repo/package_downloader.cpp
libdnf5/repo/repo.cpp
test/python3/libdnf5/conf/test_option.py

- Add `cacheonly` configuration option with: `all`, `metadata` and `none` values (`none` is default)
- Add `--cacheonly` parameter which sets the `cacheonly=all`
- Add `--refresh` parameter to expire all repo metadata and so forcing downloading fresh data from remotes
When `metadata` or `all` is set, repositories' `sync_strategy` is set to `ONLY_CACHE`.
When `all` is set, packages to be downloaded are checked and any attempt to download remote package results in an error. Also downloading any remote file results in an error.
Follow-ups:
- Better documentation: https://github.com/rpm-software-management/dnf5/issues/668
Other things to discuss:
- Inform user about `cacheonly` activated **before** confirming the transaction?
- Combination with the `clean` command?
- Read-only access to the …

Implementation of cacheonly functionality

---

include/libdnf5/repo/repo.hpp
libdnf5/repo/repo.cpp

The function `Repo::fetch_metadata()` is unused and its logic is contained within the `RepoSack::update_and_load_repos()`, therefore it could be removed.

repo: Drop unused fetch_metadata function

---

dnf5/commands/check-upgrade/check-upgrade.cpp
dnf5/commands/install/install.cpp
dnf5/commands/repoquery/repoquery.cpp
dnf5/commands/upgrade/upgrade.cpp
dnf5/context.cpp
dnf5/include/dnf5/context.hpp

Updateinfo and comps metadata were always downloaded and loaded by default. This is not necessary because each command configures the `optional_metadata_types` to download/load only what it requires.
Also there was a bug in detection whether updateinfo metadata are needed.
For: https://bugzilla.redhat.com/show_bug.cgi?id=2214520
In my testing when loading updateinfo metadata memory requirements spike at ~623 MiB but without them its only ~132 MiB (on F38 with clean cache). I will further investigate why the updateinfo metadata use so much during libsolv loading, it seems unexpected to me given their size.

Do not download updateinfo and comps metadata by default

---

include/libdnf5/rpm/nevra.hpp
test/libdnf5/rpm/test_nevra.cpp

The evrcmp template function can work also with Nevra objects which can
have empty epoch. Comparing such object to another object with epoch=0
produces incorrect results.

nevra: Fix evrcpm to work with empty epoch

---

libdnf5/logger/logger.cpp
libdnf5/rpm/transaction.hpp

As implicit conversions for enums were deprecated in fmt 10.0.0, we need to explicitly do the conversion for custom enums. See: https://github.com/fmtlib/fmt/blob/10.0.0/ChangeLog.rst?plain=1#L68
Also, using fmt 10, `time_point<system_clock>` contains seconds represented as a floating-point number. In order to drop the decimal places, we need to explicitly do the conversion. This is also conformant with the currently used fmt-9.1 docs: https://fmt.dev/9.1.0/syntax.html#chrono-format-specifications.
Bugzilla ticket: https://bugzilla.redhat.com/show_bug.cgi?id=2218180.
Closes #675.

Fix building with upcoming fmt-10 library

---

dnf5-plugins/changelog_plugin/changelog.cpp
include/libdnf5-cli/output/changelogs.hpp
libdnf5-cli/output/changelogs.cpp

The variable `count` in `print_changelogs` used to be `int32_t`, but was changed to `int64_t`. Because of that, the build on i686 arch fails with:
```
error: conversion from 'int64_t' {aka 'long long int'} to
'__gnu_cxx::__normal_iterator<libdnf5::rpm::Changelog*,
std::vector<libdnf5::rpm::Changelog> >::difference_type' {aka 'int'} may
change value [-Werror=conversion]
```
---
The issue blocks build on Fedora rawhide: https://koji.fedoraproject.org/koji/taskinfo?taskID=102735120

changelogs: Fix `count` variable type

---

doc/dnf5.8.rst

Add info about `dnf5-plugins` package into the main man page.
Related ticket: https://bugzilla.redhat.com/show_bug.cgi?id=2217933.

man: Add a note about dnf5-plugins package

---

dnf5/commands/advisory/advisory_info.cpp
dnf5/commands/advisory/advisory_list.cpp
dnf5/commands/advisory/advisory_subcommand.cpp
dnf5/commands/advisory/advisory_subcommand.hpp
dnf5/commands/advisory/advisory_summary.cpp

Closes: https://github.com/rpm-software-management/dnf5/issues/628
Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1333

advisory: add running kernel before pkg_specs filtering

---

test/python3/libdnf5/tutorial/session/create_base.py
test/tutorial/session/create_base.cpp

Otherwise we load the host system config file during execution in tests which might be broken or invalid resulting in failing tests (build).
All unittests already use their own installroot we just need to set it for the tutorials code as well.
Closes: https://github.com/rpm-software-management/dnf5/issues/588

tutorials: set installroot before loading config file

---

dnf5/config/usr/share/dnf5/aliases.d/compatibility.conf

For: https://github.com/rpm-software-management/dnf5/issues/696
In order to match rpm options again add `-l` and `--list`.

repoquery: add `-l`/`--list` alias for `--files` for rpm compat

---

libdnf5-plugins/actions/actions.cpp

I plan to extend functionality of actions plugin in the future. I want to add a new configuration item. Changing the configuration format later - when it will be documented and used is not good. So now I'm adding one "reserved" item.
Old format:
callback_name:package_filter:direction:command
New format:
callback_name:package_filter:direction:reserved:command
Requires adjustment of ci tests https://github.com/rpm-software-management/ci-dnf-stack/pull/1335

plugin_actions: Extend line in actions config file by "reserved" item

---

dnf5/commands/history/history_info.cpp

Otherwise the output was empty which is not very user friendly.
Closes: https://github.com/rpm-software-management/dnf5/issues/704

history: info: when no tran id specified use last transaction

---

CMakeLists.txt
libdnf5/rpm/solv/goal_private.cpp

This optionally enables the urpm-style solution reordering required to ensure the proper subset of locale and kernel packages were being installed.
This was present in the older DNF stack and was ported over again as it is still needed.
Reference: https://bugs.mageia.org/show_bug.cgi?id=18315

Re-add build option to enable urpmreorder solver flag

---

dnf5.spec
dnf5/main.cpp
include/libdnf5-cli/argument_parser.hpp
libdnf5-cli/argument_parser.cpp

This adds `Provide`s for `dnf5-command(<command-name>)` for all the commands in `dnf5`, and all the commands provided by `dnf5-plugins`.
Also adds a hint like we had for DNF 4, so when trying to run a missing command:
```
$ dnf foo
Unknown argument "foo" for command "dnf5". Add "--help" for more information about the arguments.
It could be a command provided by a plugin, try: dnf install dnf5-command(foo)
```
Resolves https://github.com/rpm-software-management/dnf5/issues/566

Add provides for dnf5-command(<command-name>)

---

include/libdnf5/advisory/advisory_package.hpp
libdnf5/advisory/advisory_package.cpp
libdnf5/advisory/advisory_package_private.hpp

Adds missing methods get_epoch() and get_release().
This way the AdvisoryPackage object's nevra can be compared with
another AdvisoryPackage (or Nevra, or rpm::Package).

advisory: Add missing methods to AdvisoryPackage

---

libdnf5/rpm/transaction.cpp

To correctly filter out the
"package kernel-x (which is newer than kernel-y) is already installed"
RPM transaction problem, we need to determine whether a downgrade
operation is present in the transaction.
The current implementation relies on the presence of a "downgrade"
operation in the solver results. However, for install-only packages,
there is no "downgrade" operation; only an "install" operation.
This patch introduces detection to identify if an install-only package
of an older version is present in the transaction. It then sets ignored
problems in the RPM transaction accordingly.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2221308
Resolves: https://github.com/rpm-software-management/dnf5/issues/720
Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1337

rpm::Transaction: Enable installonly pkg downgrade

---

dnf5/commands/advisory/advisory_info.cpp
dnf5/commands/advisory/advisory_info.hpp
dnf5/commands/advisory/advisory_list.cpp
dnf5/commands/advisory/advisory_list.hpp
dnf5/commands/advisory/advisory_subcommand.cpp
dnf5/commands/advisory/advisory_subcommand.hpp
dnf5/commands/advisory/advisory_summary.cpp
dnf5/commands/advisory/advisory_summary.hpp

The main problem was that --contains-pkgs values for default
(--available) behavior need to be applied after running kernel packages are
injected to packages query.
Unfortunately the problem was not caught, because the test for printing
advisories for the running kernel was also incorrect.
Fix for the test: https://github.com/rpm-software-management/ci-dnf-stack/pull/1339

dnf5: Fix printing advisories for the running kernel

---

dnf5-plugins/copr_plugin/copr_repo.cpp

copr: typo avaiable => available

---

doc/changes.rst

It's confusing and does not save that many keystrokes.
With this the https://github.com/rpm-software-management/dnf5/issues/141 is resolved.

Document dropped "if" alias of info command

---

dnf5/commands/remove/remove.cpp
dnf5/config/usr/share/dnf5/aliases.d/compatibility.conf

It is an option to prevent removal of unused dependencies.
The option was requested here: https://pagure.io/fesco/issue/3039
Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1342

Add --no-autoremove option for remove command plus alias

---

doc/changes.rst

Closes: https://github.com/rpm-software-management/dnf5/issues/151

Document replace of `-v` option by `repoinfo` command

---

doc/commands/repoquery.8.rst

It also fixes a typo in userinstalled option description.

repoquery: update and unify repoquery manpage

---

dnf5/commands/repoquery/repoquery.cpp
dnf5/config/usr/share/dnf5/aliases.d/compatibility.conf

Also move the `--qf` alias into the formatting group.

repoquery: set conflicts/requires between arguments

---

dnf5/main.cpp
doc/misc/installroot.7.rst
libdnf5/base/base.cpp
libdnf5/logger/factory.cpp
test/libdnf5/logger/test_file_logger.cpp
test/python3/libdnf5/logger/test_file_logger.py

There should be a way to set a logdir outside the installroot [1].
Currently, when `--setopt=varsdir` and `--setopt=reposdir` are specified on the command line rather than in a config file, they are treated as relative to the host, not the installroot. This patch changes `logdir` to behave the same way.
[1] https://github.com/rpm-software-management/dnf5/issues/721

Treat logdir relative to host when specified on command-line

---

test/python3/libdnf5/base/test_goal.py

After we enabled action plugin in action.conf on host system, it blocks builds. The patch does not resolve not informative error.
7/15 Test  #6: test_python3_libdnf .........................................***Failed    0.40 sec
....EEEE.E....................................................
======================================================================
ERROR: test_group_rpm_reason_change_without_id (base.test_goal.TestGoal.test_group_rpm_reason_change_without_id)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/tmp/tito/rpmbuild-dnf5ite8yota/BUILD/dnf5-git-2540.4dd1be3/test/python3/libdnf5/base/test_goal.py", line 66, in test_group_rpm_reason_change_without_id
base.setup()
File …

Set installroot in Python unit tests

---

dnf5/context.cpp
include/libdnf5/rpm/rpm_signature.hpp
libdnf5/base/transaction.cpp
libdnf5/rpm/rpm_signature.cpp
test/libdnf5/base/test_transaction.cpp
test/python3/libdnf5/base/test_transaction.py
test/python3/libdnf5/rpm/test_rpm_signature.py

As enumerated by Panu here: https://github.com/rpm-software-management/dnf5/issues/617#issuecomment-1592633793:
- This message is not present as of bfedca82d84d5588f4f57142fe7953b520eedefb, but we may want to print a warning to the console anyway, ideally after the transaction is run so it's visible to the user
Resolves https://github.com/rpm-software-management/dnf5/issues/617.

gpgcheck security and usability fixes

---

include/libdnf5/repo/repo.hpp
libdnf5/repo/repo_downloader.cpp

It allows substitutions in mirrorlist.
Additionally it marks method of Repo class as deprecated, because it is not required anymore.
Closes: https://github.com/rpm-software-management/dnf5/issues/761
CI-test: https://github.com/rpm-software-management/ci-dnf-stack/pull/1347

Set substitution for librepo handle from Base Vars

---

dnf5-plugins/builddep_plugin/builddep.cpp
dnf5-plugins/changelog_plugin/changelog.cpp
dnf5-plugins/repoclosure_plugin/repoclosure.cpp
dnf5/commands/check-upgrade/check-upgrade.cpp
dnf5/commands/list/list.cpp
dnf5/commands/repoquery/repoquery.cpp
dnf5/context.cpp
dnf5daemon-server/dbus/interfaces/org.rpm.dnf.v0.rpm.Rpm.xml
dnf5daemon-server/services/rpm/rpm.cpp
libdnf5-plugins/actions/actions.cpp
libdnf5/base/goal.cpp
libdnf5/base/transaction.cpp
libdnf5/rpm/package_sack.cpp
test/libdnf5/rpm/test_package_query.cpp

The issue was created by adding binary search that is enabled by default.
Closes: https://github.com/rpm-software-management/dnf5/issues/763
CI-Test: https://github.com/rpm-software-management/ci-dnf-stack/pull/1353

Limit exclude search for only  NEVRA

---

libdnf5/conf/vars.cpp

The architecture is already supported in libsolv/rpm/libnf/dnf4.
For: https://github.com/rpm-software-management/dnf5/issues/792

vars: Add support for loongarch64

---

libdnf5/conf/vars.cpp

If there is an item in the vars directory that is either inaccessible
(e.g. permission denied) or cannot be read from (e.g. a directory),
skip this item and write a warning to the log.
For: https://github.com/rpm-software-management/dnf5/issues/792

vars: Ignore unreadable vars files.

---

dnf5.spec

The patch prevents replacement of microdnf and dnf by dnf5 in RHEL10 and previous versions.

Modify dnf and microdnf obsoletes for RHEL

---

libdnf5/conf/vars.cpp

Currently used `rpmGetArchInfo()` API corresponds to basearch and not the
actual architecture, causing problems with incompatible architectures
during transaction resolving.
To really get the actual architecture, we need to use
`rpmExpand("%_host_cpu", NULL)`, which is also what RPM uses to detect
the architecture.
Resolves: https://github.com/rpm-software-management/dnf5/issues/795
(also see the discussion there for details)

vars: Change detecting arch mechanism

---

dnf5/main.cpp
include/libdnf5/repo/repo_errors.hpp
libdnf5/repo/repo_sack.cpp

Exception is thrown in case the configuration contains repository id
multiple times (including repos added by --repofrompath option).
Resolves: https://github.com/rpm-software-management/dnf5/issues/794
Resolves: https://github.com/rpm-software-management/dnf5/issues/793
Resolves: https://github.com/rpm-software-management/dnf5/issues/399

repo: Error out on creating repo with duplicate id

---

libdnf5/solv/pool.hpp

Closes: https://github.com/rpm-software-management/dnf5/issues/520
Additional details in: https://github.com/openSUSE/libsolv/pull/531
Test: https://github.com/rpm-software-management/ci-dnf-stack/pull/1346

Set pool flag to fix pool_addfileprovides_queue() without filelists.xml

---

dnf5.spec

This pr enable dnf5 builds that obsolete dnf5
it is used by https://copr.fedorainfracloud.org/coprs/rpmsoftwaremanagement/dnf5-testing/
related to: https://github.com/rpm-software-management/dnf/pull/1976

Configure copr repo dnf5-testing

---

dnf5/main.cpp
include/libdnf5/common/exception.hpp
libdnf5/common/exception.cpp
libdnf5/repo/repo_sack.cpp

Currently, for `libdnf5::Errors`, only the outermost error message is printed, even if the error contains nested errors, which can cause some crucial details to be left out.
Resolves https://github.com/rpm-software-management/dnf5/issues/804.

Print error messages in nested errors

---

dnf5/commands/repo/repo_info.cpp
dnf5/commands/repo/repo_info.hpp
dnf5daemon-client/commands/repolist/repolist.cpp
dnf5daemon-client/wrappers/dbus_repo_wrapper.hpp
dnf5daemon-server/services/repo/repo.cpp
include/libdnf5-cli/output/repo_info.hpp
include/libdnf5/repo/repo.hpp
libdnf5/repo/repo.cpp

Provide `repo info` command with attributes included in original dnf command and several more:
- status: `enabled` / `disabled`
- priority
- cost
- type: `available` / `commandline`
- skip if unavailable: `true` / `false`
- PGP info
- keys (from the `gpgkey` option)
- verify repodata: `true` / `false` (from the `repo_gpgcheck` option)
- verify packages: `true` / `false` (from the `gpgcheck` option) 
Related issue: https://github.com/rpm-software-management/dnf5/issues/150.
CI tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1363.

Implementation of repo info command

---

libdnf5/repo/repo_sack.cpp

It turned out that with copr inter-project dependency it's possible to
have a repo id present in configuration files multiple times.
With this patch dnf5 will not error out, but only log an error and
ignore duplicate repo.
For repositories defined by --repofrompath option the previous behaviour
is preserved, and dnf5 still errors out.
Now the behaviour is consistent with dnf4.
Fixes: https://github.com/rpm-software-management/dnf5/issues/399

repo: Don't error out on duplicate repo id

---

libdnf5/solv/reldep_parser.cpp

Fix reldep regex to match the parsing from dnf to work also with expressions without spaces between cmp and evr.
CI test: https://github.com/rpm-software-management/ci-dnf-stack/pull/1365.
Closes #825.

reldep_parser: Revert reldep regex to match dnf

---

dnf5/commands/repoquery/repoquery.cpp
dnf5/commands/repoquery/repoquery.hpp
include/libdnf5/rpm/package.hpp
libdnf5-cli/output/repoqueryformat.cpp
libdnf5/rpm/package.cpp

For: https://github.com/rpm-software-management/dnf5/issues/589
For: https://github.com/rpm-software-management/dnf5/issues/366
It should also be used for: https://github.com/rpm-software-management/dnf5/issues/497
Unlike the dnf4 version the package now returns a `std::vector` of all its remote locations.
It also takes into account pkg baseurl (if there is one) which should ensure that the returned location is always the same one which dnf (librepo) would attempt to download first.
Tests update: https://github.com/rpm-software-management/ci-dnf-stack/pull/1328

repoquery: add `--disable-modular-filtering` and `--location`

---

libdnf5/solv/solv_map.hpp

Add `#include <stdexcept>` directly to solv_map.hpp so that `std::out_of_range` is guaranteed to exist.
Fixes #768

libdnf5: add stdexcept header to fix missing exception error

---

doc/changes.rst

The `--noautoremove` option was added back to the `remove` command, so we don't need to mention it in `changes.rst`.
See https://github.com/rpm-software-management/dnf5/pull/755

changes.rst: --noautoremove was added back

---

libdnf5/solv/reldep_parser.cpp

Sticking to POSIX-compatible extended regular expressions makes the code more portable.  In particular, this change is required to avoid an abort at load time on FreeBSD.
No functional change intended.

Avoid using GNU extensions in the dependency splitter regex

---

dnf5/commands/repoquery/repoquery.cpp
doc/commands/repoquery.8.rst
libdnf5-cli/output/repoqueryformat.cpp

There is quite a bit of code reorganization, I am trying to make the slur of repoquery options more understandable but if you don't consider these changes worth it (they do complicate the history and could be confusing) I can drop them.
There is also a couple of small improvements like: option conflicts, docs improvements, fix for `--recent`, one better exception and faster `--querytags`.

Repoquery reorganize and small improvements

---

bindings/libdnf5/conf.i
dnf5/main.cpp
include/libdnf5/conf/vars.hpp
libdnf5/conf/vars.cpp
test/libdnf5/conf/test_vars.cpp

Resolves https://github.com/rpm-software-management/dnf5/issues/710.
Add `$releasever_major` and `$releasever_minor`: whenever the `releasever` var is set, automatically derive and set the `releasever_major` and `releasever_minor` vars by splitting `releasever` on the first dot. In the future (or now, possibly), we may also want to add `releasever_patch`.
Compatible with this implementation in libzypp:
https://github.com/openSUSE/libzypp/blob/d03a02d986f43266af81c73cced1b310e8615971/zypp/repo/RepoVariables.cc#L478-L495
Also adds support for `${variable:-word}` and `${variable:+word}` expansions of vars, similar to the functionality in POSIX shell.
`${variable:-word}` means if `variable` is unset or empty, the expansion of `word` is substituted. Otherwise, the value of `variable` is …

Add support for $releasever_major, $releasever_minor, and limited shell expansion

---

bindings/go/CMakeLists.txt
bindings/perl5/CMakeLists.txt
bindings/python3/CMakeLists.txt
bindings/ruby/CMakeLists.txt

- perl5: add missing linking against `${PERL_LIBRARY}`
- ruby: fix linking, replace `${RUBY_LIBRARIES}` with `${RUBY_LIBRARY}`
`${RUBY_LIBRARY}` or `${Ruby_LIBRARIES}` can be used - same meaning.
- use `target_link_libraries` instead of deprecated `swig_link_libraries`
`swig_link_libraries` has been deprecated since cmake 3.13
Missing links detected thanks to issue https://github.com/rpm-software-management/dnf5/issues/267.

swig: Fix linking targets to dependencies

---

dnf5.spec
dnf5/context.cpp
dnf5/main.cpp
dnf5daemon-server/session.cpp
include/libdnf5/base/base.hpp
include/libdnf5/conf/const.hpp
libdnf5/CMakeLists.txt
libdnf5/base/base.cpp
libdnf5/config.h.in
test/python3/libdnf5/base/test_base.py
test/python3/libdnf5/tutorial/session/create_base.py
test/tutorial/session/create_base.cpp

Introduces a new method `Base::load_config()` to replace `Base::load_config_from_file()`.
In the original implementation, the `Base` class constructor loads the default configuration from the distribution configuration file ("/usr/share/dnf5/libdnf.conf"). And later, the user configuration (by default "/etc/dnf/dnf.conf") was loaded by calling the `Base::load_config_from_file()` method.
**New implementation:**
1. The `Base` class constructor does not load any configuration file.
2. The application calls `Base::load_config()` method instead of `Base::load_config_from_file()`.
**The order of loading the configuration files by the method `Base::load_config()`:**
1. Creates an alphabetically sorted list of names of all configuration files in the distribution configuration drop-in directory …

Add support for drop-in configuration directories 

---

libdnf5/rpm/package_query.cpp
libdnf5/solv/pool.cpp
libdnf5/solv/pool.hpp

DNF5 detects first, whether provided argument contains epoch (find ':') then it construct package strings IDs accordingly.
CI-tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1372
Closes: https://github.com/rpm-software-management/dnf5/issues/614

Fix algorithm in package NEVRA filter

---

dnf5/main.cpp
include/libdnf5/logger/factory.hpp
libdnf5/logger/factory.cpp
test/libdnf5/logger/test_file_logger.cpp
test/libdnf5/logger/test_file_logger.hpp
test/python3/libdnf5/logger/test_file_logger.py

I think responsibility for setting the log file name should be on the API
users, and not the library.
This patch enhances `create_file_logger()` method to accept log file name
parameter and also deprecates the variant without the name.
Resolves: https://github.com/rpm-software-management/dnf5/issues/834

logger: Possibility to set log file name

---

dnf5/commands/repo/repo_info.cpp

With this should `repo info` always print repositories alphabetically sorted.
Fixes: https://github.com/rpm-software-management/dnf5/issues/858

dnf5: Sort repos in 'repo info' command output

---

libdnf5/base/goal.cpp
libdnf5/module/module_goal_private.cpp
libdnf5/module/module_goal_private.hpp
libdnf5/module/module_sack.cpp

Save debug solver data into the `debugdir` / "modules" subdirectory after module goal is resolved.
Also, use canonical format when displaying debug data file path to the user and show just the path to the parent directory as there could be more debug data subdirectories (e.g. like "modules") inside.
Related issue: https://github.com/rpm-software-management/dnf5/issues/172.

Add debug solver data for modules

---

libdnf5-plugins/actions/actions.conf
libdnf5/plugin/plugins.cpp
libdnf5/plugin/plugins.hpp

The name of the plugin to load was derived from the name of the plugin configuration file. Plugin configuration files are sorted by name. And then they are loaded in that order. The intention was to prefix the configuration file name with a number to define the order. This breaks the plugin name derivation mechanism.
This modification adds support for the `name` key to the configuration file to define the plugin name. If `name` key is not found, the original approach - deriving the name of the plugin from the name of the configuration file - will be used as a fallback.
Also, a warning is added to the log in case the plugin name from the configuration file differs from the real one.

libdnf5 plugins configuration: Support "name" key to define plugin name in cfg file

---

dnf5.spec
include/libdnf5/conf/const.hpp
include/libdnf5/repo/repo_sack.hpp
libdnf5/CMakeLists.txt
libdnf5/base/base.cpp
libdnf5/config.h.in
libdnf5/repo/repo_sack.cpp
libdnf5/utils/fs/utils.cpp
libdnf5/utils/fs/utils.hpp
libdnf5/utils/iniparser.cpp
test/libdnf5/iniparser/test_iniparser.cpp
test/libdnf5/iniparser/test_iniparser.hpp

After the repositories configuration is loaded, new code is run that loads the override files from the `/usr/share/dnf5/repos.override.d` and `/etc/dnf/repos.overide.d` directories.
The format of override files is the same as regular ".repo" files. However, override files can modify the settings of already existing repositories. They cannot create new repositories.
Overide files support glob in the repository ID (in the configuration file section name) to support bulk modification of repositories parameters.
**The order of processing the files with overrides:**
1. Creates an alphabetically sorted list of all filenames with overrides in the distribution override directory ("/usr/share/dnf5/repos.override.d") and the user override directory ("/etc/dnf/repos.overide.d"). If a file with the …

Add support for repos configuration overrides

---

libdnf5/rpm/solv/goal_private.cpp

libdnf5 companion to https://github.com/rpm-software-management/libdnf/pull/1610

Allow obsoletion of protected packages

---

dnf5/shared_options.cpp
include/libdnf5-cli/argument_parser.hpp
include/libdnf5/rpm/arch.hpp
libdnf5/base/base.cpp
libdnf5/conf/vars.cpp
libdnf5/rpm/arch.cpp
libdnf5/rpm/arch_private.hpp

Currently, libdnf5 initializes librpm only when detecting `arch` or
`releasever` variables. In case both these values are provided using
command line options (--releasever, --forcearch), `rpmReadConfigFiles()`
is not called at all, resulting in uninitialized librpm.
This patch moves `init_lib_rpm()` call to the `Base` class constructor,
ensuring that `rpmReadConfigFiles()` is always called.
Resolves: https://github.com/rpm-software-management/dnf5/issues/855

base: Call rpmReadConfigFiles() earlier

---

common/utils/string.hpp
include/libdnf5-cli/output/repo_info.hpp
libdnf5-cli/output/transactioninfo.cpp
libdnf5-cli/output/transactionlist.cpp

From: https://download.copr.fedorainfracloud.org/results/rpmsoftwaremanagement/dnf5-unstable/fedora-37-i386/06330258-dnf5/builder-live.log.gz
```
/builddir/build/BUILD/dnf5-5.1.2-20230822004434.9.g54ab9891/include/libdnf5-cli/output/repo_info.hpp:67:86: error: conversion from 'long long int' to 'time_t' {aka 'long int'} may change value [-Werror=conversion]
67 |         last_update = fmt::format("{:%F %X}", std::chrono::system_clock::from_time_t(cache_updated));
|                                                                                      ^~~~~~~~~~~~~
```
It is failing in nightly: https://copr.fedorainfracloud.org/coprs/rpmsoftwaremanagement/dnf5-unstable/build/6350897/

Add missing cast to fix build on i386

---

common/utils/string.hpp

Follow up to: https://github.com/rpm-software-management/dnf5/pull/844
Closes: https://github.com/rpm-software-management/dnf5/issues/889

Print more useful form for large epochs that don't fit into `time_t`

---

bindings/libdnf5/rpm.i
dnf5/shared_options.cpp
include/libdnf5/rpm/arch.hpp
libdnf5/conf/vars.cpp
libdnf5/rpm/arch.cpp
libdnf5/rpm/arch_private.hpp
test/libdnf5/rpm/test_arch.cpp
test/libdnf5/rpm/test_arch.hpp
test/python3/libdnf5/rpm/test_arch.py

Let's also standardize the rpm.arch interface by consistently using the std::string type for both arguments and return values. While this might not be the most optimal choice (as the underlying structure is char *), I prioritize consistency over performance in this case. I did consider using std::string_view, but it's not supported by SWIG.
Unit tests included.
Resolves: https://github.com/rpm-software-management/dnf5/issues/600

Make get_base_arch() public

---

include/libdnf5/repo/repo_sack.hpp
libdnf5/base/goal.cpp
libdnf5/repo/repo_sack.cpp

Save debug solver data into the debugdir / "comps" subdirectory.
The `dump_comps_debugdata()` method is being exposed on the `libdnf5::repo::RepoSack` public API where there is already an existing `dump_debugdata()` for dumping the rpm solver data.
Related issue: https://github.com/rpm-software-management/dnf5/issues/172.

Add debug solver data for comps

---

libdnf5/conf/config_main.cpp

DNF 5, like DNF 4, should be marked as protected to prevent accidental removal.
Doing it this way, rather than using a file in /etc/dnf/protected.d, means that DNF 4 will still be able to remove DNF 5. I think this is the ideal functionality: DNF 4 will be able to remove DNF 5 and vice-versa, but neither package manager will accidentally remove itself.
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=2221907 "dnf5 is not marked as protected, removal leaves system more or less bricked ".

Hardcode protection of dnf5 package

---

CONTRIBUTING.md

Phasing out the "ready-for-review" label in favor of GitHub's "Draft Pull Request" system, per
https://github.com/rpm-software-management/dnf5/discussions/821.
Also removed the mention of the "work in progress" label; I think we want to use this for PRs that need significant redesign rather than PRs where the author is requesting additional help.
If this is merged, I'll remove the "ready-for-review", "changes-requested", "dnf5", and "deferred" labels; that seemed to be the consensus in https://github.com/rpm-software-management/dnf5/discussions/821.

CONTRIBUTING: don't mention "ready-for-review"

---

dnf5/include/dnf5/context.hpp
dnf5/main.cpp
doc/dnf5.8.rst

If dnf5 is run with this argument, variable values are added to standard output.
The old DNF4 supports this argument only with the `config-manager` plugin. If the user wants to know the values of the variables with which a certain command will run, he must first use `config-manager` and then run the desired command with the same settings (same environment and configuration files) and hope that nothing changed in between (e.g. thanks to a plugin).
In other words, this PR implements part of the functionality of the dnf4 `config-manager` plugin, but for general use.
Related to: https://github.com/rpm-software-management/dnf5/issues/405

[dnf5] Implement new argument "--dump-variables"

---

CMakeLists.txt
dnf5.spec
libdnf5-plugins/CMakeLists.txt
libdnf5-plugins/rhsm/CMakeLists.txt
libdnf5-plugins/rhsm/rhsm.conf
libdnf5-plugins/rhsm/rhsm.cpp

Libdnf5 plugin with basic support for Red Hat subscriptions.
Synchronizes the enrollment with the vendor system. This can change the contents of the repositories configuration files according to the subscription levels.
The plugin uses the `librhsm` library. Just like the context part of the old lbdnf.
Solves https://github.com/rpm-software-management/dnf5/issues/859

libdnf5 plugin: Implement rhsm (Red Hat Subscription Manager) plugin

---

include/libdnf5/base/transaction.hpp
libdnf5/base/transaction.cpp

In order to have a easier workflow for making package caching exceptions for some commands and also to match the `keepcache` behavior with the original dnf in this matter, the cached files are now removed only when `keepcache` option is turned off at the moment.
We don't want to remove the stored packages cache after running the `remove` command transaction, therefore we override the `keepcache` option to true. This is useful for use cases when the previous transaction downloaded a large amount of data, but didn't finished correctly. Then we'd like to fix the system state by removing some problematic package. We don't want to lose our cached data in this case.
CI tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1381
Resolves: …

Don't drop cached packages when only removing packages (RhBug:2237883)

---

libdnf5-cli/argument_parser.cpp

Prints the options in the correct place. It also takes into account whether the parent command has options and arguments.
**Examples:**
**`dnf5 --help`:**
old: `dnf5 <COMMAND> [--help] ...`
new: `dnf5 [GLOBAL OPTIONS] <COMMAND> ...`
**dnf5 history --help:**
old: `dnf5 history <COMMAND> [--help] ...`
new: `dnf5 [GLOBAL OPTIONS] history <COMMAND> ...`
**`dnf5 history list --help`:**
old: `dnf5 history list [GLOBAL OPTIONS] [OPTIONS] [ARGUMENTS]`
new: `dnf5 [GLOBAL OPTIONS] history list [OPTIONS] [ARGUMENTS]`
**`dnf5 repo --help`:**
old: `dnf5 repo <COMMAND> [--help] ...`
new: `dnf5 [GLOBAL OPTIONS] repo [OPTIONS] <COMMAND> ...`
**`dnf5 repo list --help`:**
old: `dnf5 repo list [GLOBAL OPTIONS] [OPTIONS] [ARGUMENTS]`
new: `dnf5 [GLOBAL OPTIONS] repo [OPTIONS] list [OPTIONS] [ARGUMENTS]`

ArgumentParser::Command::help: Improve "usage" text

---

libdnf5/rpm/rpm_log_guard.cpp

RPMLOG_DEBUG is fairly low-level and causes librpm to not remove auxiliary temporary files. Therefore, it is not a good idea to use RPMLOG_DEBUG as the default. Everything except RPMLOG_DEBUG is now logged.
However, we should consider introducing an option to enable RPMLOG_DEBUG for debugging purposes.
It solves the issue https://github.com/rpm-software-management/dnf5/issues/893

Change librpm log mask value from 0xFF to everything up to RPMLOG_INFO

---

doc/commands/group.8.rst

dnf5-group(8) synopsis gave an impression that a group specifier is optional:
SYNOPSIS
dnf5 group <subcommand> [options] [<group-spec>...]
That's not true for "install" and "remove" commands. This patch fixes the manual.

doc: "group install" and "group remove" require an argument

---

dnf5/commands/module/arguments.hpp
dnf5/commands/module/module.cpp
dnf5/commands/module/module_list.cpp
dnf5/commands/module/module_list.hpp
doc/changes.rst
doc/commands/module.8.rst
include/libdnf5-cli/output/modulelist.hpp
include/libdnf5/module/module_item.hpp
include/libdnf5/module/module_profile.hpp
include/libdnf5/module/module_query.hpp
libdnf5/module/module_item.cpp
libdnf5/module/module_query.cpp
test/libdnf5/module/test_module.cpp

Closes: https://github.com/rpm-software-management/dnf5/issues/936
Closes: https://github.com/rpm-software-management/dnf5/issues/937

Add module list command

---

dnf5/include/dnf5/context.hpp
dnf5/main.cpp
doc/dnf5.8.rst

The DNF4 `config-manager` plugin supports the `--dump` argument. It prints the main configuration to standard output or, if followed by a list of repository IDs, prints the configuration of the matching repositories.
This implements part of the functionality of the dnf4 config-manager plugin, but for general use.
Related to: https://github.com/rpm-software-management/dnf5/issues/405

[dnf5] Implement new arguments "--dump-main-config", "--dump-repo-config=REPO_ID,..."

---

dnf5/include/dnf5/context.hpp
dnf5/main.cpp
doc/dnf5.8.rst

Shows newly installed leaf packages and packages that became leaves after a transaction.
I intend that the implementation of the `--show-new-leaves` argument in DNF5 will replace the functionality of the "show-leaves" plugin that is in the old DNF.
Unlike the plugin in the old DNF, this code calculates the new state (the list of new leaf packages) before the transaction is executed. The user will see the list even before confirming the transaction.

[dnf5] Implement new argument "--show-new-leaves"

---

dnf5/commands/repoquery/repoquery.cpp
include/libdnf5/rpm/package_query.hpp
libdnf5/rpm/package_query.cpp
libdnf5/rpm/solv/goal_private.hpp
libdnf5/rpm/transaction.cpp

I also plan to reuse the installonly filter in transaction replay.

PackageQuery: add `filter_installonly`

---

libdnf5/rpm/solv/goal_private.cpp

https://github.com/openSUSE/libsolv/issues/540
https://bugzilla.redhat.com/show_bug.cgi?id=2163474
https://issues.redhat.com/browse/RHEL-1253

Avoid reinstalling installonly packages marked for ERASE

---

dnf5/commands/distro-sync/distro-sync.cpp
dnf5/commands/download/download.cpp
dnf5/commands/group/group.cpp
dnf5/commands/install/install.cpp
dnf5/commands/list/list.cpp
dnf5/commands/makecache/makecache.cpp
dnf5/commands/repo/repo.cpp
dnf5/commands/repoquery/repoquery.cpp
dnf5/commands/search/search.cpp
dnf5/commands/swap/swap.cpp
dnf5/include/dnf5/shared_options.hpp
dnf5/main.cpp
doc/commands/distro-sync.8.rst
doc/commands/download.8.rst
doc/commands/group.8.rst
doc/commands/install.8.rst
doc/commands/makecache.8.rst
doc/commands/repo.8.rst
doc/commands/repoquery.8.rst
doc/commands/search.8.rst
doc/commands/swap.8.rst
doc/dnf5.8.rst

Many commands respect `--forcearch` (distro-sync, download, install, list, makecache, repoquery, search, etc.) so it makes sense to make `--forcearch` a global argument that can be used with any command.
Resolves https://github.com/rpm-software-management/dnf5/issues/872

Make `--forcearch` a global argument

---

dnf5.spec
libdnf5/CMakeLists.txt
libdnf5/rpm/solv/goal_private.cpp

I chose the name `--prefer-latest` but I would be happy to change it if there is a better name.
I think `--prefer-latest` is better than `focus-best` (used by libsolv) because it is more descriptive and doesn't confuse the behavior with the `--best` option.
Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1350

Use focusbest: prefer latest deps versions over smaller transactions

---

libdnf5-cli/argument_parser.cpp

Fixes handling of `named_arg` alias when calling `--long_name=value`. Before the fix, only `--long_name value` (without the equal sign) worked.

ArgumentParser::NamedArg::parse_long: Fix invoking attached named args

---

doc/requirements.txt

According to: https://sphinx-rtd-theme.readthedocs.io/en/stable/installing.html the dependency should be added to requirements.txt.
It was working previously becuase it was automatically installed by readthedocs, this has been changed: https://blog.readthedocs.com/python-core-requirements-changed/

readthedocs: install missing dependency `sphinx_rtd_theme`

---

include/libdnf5-cli/output/key_value_table.hpp
libdnf5-cli/output/key_value_table.cpp

Allow dropping the table group without any children to `KeyValueTable` API.
Created as a follow-up to the https://github.com/rpm-software-management/dnf5/pull/896 being closed.

key_value_table: Method to drop empty group

---

bindings/libdnf5/advisory.i
bindings/libdnf5/shared.i
doc/api/python/libdnf5_advisory.rst
doc/api/python/libdnf5_advisory_advisory.rst
doc/api/python/libdnf5_advisory_advisory_collection.rst
doc/api/python/libdnf5_advisory_advisory_module.rst
doc/api/python/libdnf5_advisory_advisory_package.rst
doc/api/python/libdnf5_advisory_advisory_query.rst
doc/api/python/libdnf5_advisory_advisory_reference.rst
doc/api/python/libdnf5_advisory_advisory_set.rst
doc/api/python/python.rst
doc/conf.py.in
test/python3/libdnf5/advisory/test_advisory.py

- Enable bindings for `AdvisoryModule`
- Add Advisory API Python tests - for https://github.com/rpm-software-management/dnf5/issues/213
- Add Advisory API Python docs
- Enables generating docs for undocumented methods for both C++ and Python bindings.

Advisory binding for AdvisoryModule and tests and docs for advisory Python API

---

README.md

Doc updates relates to fedora version being released soon and to these changes in our nightly builds:
https://github.com/rpm-software-management/ci-dnf-stack/pull/1396
https://github.com/rpm-software-management/ci-dnf-stack/pull/1394

Update README with updated coprs

---

dnf5-plugins/CMakeLists.txt
dnf5-plugins/builddep_plugin/CMakeLists.txt
dnf5-plugins/builddep_plugin/builddep.cpp

This patchset fixes issue #267. First commit fixes a transitive reliance on directly used librpm fucntions in builddep_plugin dnf plugin. The second commit disables -z defs for program plugins. As a result, it is possible to build DNF5 with "-z defs" among system-wide linker flags.

Fix building with -z defs

---

include/libdnf5/advisory/advisory_set.hpp

Add missing docs for `get_advisory_packages_sorted_by_name_arch_evr()`.

Add missing docs for `get_advisory_packages_sorted_by_name_arch_evr()`

---

CMakeLists.txt
dnf5.spec

Most Linux distributions shipping DNF do not need the RHSM plugin, and it really is only useful for the Red Hat Enterprise Linux family of distributions. Given that the RHSM stuff is often not shipped elsewhere, it's better to have this off by default and only turn it on when needed.
This is done by ensuring that the RPM spec file (which is both the reference spec file and the spec file used for RH/Fedora) turns it on and builds it.

Disable the RHSM plugin by default and enable it in the RPM spec

---

include/libdnf5/base/base.hpp
include/libdnf5/comps/environment/environment.hpp
include/libdnf5/comps/group/group.hpp
libdnf5/base/goal.cpp
libdnf5/comps/environment/environment.cpp
libdnf5/comps/group/group.cpp
libdnf5/system/state.cpp
libdnf5/system/state.hpp

This is currently always returning hard-coded `libdnf5::transaction::TransactionItemReason::NONE` breaking my transaction replay tests.
Part of https://github.com/rpm-software-management/dnf5/issues/999 work.

Implement `get_reason()` for groups and environments

---

doc/libdnf5_plugins/actions.8.rst
libdnf5-plugins/actions/actions.conf
libdnf5-plugins/actions/actions.cpp

The fourth item in the action definition has been reserved. It is now used to set additional action options. Options are separated by spaces. A space within an option can be written using escaping.
One option is now supported - `enabled=<value>`.
Supported values of `value`:
* `1` - action is always enabled
* `host-only` - the action is only enabled for operations on the host
* `installroot-only` - the action is only enabled for operations in the alternative "installroot"
Action can allways be disabled by commenting out the action line.
PR also adds a new `${plugin.version}` substitution. The expression is replaced by the actions plugin version.

[libdnf, actions plugin] Support for action options, option enabled and "plugin.version" variable

---

.packit.yaml

Requires https://github.com/rpm-software-management/ci-dnf-stack/pull/1405
Tests will fail. Once merged test with `/packit test` before merging.
Requirements to onboard:
Key advantages:
Future possible improvements:
Once this PR gets merged and works, the old actions can be removed: https://github.com/rpm-software-management/dnf5/pull/1008

 Add packit job copr and tests 

---

include/libdnf5-cli/output/transaction_table.hpp

"Disabling modules" and "Resetting modules" is correct, because the whole module gets disabled or reset, not individual streams. This is also consistent with dnf4.

modules: Fix transaction table headers for module operations

---

libdnf5/base/goal.cpp

When the user attempts to remove a group that is not installed, only
print a warning but the resolvement should not fail.
Fixes: https://github.com/rpm-software-management/dnf5/issues/917
Test: https://github.com/rpm-software-management/ci-dnf-stack/pull/1406

goal: Removal of not-installed group does not fail

---

libdnf5/comps/group/group.cpp

libxml2-2.12.0 shuffled header files and as a result a build failed:
cd /tmp/b/libdnf5 && /usr/bin/c++ -DGETTEXT_DOMAIN=\"libdnf5\" -DLIBSOLV_SOLVABLE_PREPEND_DEP -DPROJECT_BINARY_DIR=\"/tmp/b\" -DPROJECT_SOURCE_DIR=\"/home/test/dnf5\" -DPROJECT_VERSION_MAJOR=5 -DPROJECT_VERSION_MINOR=1 -DPROJECT_VERSION_PATCH=7 -DWITH_ZCHUNK -Dlibdnf5_EXPORTS -I/home/test/dnf5/include -I/home/test/dnf5/common -I/home/test/dnf5/libdnf5/. -I/usr/include/json-c -I/usr/include/libxml2 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-6 -std=gnu++20 -fPIC -fmacro-prefix-map=/home/test/dnf5/= -Wall -Wextra -Werror -Wcast-align -Wformat-nonliteral -Wmissing-format-attribute -Wredundant-decls -Wsign-compare -Wtype-limits -Wuninitialized -Wwrite-strings -Werror=unused-result -Wodr …

build: Restore compatiblity with libxml2-2.12.0

---

common/utils/string.hpp

There was a change in fmt-10.0.0 which adds support for sub-second precision printing.
Given that we want only whole seconds on the output round the time point to `std::chrono::seconds`.
Closes: https://github.com/rpm-software-management/dnf5/issues/1020

Epoch formatting: set whole seconds precision

---

libdnf5/base/base.cpp
libdnf5/module/module_sack_impl.hpp

It is important to provide architecture to libsolv pool, because it might lead to incorrect resolve of active module items.

Add arch to module pool

---

.github/workflows/weblate-sync-pot.yml

Otherwise the dnf5-l10n repo might contain mostly empty commits.

Workflow for *.pot sync exits if only creation dates were changed

---

libdnf5/base/transaction.cpp

Correctly report "Argument matches only source packages." in case user
tries to install a source rpm.
Current code misleadingly reports "Argument matches only excluded
packages."

transaction: Fix reporting spec matches only source

---

libdnf5/rpm/package_query.cpp

To fully update CPU microcode, a reboot is needed because the microcode update should be applied before starting a kernel and other process.
Therefore recommend a reboot after installing or updating microcode_ctl package.
https://issues.redhat.com/browse/RHEL-4600

needs-restarting: Add microcode_ctl to a reboot list

---

libdnf5/base/transaction.cpp
libdnf5/repo/package_downloader.cpp
libdnf5/repo/temp_files_memory.cpp
libdnf5/repo/temp_files_memory.hpp
test/libdnf5/repo/test_package_downloader.cpp
test/libdnf5/repo/test_temp_files_memory.cpp
test/libdnf5/repo/test_temp_files_memory.hpp

Based on the https://github.com/rpm-software-management/dnf5/issues/1001, adding a check after the toml serialization of temporary files memory to make sure the result is not an empty file. Such a file would not be parsable when loading from the disk afterwards.
Closes #1001.

Check serialized temporary files memory is non-empty

---

libdnf5/rpm/package_query.cpp

Libsolv is unable to match globs in installonly set `job multiversion provides kernel*` will not mach with anything.
The `Query::filter_installonly() should provide the same behavior therefore query filter must not support globs.

Modify installonly filter

---

dnf5/commands/group/group_upgrade.cpp
doc/changes.rst
doc/commands/distro-sync.8.rst
doc/commands/downgrade.8.rst
doc/commands/group.8.rst
doc/commands/install.8.rst
doc/commands/mark.8.rst
doc/commands/reinstall.8.rst
doc/commands/upgrade.8.rst
doc/dnf5.8.rst

- Document dropped support of the `--skip-broken` option from the `upgrade` command
- Exclude the `--skip-broken` option from the global options documentation, restricting only to related commands
- Add missing man pages documentation for options related to resolving missing dependencies
Closes #1033.

Support skip-broken option for the upgrade command

---

dnf5/commands/history/history.cpp
dnf5/commands/history/history_store.cpp
dnf5/commands/history/history_store.hpp
include/libdnf5/base/goal.hpp
include/libdnf5/base/goal_elements.hpp
include/libdnf5/base/transaction.hpp
include/libdnf5/transaction/transaction.hpp
libdnf5/base/goal.cpp
libdnf5/base/transaction.cpp
libdnf5/base/transaction_impl.hpp
libdnf5/transaction/transaction.cpp
libdnf5/transaction/transaction_sr.cpp
libdnf5/transaction/transaction_sr.hpp

This is a second iteration for: https://github.com/rpm-software-management/dnf5/pull/978 I have made a new PR because it nearly completely changed and the old comments could be confusing.
Now there is only one approach and replaying a transaction must go through a `libdnf5::Goal`. The new API is:
- `void libdnf5::Goal::add_transaction_replay(const std::string & json_serialized_transaction, libdnf5::GoalJobSettings & settings_p);`
- `std::string libdnf5::base::transaction::serialize_to_json();`
- `std::string libdnf5::transaction::transaction::serialize_to_json();`
For: https://github.com/rpm-software-management/dnf5/issues/999

Add capabilities for storing and replaying a transaction

---

common/utils/auth.cpp
common/utils/auth.hpp
dnf5/context.cpp
dnf5/main.cpp
include/libdnf5/repo/repo.hpp
libdnf5/repo/repo.cpp
libdnf5/repo/repo_sack.cpp
libdnf5/repo/solv_repo.cpp

When preparing repositories within `repo_sack`, check for empty or invalid repository metadata. If either condition is met, attempt to clone the root metadata cache, if available.
Solver cache files use the `mkstemp` method and are only readable by the owner. Read attributes have been added to these files.
The packages cache is ignored. It is expected that superuser privileges will be required for any command manipulating packages on the system (see #849 or #337).
Additional notes:
- Copy-on-write functionality is automatically utilized by the filesystem when a copy operation is performed on a filesystem that supports it, such as Btrfs (the default in Fedora).
- For repodata, the default cache location is `/var/cache`, where read permissions are granted to non-owners. However, if a custom …

Sharing root cache with users

---

test/libdnf5/rpm/test_transaction.cpp

In order to allow further investigation of issues on the RISC-V arch.
For: https://github.com/rpm-software-management/dnf5/issues/503.

Temporarily skip asserts on transaction unit tests

---

libdnf5-cli/progressbar/multi_progress_bar.cpp

Resolves: https://github.com/rpm-software-management/dnf5/issues/1058

cli: Progress bars miss newlines on non-interactive output

---

dnf5/bash-completion/dnf5

The original version used "Process Substitution". dnf5 was run in another process and the output was referenced by filename (usually /dev/fd/63). That tends to be a problem in the chroot.
The new version uses "Command Substitution". dnf5 is run and its output is passed using "Here Strings".
The patch resolves the issue:
`dnf5 bash: /dev/fd/63: No such file or directory`

dnf5: bash-completion: Use Command substitution instead of Process subst

---

dnf5/commands/check/check.cpp

It uses a loop to go through the rpmdb database instead of using the `rpmcliVerify` and `rpmcliQuery` functions (which then called back our code).
Why this PR:
- The original version uses the `rpmcliVerify` and `rpmcliQuery` functions from the librpm library. These functions, from C library, go through the rpmdb database and call back a C++ function from our code for each element. Our C++ function may throw an exception. The result may work, but it's generally better to avoid this situation (passing C++ exceptions through the C library.). In the new version, our code goes through the database and C callbacks are not used.
- librpm does not pass "user" data in callbacks. Therefore, they were passed through global variables (ok, they are in an anonymous namespace, available only in the …

dnf5: "check" command - optimize, don't use rpmcli

---

dnf5-plugins/builddep_plugin/builddep.cpp

Not parsing the pkg specs as globs would require an ABI-breaking change (https://github.com/rpm-software-management/dnf5/pull/1085). A workaround that doesn't involve breaking changes is to escape the glob characters in the pkg specs.
Related: https://github.com/rpm-software-management/mock/issues/1267
Resolves https://github.com/rpm-software-management/dnf5/issues/1084

builddep: Escape glob characters in pkg specs

---

include/libdnf5-cli/output/moduleinfo.hpp

This produces the same output as dnf4 - splits the string into multiple lines instead of containing ugly escape code.

modules: info - better format summary and description

---

libdnf5/module/module_dependency.cpp
test/libdnf5/module/test_module.cpp

Add ":[]" when any stream is required instead of keeping only the module name. This makes it consistent with `modulemd_stream` yaml and with dnf4 output of the module info command.

modules: Change module dependency string to be the same as in dnf4

---

dnf5/commands/clean/clean.cpp

Add a list of supported types to clean command description.
Closes: https://github.com/rpm-software-management/dnf5/issues/1099

Add a list of supported types to clean command description

---

dnf5/context.cpp
dnf5/main.cpp
doc/changes.rst
libdnf5/repo/repo_sack.cpp

Options `--setopt`, `--enable-repo`, `--disable-repo` and `--repo` will not accept repo-id vaule that doesn't match any configured repository.
This is different to dnf4 where only `--repo` and `--enablerepo` throw an error on invalid repo id. `--disablerepo` just shows a warning and `--setopt` doesn't show any problem.
Closes: https://github.com/rpm-software-management/dnf5/issues/1082

Throw an error on invalid repo input for `setopt` and `*repo` options

---

dnf5/commands/upgrade/upgrade.cpp

- Added the option -destdir to the dnf5 update command
Fixes: #603 
Example Command Run:
Example Output Files:

Added destdir option to update command

---

include/libdnf5-cli/output/moduleinfo.hpp
include/libdnf5-cli/output/modulelist.hpp

Also removes the note to sort the module list table, because it's already sorted.

modules: Sort the module info table

---

dnf5/include/dnf5/iplugin.hpp
dnf5/plugins.cpp
doc/dnf5_plugins/index.rst
doc/index.rst
doc/libdnf5_plugins/actions.8.rst
doc/libdnf5_plugins/index.rst
doc/templates/dnf5-plugin/CMakeLists.txt
doc/templates/dnf5-plugin/template.cpp
doc/templates/dnf5-plugin/template.hpp
doc/templates/dnf5-plugin/template_cmd_plugin.cpp
doc/templates/index.rst
doc/templates/libdnf5-plugin/CMakeLists.txt
doc/templates/libdnf5-plugin/template.conf
doc/templates/libdnf5-plugin/template.cpp
doc/templates/template-command.rst
doc/templates/template-dnf5-plugin.rst
doc/templates/template-libdnf5-plugin.rst
doc/tutorial/plugins/dnf5-plugins.rst
doc/tutorial/plugins/index.rst
doc/tutorial/plugins/libdnf5-plugins.rst
include/libdnf5/plugin/iplugin.hpp

Documentation updates cover the following aspects:
- DNF5 and LIBDNF5 plugins
- Example template codes
- Purpose of plugins
- Deployment description
Closes #287.

doc: Add a tutorial how to write plugins

---

dnf5daemon-server/package.cpp
dnf5daemon-server/package.hpp

This is needed for porting over dnfdragora from dnfdaemon.

dnf5daemon-server: Add RPM package Group attribute 

---

dnf5.spec

zchunk is not supported in RHEL, and other related packages also disable their zchunk dependency on RHEL.

Disable zchunk on RHEL

---

dnf5.spec

rpminspect complains on a dnf5 build:
Subpackage dnf5-plugins on x86_64 carries 'Requires:
libdnf5-cli.so.1()(64bit)' which comes from subpackage libdnf5-cli
but does not carry an explicit package version requirement. Please
add 'Requires: libdnf5-cli = %{version}-%{release}' to the spec
file to avoid the need to test interoperability between various
combinations of old and new subpackages.
This patch adds the dependency into dnf5.spec.
The very same dependency already exists in dnf5daemon-client and libdnf5-cli bindings.

Packaging: Require an exact release of libdnf5-cli by dnf5-plugins

---

dnf5/commands/remove/remove.cpp
dnf5daemon-server/services/rpm/rpm.cpp
doc/changes.rst
doc/commands/remove.8.rst
doc/commands/repoquery.8.rst

It prevents additional removal after succesful remove using the same spec. Spec `foo`. The original code during the first run removes (dnf5 remove foo) all packages with the name `foo`. In the next run (dnf5 remove foo) it removes all packages providing `foo`. The next run will remove packages providing binary `foo`. This behavior is inconsistent.
Resolves: https://issues.redhat.com/browse/RHEL-5747
CI-tests - https://github.com/rpm-software-management/ci-dnf-stack/pull/1430

Limit search pattern for remove command

---

dnf5/commands/repoquery/repoquery.cpp
dnf5/commands/repoquery/repoquery.hpp
doc/changes.rst
doc/commands/repoquery.8.rst
include/libdnf5-cli/output/repoquery.hpp
libdnf5-cli/output/repoqueryformat.cpp

I am proposing to change the `repoquery` `--resolve` option to `--providers-of=PACKAGE_ATTRIBUTE`.
The `--resolve` option was using the existing formatting options (`--requires`, `--provides`,...) to determine for which package attribute it should find providers. This is confusing because it completely changes the meaning of those options
and their original functionality is no longer available.
Instead add a new `--providers-of=` option which allows specifying the package attribute directly.
(Another option, perhaps a bit more compatible, would be to call the option `--resolve=PACKAGE_ATTRIBUTE`.)
More context: the `--resolve` option is also used in [download](https://dnf-plugins-core.readthedocs.io/en/latest/download.html#options) and …

repoquery: add `--providers-of=PACKAGE_ATTRIBUTE` and `--recursive` options

---

dnf5daemon-server/dbus/interfaces/org.rpm.dnf.v0.Base.xml

Commit a7036588575e3e15e5e62d28d3517305154a8b0a (dnfdaemon: Fix download callbacks) renamed repo_load_end signal to download_end, but forgot to change the name in org.rpm.dnf.v0.Base interface introspection file.
Fixes: https://github.com/rpm-software-management/dnf5/issues/1146

D-Bus: Fix download_end signal name in org.rpm.dnf.v0.Base interface

---

bindings/libdnf5/repo.i

Fixes error:
repoPYTHON_wrap.cxx:5656:56: error: expected template-name before '<' token
5656 |     struct SwigPyMapIterator_T : SwigPyIteratorClosed_T<OutIterator, ValueType, FromOper>
due to missing SWIG %fragment dependency on SwigPyIterator_T which provides the missing base class SwigPyIteratorClosed_T.
See https://github.com/swig/swig/issues/2744

Workaround for swig-4.2.0 missing fragment dependency

---

doc/misc/installroot.7.rst
libdnf5/base/base.cpp

Like `logdir`, the `cachedir` configuration option should be treated as relative to the installroot, unless it is specified on the command line via `--setopt=cachedir=/path/to/cachedir`. This is the behavior of the cachedir with DNF 4.
Currently, the host cache directory is used by default, conflicting with what our docs say (man 7 dnf5-installroot):
> cachedir, log files, releasever, and gpgkey are taken from or stored in the installroot.
After this change, the default cachedir is `$installroot/var/cache/libdnf5`, which is consistent with the docs.
For https://bugzilla.redhat.com/show_bug.cgi?id=2256945.

Make cachedir relative to installroot

---

doc/commands/distro-sync.8.rst
doc/commands/downgrade.8.rst
doc/commands/group.8.rst
doc/commands/install.8.rst
doc/commands/mark.8.rst
doc/commands/reinstall.8.rst
doc/commands/upgrade.8.rst
include/libdnf5/base/goal_elements.hpp

I think it must have been forgotten and just copied from builddep plugin.
Also removes two unused includes.
I have discovered this while restructuring `GoalJobSettings` and documenting them for https://github.com/rpm-software-management/dnf5/issues/1025.

Fix --skip-unavailable documentation

---

include/libdnf5/utils/bgettext/bgettext-mark-domain.h
include/libdnf5/utils/bgettext/bgettext-mark.h
libdnf5-cli/exception.cpp
libdnf5-cli/po/ka.po
libdnf5-cli/po/libdnf5-cli.pot
libdnf5-cli/po/sv.po

An empty string has a special meaning in gettext and marking such string produces invalid catalogs with a duplicate message ID entry.
Fixes: #1158

I18N: Do not mark empty strings for a translation

---

dnf5/commands/group/group_install.cpp
dnf5/commands/group/group_install.hpp
dnf5/commands/group/group_remove.cpp
dnf5/commands/group/group_upgrade.cpp
dnf5/commands/group/group_upgrade.hpp
doc/commands/group.8.rst

Allow passing `--allowerasing` option in group subcommands.
Resolves: https://github.com/rpm-software-management/dnf5/issues/1165.

group: Fix using allowerasing option

---

bindings/libdnf5/common.i
bindings/libdnf5/rpm.i
include/libdnf5/rpm/package.hpp
include/libdnf5/rpm/reldep.hpp
libdnf5/rpm/package.cpp
libdnf5/rpm/reldep.cpp

I believe we should directly set Python slot using SWIG feature (see bellow), but I was unable to make it working.
`%feature("python:slot", "tp_str", functype="reprfunc") libdnf5::rpm::Reldep::to_string;`
`set_property(SOURCE rpm.i PROPERTY SWIG_FLAGS "-builtin"`

Improve Python binding of Reldep and PAckage Classes

---

dnf5-plugins/config-manager_plugin/addrepo.cpp
dnf5-plugins/config-manager_plugin/setopt.cpp
dnf5-plugins/config-manager_plugin/setvar.cpp
dnf5-plugins/config-manager_plugin/unsetopt.cpp
dnf5/main.cpp
dnf5daemon-client/main.cpp

Make similar strings equals by replacing argument names with placeholders `{}`. This benefits translators that will see less strings for translation, but the major advantage is to assure consistency across similar translated strings.

Deduplicate strings for translations

---

libdnf5/rpm/package_query.cpp
test/libdnf5/rpm/test_package_query.cpp

The current implementation of the `filter_version` and `filter_release` filters
always uses the `cmp_eq` comparator. This means that these filters only work
with EQ and NEQ comparisons. The patch fixes these filters to work
correctly with LT, LTE, GT, and GTE comparisons as well.

package_query: Fix filter_version with non EQ comparator

---

dnf5daemon-client/commands/advisory/arguments.hpp

The comment is extracted by "xgettext -c" and placed to gettext catalogs. It helps the translators not know which words not to translate:
#. Note for translators: "critical" etc. quoted words are
#. literals that should not be translated.
#: commands/advisory/arguments.hpp:155
msgid ""
"Limit to packages in advisories with specified severity. List option. Can be "
"\"critical\", \"important\", \"moderate\", \"low\", \"none\"."
msgstr ""
Fixes: #1159

I18N: Annotate literals in advisory command

---

doc/dnf5.conf.5.rst
include/libdnf5/base/base.hpp
libdnf5/base/base.cpp
libdnf5/conf/config_main.cpp
libdnf5/conf/config_utils.cpp
libdnf5/conf/config_utils.hpp

It will allow to use configuration overrides from /usr for protected packages.
Resolves: https://github.com/rpm-software-management/dnf5/issues/1107
CI: https://github.com/rpm-software-management/ci-dnf-stack/pull/1431

Make protected_packages an append options

---

dnf5/commands/download/download.cpp
dnf5/commands/download/download.hpp

Fixes #497
Changes get the urls for the package specified by the --url option and returns the first url found as discussed.

Url option

---

dnf5-plugins/copr_plugin/copr_repo.cpp

Since the first placeholder `{}` is the number of an item (not the number of items), placing the placeholder after the word "item" makes the sentence clearer.
See discussion #1160.

Move number placeholder to postposition in copr_repo.cpp

---

doc/commands/upgrade.8.rst

This patch documents a new option added in commit
5b81b10d20372c8f653843e66428d7eaeccd838e ("Added upgrade option").
Fixes: #603

doc: Add --destdir option to upgrade command manual

---

.packit.yaml

Disable autorun of DNF and DNF5DAEMON. They can always be run with `/packit test` in a PR comment.
DNF tests are failing due to wrongly configured tmt.
The new tmt plans are tested in https://github.com/rpm-software-management/dnf/pull/2034
DNF5DAEMON tests are expected to fail due to a PR which specifies config overrides. https://github.com/rpm-software-management/dnf5/pull/1201

Disable dnf and dnf5daemon tests

---

dnf5daemon-server/session.cpp

Limit main config options overrides for dnfdaemon session only to
those explicitely allowed.

dnfdaemon: Exlicitely specify allowed config overrides

---

dnf5/commands/download/download.cpp
dnf5/commands/download/download.hpp
doc/commands/download.8.rst
libdnf5/rpm/package.cpp

Fixes #950 
- Implements --urlprotocols to the download command and limits the valid package urls to the set url protocols.
- If no protocols are specified, all protocols are considered valid.

Added urlprotocol option

---

dnf5.spec

A GCC 9.2 user reported this failure:
In file included from /home/rpm/rpmbuild/BUILD/common/utils/string.cpp:21:
/home/rpm/rpmbuild/BUILD/common/utils/string.hpp: In function 'std::string libdnf5::utils::string::format_epoch(T)':
/home/rpm/rpmbuild/BUILD/common/utils/string.hpp:115:14: error: 'in_range' is not a member of 'std'
115 |     if (std::in_range<time_t>(epoch_num)) {
|              ^~~~~~~~
The cause is that std::in_range<>() is a C++20 feature added to GCC in version 10.1.
This patch sets the minimal version in dnf5.spec.
Originally, I also wanted to add a check into a build script to fail early. std::in_range<>() is supported if the compiler defines __cpp_lib_integer_comparison_functions >= 202002L feature test macro.
However, checking for it in CMake is very difficult: …

Build: Require GCC 10.1 for std::in_range<>()

---

include/libdnf5/base/transaction_environment.hpp
include/libdnf5/base/transaction_group.hpp
include/libdnf5/base/transaction_module.hpp
include/libdnf5/base/transaction_package.hpp
libdnf5/base/transaction.cpp
libdnf5/base/transaction_environment.cpp
libdnf5/base/transaction_group.cpp
libdnf5/base/transaction_module.cpp
libdnf5/base/transaction_package.cpp
libdnf5/base/transaction_package_impl.hpp

This includes package, group, environment and module.
This PR is into a new dnf5-5.2.0.0 branch to keep the main branch API compatible.
Another part for: https://github.com/rpm-software-management/dnf5/issues/1025

Add pImpl to `libdnf5::base::transaction_*` classes

---

doc/changes.rst

Fixes: `WARNING: Title underline too short.`

Fix a warning when building docs.

---

include/libdnf5/module/module_item.hpp
libdnf5/module/module_item.cpp
libdnf5/module/module_query.cpp
libdnf5/module/module_sack.cpp

This PR is into a new dnf5-5.2.0.0 branch to keep the main branch API compatible.
Another part for: https://github.com/rpm-software-management/dnf5/issues/1025

Add pImpl to `ModuleItem` and remove definitions from header

---

libdnf5/rpm/solv/goal_private.cpp

This reverts commit 2d9df1c43b0b2f7027a6366dc1d64c0e646d1e2a.
The current behavior of `SOLVER_FLAG_FOCUS_BEST` turned out not be viable at this time, more details in: https://github.com/rpm-software-management/dnf5/issues/1106
Depending on https://github.com/openSUSE/libsolv/issues/549 we can either make the `SOLVER_FLAG_FOCUS_BEST` functionality configurable with a new option or use some different approach.
Closes https://github.com/rpm-software-management/dnf5/issues/1106

Revert "Use focusbest: prefer latest deps versions over smaller transactions

---

libdnf5-cli/output/advisorylist.cpp

A compilation fails on some systems with:
/home/rpm/rpmbuild/BUILD/libdnf5-cli/output/advisorylist.cpp: In function 'libscols_table* libdnf5::cli::output::create_advisorylist_table(std::string)':
/home/rpm/rpmbuild/BUILD/libdnf5-cli/output/advisorylist.cpp:33:9: error: 'isatty' was not declared in this scope
33 |     if (isatty(1)) {
|         ^~~~~~
The cause is a missing "#include <unistd.h>" in the compilation unit.
This bug was introduced in commit
d8d9c631faf259d0d4d88671fe2029749a081f66 (Add output formatting for advisory list and info into libdnf-cli).
Fixes: #1168

build: Include <unistd.h> for isatty()

---

.github/workflows/do-release.yaml
.github/workflows/package-build.yml
.github/workflows/pre-commit.yml
.github/workflows/prepare-release.yml

GitHub CI warns that Node.js 16 is deprecated:
CCache Build (clang)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
This patch moves action/checkout from v3 to v4 which is based on Node.js 20. It's fully compatible
<https://github.com/actions/checkout/compare/v3...v4.0.0>.

CI: Upgrade action/checkout to a version with Node.js 20

---

dnf5/commands/download/download.cpp
dnf5/commands/download/download.hpp
doc/commands/download.8.rst

Fixes: #946 
Add the --arch option to the download command. Filters queried compatible packages based on the specified architectures. If the architecture needs to be changed, the users can use the global --forcearch to change the base architecture.

Added arch option to the download command

---

include/libdnf5/rpm/package_query.hpp
libdnf5/rpm/package_query.cpp
test/data/repos-solv/solv-multiarch.repo
test/libdnf5/rpm/test_package_query.cpp
test/libdnf5/rpm/test_package_query.hpp

Resolves https://github.com/rpm-software-management/dnf5/issues/1111.
`filter_latest_evr` and `filter_earliest_evr` group packages by architecture and keep the latest package on each architecture. After `filter_latest_evr`, a PackageQuery might have anaconda-1-1.noarch as well as anaconda-2.2.x86_64.
This commit adds `filter_latest_evr_ignore_arch` and `filter_earliest_evr_ignore_arch` which filter for packages with the latest versions regardless of their architecture. Filtering the above anaconda example with `filter_latest_evr_ignore_arch` would result in just {anaconda-2.2.x86_64} since it is the latest version of the package for any arch.
This is an ABI-breaking change and thus is targeted at dnf5 5.2.

PackageQuery: Add `filter_{latest,earliest}_evr_ignore_arch`

---

.packit.yaml

To allow manual triggering of test suites on the GitHub PR with `/packit test –identifier <id>`.

Add tmt tests identifiers

---

dnf5/commands/download/download.cpp
dnf5/commands/download/download.hpp
doc/changes.rst
doc/commands/download.8.rst

Fixes #947
Implements the `--source` option for the download command to download only the source rpm(s).

download: add `--srpm` option

---

include/libdnf5/transaction/comps_environment.hpp
include/libdnf5/transaction/comps_group.hpp
include/libdnf5/transaction/rpm_package.hpp
include/libdnf5/transaction/transaction_history.hpp
include/libdnf5/transaction/transaction_item.hpp
libdnf5/transaction/comps_environment.cpp
libdnf5/transaction/comps_group.cpp
libdnf5/transaction/rpm_package.cpp
libdnf5/transaction/transaction_history.cpp
libdnf5/transaction/transaction_item.cpp

This includes `TransactionItem`, `CompsEnvironment`, `CompsEnvironmentGroup`, `CompsGroup`, `CompsGroupPackage`, `Package` and `TransactionHistory`.
This PR is into a new dnf5-5.2.0.0 branch to keep the main branch API compatible.
Another part for: https://github.com/rpm-software-management/dnf5/issues/1025

Add pImpl to libdnf5::transaction::* classes

---

include/libdnf5/base/log_event.hpp
include/libdnf5/base/solver_problems.hpp
include/libdnf5/conf/config_parser.hpp
include/libdnf5/conf/vars.hpp
include/libdnf5/repo/repo_sack.hpp
include/libdnf5/rpm/rpm_signature.hpp
include/libdnf5/transaction/transaction.hpp
libdnf5/base/log_event.cpp
libdnf5/base/solver_problems.cpp
libdnf5/conf/config_parser.cpp
libdnf5/conf/vars.cpp
libdnf5/repo/repo_pgp.cpp
libdnf5/repo/repo_sack.cpp
libdnf5/rpm/rpm_signature.cpp
libdnf5/transaction/transaction.cpp

This PR is into a new dnf5-5.2.0.0 branch to keep the main branch API compatible.
Another part for: https://github.com/rpm-software-management/dnf5/issues/1025
Specifically for `RpmSignature` I am proposing to convert it into a namespace rather than adding a `pImpl` to it, it is described in more details in the commit message.

Add pImpl to several classes

---

dnf5.spec

Fedora 41 moved a CMake script for bash-completion from bash-completion to bash-completion-devel package
<https://bugzilla.redhat.com/show_bug.cgi?id=1457164>. That broke building dnf5.spec:
~~~~
RPM build errors:
Directory not found: /builddir/build/BUILDROOT/dnf5-5.1.12-1.20240216152113944400.pr1250.22.gd9fb3e11.fc41.x86_64/usr/share/bash-completion
Directory not found: /builddir/build/BUILDROOT/dnf5-5.1.12-1.20240216152113944400.pr1250.22.gd9fb3e11.fc41.x86_64/usr/share/bash-completion/completions
File not found: /builddir/build/BUILDROOT/dnf5-5.1.12-1.20240216152113944400.pr1250.22.gd9fb3e11.fc41.x86_64/usr/share/bash-completion/completions/dnf5
~~~~
This adapts to the change.
Fixes: #1252

build: Adapt to changes in Fedora packaging of bash-completion

---

bindings/libdnf5/comps.i

The pending SWIG 4.2.1 release fixes a type tables bug requiring the definition of RepoQuery.
The generated type tables now allow for casting `RepoQuery` up the inheritance hierarchy to libdnf5::sack::Query<RepoWeakPtr> to libdnf5::Set<libdnf5::repo::RepoWeakPtr>.
See https://github.com/swig/swig/issues/2804.

Add repo_query.hpp for swig-4.2.1 support

---

dnf5daemon-server/dbus.hpp
dnf5daemon-server/polkit/org.rpm.dnf.v0.policy
dnf5daemon-server/session.cpp
dnf5daemon-server/session.hpp

Root user is allowed to override all config options.

dnfdaemon: Allow configuration overrides for root

---

dnf5/commands/list/list.cpp

It unifies behavior with repoquery command and DNF4
Closes: https://github.com/rpm-software-management/dnf5/issues/1259
Test: https://github.com/rpm-software-management/ci-dnf-stack/pull/1460

Make info and list commane case insesitive

---

include/libdnf5/advisory/advisory.hpp
include/libdnf5/advisory/advisory_collection.hpp
include/libdnf5/advisory/advisory_query.hpp
include/libdnf5/advisory/advisory_reference.hpp
libdnf5/advisory/advisory.cpp
libdnf5/advisory/advisory_collection.cpp
libdnf5/advisory/advisory_query.cpp
libdnf5/advisory/advisory_reference.cpp

Add pImpl to `libdnf5::advisory::*` classes
This PR is into a new dnf5-5.2.0.0 branch to keep the main branch ABI compatible.

Add pImpl to `libdnf5::advisory::*` classes

---

include/libdnf5/module/module_dependency.hpp
include/libdnf5/module/module_profile.hpp
include/libdnf5/module/module_query.hpp
include/libdnf5/module/nsvcap.hpp
libdnf5/module/module_dependency.cpp
libdnf5/module/module_profile.cpp
libdnf5/module/module_query.cpp
libdnf5/module/nsvcap.cpp

This PR is into a new dnf5-5.2.0.0 branch to keep the main branch ABI compatible.

Add pImpl to `libdnf5::module::*` classes

---

libdnf5/rpm/solv/goal_private.cpp

First gather all unique providers of installonly provides and then
handle each set of packages (providers) with the same name.
Previously the handling was done per provide, this could result in repeated
handling of a single package if it provided multiple installonly
provides. Such as `kernel` and `installonlypkg(kernel)`.
This could also lead to problems when multiple versions of installonly
pkgs didn't have the same installonly provides.
https://bugzilla.redhat.com/show_bug.cgi?id=2263675
Test: https://github.com/rpm-software-management/ci-dnf-stack/pull/1454

When limiting installonly pkg handle each provider just once

---

dnf5daemon-server/callbacks.cpp
dnf5daemon-server/callbacks.hpp
dnf5daemon-server/dbus.hpp
dnf5daemon-server/dbus/interfaces/org.rpm.dnf.v0.rpm.Rpm.xml
include/libdnf5/rpm/transaction_callbacks.hpp
libdnf5/rpm/transaction.cpp

There is currently no way for dnf5daemon user to find out when the rpm
transaction began and when it finished.
The change introduces two new callbacks on rpm::TransactionCallbacks class:
TransactionCallbacks::before_begin(int total)
executed right before the rpm transaction is run
parameter total contains number of elements in the rpm transaction.
TransactionCallbacks::after_complete(bool success)
executed right after the rpm transaction finished
parameter success indicates whether the transaction finished successfully.
These callbacks are then used in dnf5daemon-server to send respective signals
to the client.
For https://github.com/rpm-software-management/dnf5/issues/1189
Replaces https://github.com/rpm-software-management/dnf5/pull/1250
Originally opened on the main branch, but since …

rpm: New callbacks to wrap whole rpm transaction

---

dnf5-plugins/automatic_plugin/automatic.cpp

Network availability check uses remote repository URLs. If there is no
remote repository, skip the check.
This speeds up `dnf5 automatic` CI tests greatly because it skips
default 60 seconds timeout.

automatic: Skip network availability check without remote repo

---

include/libdnf5/base/base.hpp
libdnf5/base/base.cpp
libdnf5/base/base_impl.hpp
libdnf5/base/goal.cpp
libdnf5/module/module_db.cpp
libdnf5/repo/repo_sack.cpp

Test update: https://github.com/rpm-software-management/ci-dnf-stack/pull/1465

Move all `libdnf5::Base` members to pImpl and remove deprecated

---

dnf5/commands/clean/clean.cpp
include/libdnf5/repo/repo_cache.hpp
include/libdnf5/repo/repo_query.hpp
libdnf5/repo/repo_cache.cpp
libdnf5/repo/repo_cache_private.hpp
libdnf5/repo/repo_query.cpp

This PR is into a new dnf5-5.2.0.0 branch to keep the main branch ABI compatible.
I am leaving the interface classes `RepoCallbacks` and `DownloadCallbacks` unmodified.

Add pImpl to `libdnf5::repo::*`

---

dnf5.spec
dnf5daemon-client/CMakeLists.txt
dnf5daemon-server/CMakeLists.txt
dnf5daemon-server/callbacks.cpp
dnf5daemon-server/dbus/interfaces/org.rpm.dnf.v0.Base.xml
dnf5daemon-server/dbus/interfaces/org.rpm.dnf.v0.Goal.xml
dnf5daemon-server/dbus/interfaces/org.rpm.dnf.v0.SessionManager.xml
dnf5daemon-server/dbus/interfaces/org.rpm.dnf.v0.rpm.Repo.xml
dnf5daemon-server/dbus/interfaces/org.rpm.dnf.v0.rpm.Rpm.xml
dnf5daemon-server/services/advisory/advisory.cpp
dnf5daemon-server/services/base/base.cpp
dnf5daemon-server/services/goal/goal.cpp
dnf5daemon-server/services/repo/repo.cpp
dnf5daemon-server/services/rpm/rpm.cpp
dnf5daemon-server/session_manager.cpp

The change makes sure that all dnf5daemon-server methods and signals:
- are documented in <interface>.xml files
- have correct D-Bus signatures
- all their parameters have provided names for better introspection
Fixes: https://github.com/rpm-software-management/dnf5/issues/1246

dnf5daemon: Introspection files revision

---

dnf5-plugins/config-manager_plugin/addrepo.cpp
dnf5-plugins/config-manager_plugin/setopt.cpp
dnf5-plugins/config-manager_plugin/shared.hpp
dnf5-plugins/config-manager_plugin/unsetopt.cpp
dnf5-plugins/config-manager_plugin/unsetvar.cpp

It solves tasks in the https://github.com/rpm-software-management/dnf5/issues/1011 issue except for documentation and does not replace crc32 with library functions.
Requires: https://github.com/rpm-software-management/ci-dnf-stack/pull/1429 adjustment of CI tests. 
Closes: #1011 .

Additional features for config-manager

---

libdnf5/transaction/transaction_sr.cpp

Parsing serialized transaction: format validation.
I will also provide CI tests once have know how the CLI should look like for commands that will use this API.
For: https://github.com/rpm-software-management/dnf5/issues/999

Parsing serialized transaction: format validation

---

dnf5/commands/upgrade/upgrade.cpp
dnf5/shared_options.cpp
doc/commands/upgrade.8.rst

If only `--destdir` is specified the command will download the pkgs to specified directory and then fail because transaction cannot find them (they are not in cache).

upgrade: check that `--destdir` is used only with `--downloadonly`

---

dnf5-plugins/builddep_plugin/builddep.cpp
include/libdnf5/base/goal_elements.hpp
libdnf5/base/goal_elements.cpp
libdnf5/rpm/package_query.cpp

This commit makes a breaking change adding `expand_globs` setting to the `ResolveSpecSetting`.
Related: https://github.com/rpm-software-management/mock/issues/1267
Resolves https://github.com/rpm-software-management/dnf5/issues/1084
Are there any other places where the `expand_globs` setting should be `false`? Or maybe `false` should be the default and the commands that accept pkg specs on the command line should set it to `true` themselves?
WIP since a ci-dnf-stack PR is still on the way.

builddep: Don't try to expand globs in pkg specs

---

dnf5.spec

The necessary pieces are not yet in place for RHEL 11 and this results in conflicts.

Don't set obsoletes < 5 for ELN/RHEL yet

---

dnf5/commands/check-upgrade/check-upgrade.cpp
dnf5/commands/list/list.cpp
libdnf5/rpm/package_query.cpp

Noarch packages can be used to upgrade any binary packages, but not source
packages. Fixes incorrect filter_upgrades() behaviour where src packages
were returned as upgrade candidates for noarch packages.
Tests adjustment: https://github.com/rpm-software-management/ci-dnf-stack/pull/1472

PackageQuery: Source rpms do not upgrade binary ones

---

libdnf5-cli/output/package_info_sections.cpp

This is a hacky workaround for a performance problem with `scols_table_print_range()`. Once the table is large (eg. all pkgs in fedora repo) calling `scols_table_print_range()` for each package is very slow. However we cannot print the whole table at once because it isn't possible to add an empty line into the table to separate the packages.
To workaround this print each package right away after it is added and clear the table. This changes the behavior, the printing is done by `add_section()` and the final call to `print()` is a noop.
This should be reworked for 5.2.0.0 where we can break API.
For: https://github.com/rpm-software-management/dnf5/issues/1251

Workaround slow scols_table_print_range() for pkg info formatting

---

include/libdnf5-cli/argument_parser.hpp
libdnf5-cli/argument_parser.cpp
test/libdnf5-cli/test_argument_parser.cpp

Breaks the `AgumentParser` ABI. But it simplifies its maintainability for the future.
Related to https://github.com/rpm-software-management/dnf5/issues/1025

Argument parser: support repeated positional args, use p_impl, no inline methods

---

dnf5/commands/check-upgrade/check-upgrade.cpp
dnf5/commands/list/info.cpp
dnf5/commands/list/list.cpp
dnf5/commands/repoquery/repoquery.cpp
dnf5/config/usr/share/dnf5/aliases.d/compatibility.conf
dnf5daemon-client/commands/repoquery/repoquery.cpp
include/libdnf5-cli/output/package_info_sections.hpp
include/libdnf5-cli/output/package_list_sections.hpp
include/libdnf5-cli/output/packageinfo.hpp
libdnf5-cli/output/package_info_sections.cpp
libdnf5-cli/output/package_list_sections.cpp
libdnf5-cli/output/package_list_sections_impl.hpp
libdnf5-cli/output/packageinfo.cpp

`scols_table_print_range` is slow when the table is large (when the
table contains info for all available packages). Since we need to print
an empty line between the packages the only option is to print each
package as a separate table.
To achieve that and keep the class compatible with
`package_list_sections` it needed to be changed.
`package_list/info_sections` still take a `PackageSet` when adding a
section, this could be updated to a more general vector of IPackage
which could also be used from dnf5daemon but the sets would require
converting and I am not certain it will be needed.

Update `package_info_sections` not to use `scols_table_print_range`

---

dnf5-plugins/automatic_plugin/transaction_callbacks_simple.cpp
dnf5/context.cpp
dnf5daemon-client/wrappers/dbus_transaction_module_wrapper.hpp
dnf5daemon-server/transaction.cpp
include/libdnf5-cli/output/adapters/transaction_tmpl.hpp
include/libdnf5-cli/output/interfaces/transaction.hpp
include/libdnf5/base/goal_elements.hpp
include/libdnf5/base/transaction_module.hpp
include/libdnf5/transaction/transaction_item_action.hpp
libdnf5-cli/output/transaction_table.cpp
libdnf5/base/goal.cpp
libdnf5/base/log_event.cpp
libdnf5/base/transaction.cpp
libdnf5/base/transaction_module.cpp
libdnf5/base/transaction_module_impl.hpp
libdnf5/rpm/transaction.cpp
libdnf5/transaction/transaction_item_action.cpp

Replacement for https://github.com/rpm-software-management/dnf5/pull/1285 , but opened against the dnf5-5.2.0.0 branch.
The tests are still here: https://github.com/rpm-software-management/ci-dnf-stack/pull/1462

modules: Report switching module streams

---

dnf5/commands/offline/offline.cpp
dnf5/commands/system-upgrade/system-upgrade.cpp
dnf5/include/dnf5/offline.cpp
dnf5/include/dnf5/offline.hpp
doc/commands/system-upgrade.8.rst

Fix a couple issues that came up when writing the system-upgrade and offline tests:
- Fix `system-upgrade download --no-downgrade`
- Print more transaction tables, mainly so the tests can parse them
- Exit cleanly when `dnf5 offline _execute` is run but there is no valid state file. This is important for when DNF 4 is running a system upgrade but DNF 5 is also installed, as dnf5-offline-transaction.service will otherwise interfere with the DNF 4 system-upgrade.
- Clean command now deletes the `/system-update` "magic symlink"
- `system-upgrade download` is now simplified to use more of `main.cpp`'s general transaction flow, but it doesn't print the "Download complete!" message at the end or log a message marked with `DOWNLOAD_FINISHED_ID`.

system-upgrade: bugfixes, output changes

---

dnf5daemon-server/advisory.cpp
doc/dnf_daemon/examples/print_upgrades_with_severities.py

To improve user experience add also complete NEVRAs to returned
packages in advisory collections.

dnfdaemon: Add NEVRA field to advisory packages

---

dnf5/main.cpp

Print to the user relevant hints about what command line options could
be used to fix transaction resolving issues.
It can suggest using --skip-unavailable, --no-best,
--allowerasing, --skip-broken, and --setopt=optional_metadata_types=filelists
Fixes: https://github.com/rpm-software-management/dnf5/issues/548
Fixes: https://github.com/rpm-software-management/dnf5/issues/1131
Because the PR changes the stderr output, some tests need adjustments: https://github.com/rpm-software-management/ci-dnf-stack/pull/1473

dnf5: Print command line hints after resolve failure

---

dnf5.spec
dnf5/bash-completion/dnf5

For: https://bugzilla.redhat.com/show_bug.cgi?id=2223324.
Connected with:
- https://github.com/rpm-software-management/dnf/pull/2070
Related:
- https://github.com/rpm-software-management/dnf5/issues/1057

Prepare bash-completion for switch to dnf5 as the default package manager

---

dnf5/commands/system-upgrade/system-upgrade.cpp
dnf5/commands/system-upgrade/system-upgrade.hpp
dnf5/config/usr/share/dnf5/aliases.d/compatibility.conf
dnf5/main.cpp

Make `dnf5 offline-distrosync` and `dnf5 offline-upgrade` backwards-compatible with DNF 4. There didn't seem to be a way to do this with aliases alone since we need `dnf5 offline-distrosync` and `dnf5 offline-distrosync download` to be aliased to different commands (`dnf5 offline` and `dnf5 distro-sync`, respectively). We also want `dnf5 offline-distrosync --help` to show the help for `dnf5 offline`.
Resolves https://github.com/rpm-software-management/dnf5/issues/1343.
Marked draft until I have a ci-dnf-stack PR ready.

system-upgrade: backwards-compat offline-{upgrade,distrosync}

---

bindings/libdnf5/conf.i
dnf5-plugins/automatic_plugin/config_automatic.hpp
dnf5/commands/repoquery/repoquery.cpp
dnf5/commands/repoquery/repoquery.hpp
dnf5daemon-client/commands/repolist/repolist.cpp
dnf5daemon-client/commands/repolist/repolist.hpp
include/libdnf5/conf/config_main.hpp
include/libdnf5/conf/option.hpp
include/libdnf5/conf/option_enum.hpp
include/libdnf5/repo/config_repo.hpp
libdnf5/conf/config_main.cpp
libdnf5/conf/option.cpp
libdnf5/conf/option_enum.cpp
libdnf5/repo/config_repo.cpp
libdnf5/utils/dnf4convert/config_module.hpp
test/libdnf5/conf/test_option.cpp

In next PRs I would like to add pImpl also to other `Option`* classes.

libdnf5::OptionEnum: remove template, add pImpl

---

dnf5daemon-server/session.cpp

The option is potentially dangerous and can cause dnf5daemon-server to
block on malicious reposdir.

dnf5daemon: Remove reposdir from allowed config overrides

---

dnf5.spec

For: https://bugzilla.redhat.com/show_bug.cgi?id=2216850.
Requires:
- https://github.com/rpm-software-management/dnf/pull/2072
- https://github.com/rpm-software-management/dnf-plugins-core/pull/529
Related:
- https://github.com/rpm-software-management/dnf5/issues/1057

Prepare man pages for switch to dnf5 as the default package manager

---

dnf5daemon-client/commands/group/group_list.cpp
dnf5daemon-client/commands/group/group_list.hpp
dnf5daemon-client/wrappers/dbus_group_wrapper.hpp
dnf5daemon-server/dbus/interfaces/CMakeLists.txt
dnf5daemon-server/dbus/interfaces/org.rpm.dnf.v0.comps.Group.xml
dnf5daemon-server/services/comps/group.cpp
doc/dnf_daemon/dnf5daemon_dbus_api.8.rst

New accepted options:
- with_hidden - boolean, defaults to false
whether include hidden (uservisible=false) groups into output
- scope - string, accepted values "all" (default), "installed",
"available"
- group_with_id - boolean, defaults to true
whether patterns should be matched against group ids
- group_with_name - boolean, defaults to false
whether patterns should be matched against group names
- contains_pkgs - list of strings
only return groups containing given packages
Change in behavior:
- in case the scope is "all" (default), duplicated groups are removed
from the output. Duplicities basically mean that the group is
installed and previously both installed and available groups were
returned.
Also adds comps.Groups interface to the D-Bus API documentation and adjusts …

dnfdaemon: Enhance comps.Group.list() method

---

include/libdnf5/conf/config.hpp
include/libdnf5/conf/option_binds.hpp
include/libdnf5/logger/log_router.hpp
include/libdnf5/logger/memory_buffer_logger.hpp
libdnf5/conf/config.cpp
libdnf5/conf/option_binds.cpp
libdnf5/logger/log_router.cpp
libdnf5/logger/memory_buffer_logger.cpp

I think this could be the last PR for https://github.com/rpm-software-management/dnf5/issues/1025
In my option the rest of the classes are not suitable for pImpl. 
Please let me know if we need to add it on some additional place.

Add pImpl to the remaining various classes

---

libdnf5/base/base.cpp
test/dnf5daemon-server/support.py
test/perl5/libdnf5/rpm/test_package_query.t
test/python3/libdnf5/base_test_case.py
test/python3/libdnf5/tutorial/session/create_base.py
test/ruby/libdnf5/base_test_case.rb
test/shared/base_test_case.cpp
test/shared/test_case_fixture.cpp
test/tutorial/session/create_base.cpp

Loading plugins from host system is risky for both sides.
Closes: https://github.com/rpm-software-management/dnf5/issues/1316

Prevent loading plugins for unittests

---

include/libdnf5/base/base.hpp

The oposit order might lead to incomplete substitotions of repository configurations
Closes: https://github.com/rpm-software-management/dnf5/issues/1374

Add a hint to call base.setup() prior loading repositories

---

dnf5.spec
dnf5daemon-server/dbus/CMakeLists.txt

We should prefer to install DBUS policy configuration files into /usr rather than /etc.

dnf5daemon-server/dbus: Install config files into /usr

---

include/libdnf5/conf/vars.hpp
libdnf5/conf/vars.cpp
test/libdnf5/conf/test_vars.cpp
test/libdnf5/conf/test_vars.hpp

Vars::unset: API method for removing variable

---

dnf5daemon-client/CMakeLists.txt
dnf5daemon-client/commands/repoquery/repoquery.cpp
dnf5daemon-server/CMakeLists.txt
dnf5daemon-server/dbus.hpp
dnf5daemon-server/dbus/interfaces/org.rpm.dnf.v0.rpm.Rpm.xml
dnf5daemon-server/main.cpp
dnf5daemon-server/package.cpp
dnf5daemon-server/package.hpp
dnf5daemon-server/services/comps/group.cpp
dnf5daemon-server/services/goal/goal.cpp
dnf5daemon-server/services/repo/repo.cpp
dnf5daemon-server/services/rpm/rpm.cpp
dnf5daemon-server/services/rpm/rpm.hpp
dnf5daemon-server/session.hpp
dnf5daemon-server/threads_manager.hpp
dnf5daemon-server/utils.cpp
dnf5daemon-server/utils.hpp
doc/dnf_daemon/examples/rpm_list_fd.py

Adds new API `list_fd()` on `Rpm` interface.
This is an alternative to the original Rpm.list() method. It accepts the same 
input arguments and behaves the same way. The difference is that it uses a
file descriptor to transfer package data to the user.
It enables dnfdaemon to bypass D-Bus message size restrictions. The draw-back
is that the client has to implement reading from a pipe and parsing returned
JSON dictionaries with packages.
For: https://github.com/rpm-software-management/dnf5/issues/1139

dnfdaemon: Add new API for requests with large replies

---

CMakeLists.txt

Hidden inline methods will not appear in the export table of a DSO (dynamic shared object) and will not require a PLT indirection when used within the DSO. 
According to the GCC man page:
Enabling  this  option  can have a dramatic effect on load and link times of a DSO as it massively reduces the size of the dynamic export table when the library  makes heavy use of templates.
So:
- it is optimization
- also hides our internal inline methos (Related to https://github.com/rpm-software-management/dnf5/issues/1304
And we can do this because we do not attempt to compare pointers to inline functions or methods where the  addresses  of  the two functions are taken in different shared objects.

Give inline methods hidden visibility by default

---

doc/dnf5.conf.5.rst
libdnf5/base/transaction.cpp

I think this could be helpful for debugging some installer issues - e.g. https://bugzilla.redhat.com/show_bug.cgi?id=2244744

Support RPMTRANS_FLAG_DEPLOOPS

---

libdnf5/base/goal.cpp

Since distro-sync uses `SOLVER_TARGETED` mode we cannot pass in installed packages because if we did updating only a subset of packages would be a valid solution. However in a distro-sync we want to ensure ALL packages are synchronized with the target repository.
This brings dnf5 behavior closer to dnf4.
There is still one difference in the transaction setup, dnf4 doesn't specify the transaction as targeted but thanks to libsolv's `auto-targeting` this should have the same behavior.
For: https://bugzilla.redhat.com/show_bug.cgi?id=2273749
Test: https://github.com/rpm-software-management/ci-dnf-stack/pull/1482

Fix `DISTRO_SYNC_ALL` (distro-sync without arguments, system upgrade)

---

libdnf5/system/state.cpp

The original test for import failed because tmp file cannot be created when target directory is not present.
Closes: https://github.com/rpm-software-management/dnf5/issues/1379

Enable import data from DNF4 for systems without state dir

---

dnf5.spec

Should fix failing nightly testing builds.

spec: Add missing dnf-config-manager.8.gz file

---

dnf5/config/usr/share/dnf5/aliases.d/compatibility.conf

Adds two command aliases present in dnf4:
- `se` for the `search` command
- `if` for the `info` command

config: add search (se) and info (if) aliases

---

dnf5daemon-server/session.cpp
doc/dnf_daemon/dnf5daemon_dbus_api.8.rst

- set a timeout for the user to enter the password (default 25 seconds
seems to be too short)
- catch timeout error - otherwise the error is returned to the client
causing the original call to fail with timeout
For example:
The user invokes the do_transaction() method on the Goal interface. The
first action of the do_transaction handler is to verify that the user is
authorized to run an RPM transaction. If an authentication agent is
available, this may result in prompting the user to enter their
password. If the user ignores the prompt, after a timeout period, the
result should be a "Not authorized" error.
However, without this patch, the result would be a "Method call timed
out," which is misleading. While the user called do_transaction(), the
timeout did not occur at this stage.
For: …

dnfdaemon: Catch timeout during CheckAuthorization

---

test/dnf5-plugins/CMakeLists.txt

The Copr dnf5 plugin is faulty, issue https://github.com/rpm-software-management/dnf5/issues/1317
It uses an uninitialized variable. Because of the random value of this variable, unit tests fail randomly (when it has a value of 0, which is whenever we allow the compiler to initialize memory to 0, or we use clang).
I'm in favor of temporarily disabling the Copr unit tests until the plugin is fixed, so we can re-enable compilation with clang.

Disable unit tests for Copr dnf5 plugin

---

dnf5/main.cpp
include/libdnf5/base/base.hpp
include/libdnf5/plugin/iplugin.hpp
libdnf5/base/base.cpp
libdnf5/base/base_impl.hpp
libdnf5/plugin/plugins.cpp
libdnf5/plugin/plugins.hpp
libdnf5/repo/repo_sack.cpp

`notify_repos_configured` notifies the libdnf5 library that the repositories are configured.  It can be called before `load_repos`. The libdnf5 library can then call plugins `post_repos_configured` hook that can make final adjustments to the repositories configuration. In case the `notify_repos_configured` method was not explicitly called, it is called automatically at the beginning of the `load_repos` method.
Closes #1404 
Also adds hooks:
`repos_loaded`, `pre_add_cmdline_packages`, and `post_add_cmdline_packages`

Base: `notify_repos_configured` and `are_repos_configured methods`, libdnf5 plugins `post_repos_configured` hook

---

dnf5/include/dnf5/iplugin.hpp
dnf5/include/dnf5/version.hpp
dnf5/iplugin.cpp

Related https://github.com/rpm-software-management/dnf5/issues/1025
And increases the dnf5 plugin API version to 2.0.

dnf5 IPlugin: Do not use inline methods on API

---

include/libdnf5/plugin/iplugin.hpp
include/libdnf5/version.hpp
libdnf5-plugins/actions/actions.cpp
libdnf5-plugins/python_plugins_loader/python_plugins_loader.cpp
libdnf5-plugins/rhsm/rhsm.cpp
libdnf5/plugin/iplugin.cpp
libdnf5/plugin/iplugin_private.hpp
libdnf5/plugin/plugins.cpp

Related https://github.com/rpm-software-management/dnf5/issues/1025
Please merge PR https://github.com/rpm-software-management/dnf5/pull/1405 first.
PR introduces pImpl and IPluginData.
IPluginData was introduced to allow future changes to the passed dataset without changing the API and ABI.
IPluginData now represents Base. But in the future it may be a struct/class.
And increases the libdnf5 plugin API version to 2.0.

Libdnf5 plugins: API and ABI stability improve, pImpl, IPluginData

---

.github/workflows/package-build.yml

Re-enable clang builds after API changes

---

doc/changes.rst
doc/dnf5.8.rst
doc/dnf5.conf.5.rst
doc/dnf5_plugins/automatic.8.rst

Related to #1290.
Closes #940.

doc: Review of DNF4 vs DNF5 CLI and configuration changes

---

libdnf5/logger/null_logger.cpp

I forgot to include the "null_loger.cpp" file in the previous PR (Loggers API: unify, explicit ctors, non-inline methods, use p_impl). The problem only becomes apparent when someone uses this logger. That's why it passed.

Loggers: Fix: Add missing "null_loger.cpp" file

---

dnf5/include/dnf5/context.hpp
dnf5/main.cpp

These command line arguments were added some time ago, but the handler logic has not been implemented.
Now these arguments enable/disable loading of listed libdnf5 library plugins.
Closes #1422.

[DNF5] Implement `--enable-plugin` and `--disable-pluin`

---

libdnf5/base/goal.cpp
libdnf5/rpm/solv/goal_private.cpp
libdnf5/rpm/solv/goal_private.hpp

It also renames `add_transaction_group_installed` since it is now used to store removed packages as well.
I have discovered this while working on `undo` command, when undoing a `group remove` transaction the packages need to have a `group` reason.

Set `group` reason for packages removed by a group removal

---

dnf5.spec

Related:
- https://github.com/rpm-software-management/dnf/pull/2082
- https://github.com/rpm-software-management/dnf-plugins-core/pull/531

Prepare for switch of dnf5 in Rawhide

---

bindings/libdnf5/base.i
bindings/libdnf5/plugin.i
include/libdnf5/base/base.hpp
include/libdnf5/plugin/iplugin.hpp
include/libdnf5/plugin/plugin_info.hpp
include/libdnf5/plugin/plugin_version.hpp
libdnf5-plugins/actions/actions.cpp
libdnf5-plugins/python_plugins_loader/python_plugins_loader.cpp
libdnf5-plugins/rhsm/rhsm.cpp
libdnf5/base/base.cpp
libdnf5/base/base_impl.hpp
libdnf5/plugin/plugin_info.cpp
libdnf5/plugin/plugin_info_impl.hpp
libdnf5/plugin/plugins.cpp

Introduces the `Base::get_plugins_info` method, which returns a list of information about plugins found during `Base::setup`.
It also introduces the `plugin::PluginInfo` class, which provides information about one libdnf5 plugin.
Closes #1429
Related to #1335

[libdnf5 API] Base::get_plugins_info

---

dnf5.spec

Another bit needed for switching dnf5 in Rawhide. We need to ensure there are no multiple providers of the dnf configuration on the system simultaneously.
Related: https://github.com/rpm-software-management/dnf5/pull/1444.

spec: Add conflict with the old provider of dnf.conf

---

dnf5.spec

We relocated the plugin man pages provided by `dnf-plugins-core` to a different location, avoiding conflicts with `dnf5`, starting with `dnf-plugins-core` version 4.7.0. As a result, we need to require this upgrade; otherwise, the man page files will conflict.
Closes https://github.com/rpm-software-management/dnf5/issues/1383.

spec: Add conflict with the former provider of plugin man pages

---

dnf5/context.cpp
dnf5/include/dnf5/context.hpp
dnf5/main.cpp

Print a warning if no libdnf plugin with a matching name is found.
Also moves `Context::libdnf5_plugins_enablement` to `Impl` and adds getters `Context::get_libdnf_plugins_enablement()`. I overlooked it when I created the Impl.
Closes #1431
Depends on issue #1429. PR #1430 needs to be merged first, then I'll rebase this PR.

[DNF5] --enable-plugin and --disable-pluin: no match found message 

---

doc/dnf5.8.rst

Ammend dnf5(8) manual regarding loading plugins and distinguish between library and appliacatino plugins.
Fixes: #1445
I also wanted to document a default value for DNF5_PLUGINS_DIR, but the value depends on how the build is configured (/usr/lib64/…, or /usr/lib/…, or /usr/local/…). However, I found that current documentation does not undergo a variable substitution. So I left it out.

doc: Add enviroment variables and clarify options for loading the plugins

---

dnf5/commands/repoquery/repoquery.cpp
doc/commands/repoquery.8.rst
doc/misc/specs.7.rst

File provides are not only present in file provides, but also in normal provides. The code did not searched for file provides when filter_provide() already gained a result. It means that for some glob pattern, dnf5 provides incomplete results without the patch.
Closes: https://github.com/rpm-software-management/dnf5/issues/1153
CI-test: https://github.com/rpm-software-management/ci-dnf-stack/pull/1491

Add file search result for repoquery --whatprovides

---

dnf5-plugins/copr_plugin/copr_repo.hpp
test/dnf5-plugins/CMakeLists.txt

This was the last occurrence causing the attribute to remain uninitialized after calling any of the constructors.
This also reverts commit 2b6b53f7a2f71c86355b9f4d8cb2ae7f4e2ca02b.
Fixes: #1317

copr: the dnf5 copr enable sets CoprRepoPart.enabled = true

---

dnf5/commands/offline/offline.cpp
dnf5/commands/offline/offline.hpp
dnf5/context.cpp
dnf5/include/dnf5/offline.hpp
dnf5/shared_options.cpp

System-upgrade was broken by https://github.com/rpm-software-management/dnf5/commit/5f8b76ad7e0faa5c5b151e4301417f004bc4470e, since RPMs of serialized transactions are now expected to be stored in a single flat directory (like that created by `dnf5 download --destdir ./packages`) rather than the directory structure used by the DNF cache (in `/path/to/repository-cachedir/packages`).
We would like to set `destdir` to download the packages to a single flat directory, but then we can't test the transaction as usual because of the limitation described in https://github.com/rpm-software-management/dnf5/pull/1301. So instead, we serialize the transaction without testing it, then build a new "test transaction" from the serialized transaction and test that. This solution may seem like a hack, but …

system-upgrade: Fix + adapt to new transaction serialization format

---

bindings/libdnf5/base.i
bindings/libdnf5/common.i
bindings/libdnf5/repo.i
bindings/libdnf5/rpm.i
test/python3/libdnf5/common/test_struct_attributes.py

This aligns with existing attributes for options in the configuration classes.
It should also resolve the issues breaking our libdnf5 clients, as the struct wrappers change was the only thing removed from the Python public API without prior deprecation.

bindings: Add Python attributes for structs

---

dnf5daemon-client/wrappers/dbus_goal_wrapper.cpp
dnf5daemon-client/wrappers/dbus_goal_wrapper.hpp
dnf5daemon-server/dbus.hpp
dnf5daemon-server/services/goal/goal.cpp
include/libdnf5-cli/output/adapters/transaction_tmpl.hpp
include/libdnf5-cli/output/interfaces/transaction.hpp
include/libdnf5/base/transaction.hpp
libdnf5-cli/output/transaction_table.cpp
libdnf5/base/solver_problems.cpp
libdnf5/base/solver_problems_internal.hpp
libdnf5/base/transaction.cpp
libdnf5/base/transaction_impl.hpp

Resolves: https://github.com/rpm-software-management/dnf5/issues/359

cli: Add skipped packages to the transaction table

---

libdnf5/base/log_event.cpp

The leading message glued paragraphs and a missing space in _("Unable to resolve argument '{}':{}") was confusing for the translators.
A continuations of the message also did not suport plural forms.
Both issues are fixed with this patch. The singular form will never be used, but the many plural ones will do.
Fixes: #1480

i18n: Improve formatting an error message for multiple streams

---

include/libdnf5/rpm/package_query.hpp
libdnf5/rpm/package_query.cpp

Add/fix documentation for rpm::PackageQuery methods

---

libdnf5/base/log_event.cpp

In some languages a correct translation of that message depends on the first argument ("No {}"). This patch removes that argument by spelling all four possible values in full text.
Fixes: #1471

i18n: Unwind "No {} to remove for argument: {}"

---

libdnf5-cli/output/transactionlist.cpp

dnf4 also counts them.
(It is required for enabling `undo` tests for dnf5.)

`history list`: count also groups and envs in total `Altered`

---

doc/libdnf5_plugins/actions.8.rst
libdnf5-plugins/actions/actions.cpp

PR https://github.com/rpm-software-management/dnf5/pull/1405 added new hooks to the ibdnf5 plugin API:
`repos_configured`, `repos_loaded`, `pre_add_cmdline_packages`, `post_add_cmdline_packages`
This PR extends the actions plugin to support these new hooks.
Plugin version is set to 1.0.0.
Closes #1455

[libdnf5] Actions plugin: Add hooks `repos_configured`, `repos_loaded`, `pre/post_add_cmdline_packages`

---

dnf5/commands/repoquery/repoquery.cpp

It can work just fine with only installed packages.
This was also a change in comparison to dnf4 (option `--resolve` didn't load available repos).
https://bugzilla.redhat.com/show_bug.cgi?id=2279959

Option `--providers-of` doesn't require available repos

---

doc/changes.rst
doc/misc/caching.7.rst

Improve docs regarding the keepcache option and download command

---

dnf5-plugins/needs_restarting_plugin/needs_restarting.cpp

`current` is a reference to the last item of the `stack` vector, which
is being used after being invalidated by the `stack.pop_back()` call.
Resolves: https://github.com/rpm-software-management/dnf5/pull/1477

needs_restarting: Fix invalid reference usage

---

dnf5/config/usr/share/dnf5/aliases.d/compatibility.conf

For compatibility with the download plugin in dnf4:
https://github.com/rpm-software-management/dnf-plugins-core/blob/a054dcbd64db7743b0af78ac8e06104c4bd6be6e/plugins/download.py#L52-L53

download: add `--source` alias for `--srpm`

---

dnf5-plugins/automatic_plugin/automatic.cpp
dnf5-plugins/automatic_plugin/config/usr/share/dnf5/dnf5-plugins/automatic.conf
dnf5.spec
doc/changes.rst
doc/dnf5_plugins/automatic.8.rst

- changes the config files reading behavior - /usr/share/dnf5/dnf5-plugins/automatic.conf is always read to set the defaults, /etc/dnf/dnf5-plugins/automatic.conf is then used for host-specific overrides
- fixes errors in the documentation
- enhances documentation of changes between dnf4 and dnf5
- ship default configuration file in /usr/share/dnf5/dnf5-plugins/automatic.conf
Resolves: https://github.com/rpm-software-management/dnf5/issues/1289
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2279257
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2279258

automatic: Fix documentation and ship config file

---

libdnf5/rpm/transaction.cpp

Correct localization depends on the first argument. This patch fixes it by spelling the complete sentence.
Note: libdnf_assert(), libdnf_throw_assertion() cannot be internationalized because undelying fmt::format() requires a costexpr. Hence the formatting string cannot be computed at runtime.
Fixes #1488

i18n: Unwind "Cannot {} package \"{}\"" message

---

include/libdnf5/base/goal_elements.hpp
libdnf5/base/solver_problems.cpp
libdnf5/base/transaction.cpp
libdnf5/rpm/solv/goal_private.cpp

Information about the repository is important for debugging, especially
for systems where packages may originate from different repositories.
Resolves: https://github.com/rpm-software-management/dnf5/issues/1123
Tests adjustments: https://github.com/rpm-software-management/ci-dnf-stack/pull/1500

base: Add repository to solver problem messages

---

bindings/libdnf5/conf.i
dnf5/commands/repo/repo_info.cpp
include/libdnf5/conf/config_main.hpp
include/libdnf5/conf/option_string_list.hpp
include/libdnf5/repo/config_repo.hpp
libdnf5/conf/config_main.cpp
libdnf5/conf/config_utils.hpp
libdnf5/conf/option_string_list.cpp
libdnf5/repo/config_repo.cpp
test/libdnf5/conf/test_option.cpp
test/libdnf5/conf/test_option.hpp
test/python3/libdnf5/conf/test_option.py

Introducing `OptionStringAppendList` and `OptionStringAppendSet` classes
for append options.
The current implementation of append options is flawed because it requires
the options to be set in ascending order of priority for proper 
functionality. This is necessary for the resetting mechanism using an empty
item to work correctly. However, in dnf5, options are not processed
strictly in priority order. For instance, command line options like
`--exclude` are processed before the configuration files, despite having a
higher priority than config files.
The new classes accumulate all setting attempts and only process them in 
priority order when the option value is needed.
Resolves: https://github.com/rpm-software-management/dnf5/issues/1331

conf: New classes for append options

---

dnf5daemon-server/dbus/interfaces/org.rpm.dnf.v0.rpm.Rpm.xml
dnf5daemon-server/package.cpp
dnf5daemon-server/package.hpp
doc/dnf_daemon/examples/rpm_list_fd.py

Hello. I'm trying to develop a desktop application and using the capabilities of dnfdaemon, I came across the lack of a really useful buildtime attribute. Without it, I will not be able to correctly and quickly separate packages by date and recommend recent updates. I have added small changes that work on my stand. Now I can get this attribute by specifying it in package_attrs when accessing dbus methods, but I'm not completely sure that I won't need to change it somewhere else.

dnf5daemon: The buildtime attribute has been added to the package_attrs option

---

libdnf5/base/transaction.cpp
test/libdnf5/base/test_transaction.cpp
test/python3/libdnf5/base/test_transaction.py

DNF5 informs about number of packages that signature was not verified, but without any additional detail. The ID of repository provides a good hint for user why the check was skipped.
Closes: https://github.com/rpm-software-management/dnf5/issues/1311
Requires CI modification: https://github.com/rpm-software-management/ci-dnf-stack/pull/1498

Enhance warning about RPMs that were not validate by RPM

---

dnf5-plugins/builddep_plugin/builddep.cpp
dnf5/commands/clean/clean.cpp
dnf5/commands/distro-sync/distro-sync.cpp
dnf5/main.cpp
doc/commands/distro-sync.8.rst
include/libdnf5-cli/exception.hpp
include/libdnf5/conf/const.hpp
include/libdnf5/utils/locker.hpp
libdnf5/base/transaction.cpp
libdnf5/utils/locker.cpp

Using the existing RPM lock file functionality.
There are a hard-coded list of commands that are not allowed to run without superuser privileges. Then `assumeno` and `downloadonly` options are taken into account. Lastly, we check if provided command has defined the `store` option which should be defined for all transactional commands and therefore it should mean a need for elevated privileges.
For: #849.
Successor of: #1504.

Implementation of unified privileges checking for CLI commands

---

dnf5.spec

- /usr/lib/sysimage/dnf was renamed to /usr/lib/sysimage/libdnf5
- added /usr/lib/sysimage/libdnf5/comps_groups directory
- added /usr/lib/sysimage/libdnf5/offline directory
- added /etc/dnf/versionlock.toml config file
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2284612

spec: Fix files and directories ownership

---

dnf5/commands/check-upgrade/check-upgrade.cpp
dnf5/commands/check-upgrade/check-upgrade.hpp
dnf5/commands/upgrade/upgrade.cpp
doc/commands/check-upgrade.8.rst
doc/commands/upgrade.8.rst

It is required for a feature parity with upgrade command where the option is already available.
Related: https://issues.redhat.com/browse/RHEL-38804
CI: https://github.com/rpm-software-management/ci-dnf-stack/pull/1511

Add --minimal option for check-ugrade command

---

dnf5/commands/repo/repo_list.cpp
dnf5/context.cpp
dnf5/include/dnf5/context.hpp
dnf5/include/dnf5/shared_options.hpp
dnf5/shared_options.cpp
include/libdnf5-cli/output/repolist.hpp
libdnf5-cli/CMakeLists.txt
libdnf5-cli/output/repolist.cpp

- Created shared `--json` option for requesting output in JSON format
- Implementation for `repo list` command
For: https://github.com/rpm-software-management/dnf5/issues/867.

repolist: Implement JSON output

---

dnf5/commands/repo/repo_info.cpp
dnf5/context.cpp
dnf5/main.cpp
include/libdnf5-cli/output/repo_info.hpp
libdnf5-cli/output/repo_info.cpp

Turn on `quiet` mode when `--json` is requested. Also fixed suppressing repository download progress when `quiet` mode is turned on.
For: #867.

repoinfo: Implement JSON output

---

dnf5/commands/offline/offline.cpp
dnf5/commands/offline/offline.hpp
dnf5/commands/system-upgrade/system-upgrade.hpp
dnf5/context.cpp
dnf5/include/dnf5/offline.hpp
dnf5/offline.cpp
include/libdnf5/transaction/offline.hpp
libdnf5/transaction/offline.cpp

We will need to share the code also with dnf5daemon-server to support
offline upgrades using D-Bus API.
For: https://bugzilla.redhat.com/show_bug.cgi?id=2124503

Move offline from dnf5 to libdnf5

---

include/libdnf5/base/goal_elements.hpp
libdnf5/CMakeLists.txt
test/CMakeLists.txt
test/libdnf5-cli/CMakeLists.txt
test/libdnf5/CMakeLists.txt
test/shared/CMakeLists.txt

Some unit tests use private symbols that are not exported from libdnf5.so shared library.
Therefore, a static version of the libdnf5 library is built in which all symbols are available. Unit tests that need private symbols use the static library.
Please merge after https://github.com/rpm-software-management/dnf5/pull/1307 .

Build libdnf5 static library, re-enable unit tests that use hidden (private) libdnf5 symbols

---

dnf5daemon-server/dbus/interfaces/org.rpm.dnf.v0.rpm.Rpm.xml
dnf5daemon-server/services/rpm/rpm.cpp
dnf5daemon-server/services/rpm/rpm.hpp
dnf5daemon-server/threads_manager.hpp
doc/dnf_daemon/examples/rpm_list_fd.py

The list_fd() method of the Rpm interface uses a unique transfer_id to
identify which particular file descriptor transfer has finished.
Previously, it was the client's responsibility to pass this unique
identifier to the server in the list_fd() method call. With this patch,
the identifier is generated on the server side, simplifying the method's
usage for clients.
Resolves: https://github.com/rpm-software-management/dnf5/issues/1493

daemon: Generate transfer_id on server side

---

dnf5-plugins/builddep_plugin/CMakeLists.txt

The plugin uses "libdnf5::utils::string::split" function.

Fix: dnf5 builddep plugin: Link with "common"

---

dnf5.spec
dnf5/config/usr/share/dnf5/aliases.d/compatibility-plugins.conf

Since the `build-dep` alias has been present in dnf4 and is still used by some teams, let's keep it in dnf5 as well.
Closes: #1528.

builddep: Add build-dep alias

---

doc/changes.rst
doc/commands/history.8.rst
libdnf5/base/goal_elements.cpp
libdnf5/base/log_event.cpp

I chose not to add the context messages for translators for now (https://github.com/rpm-software-management/dnf5/issues/1544) but I can add them if required.

`undo` command man page and translations

---

dnf5/commands/advisory/advisory_list.cpp
dnf5/commands/advisory/advisory_list.hpp
include/libdnf5-cli/output/advisorylist.hpp
libdnf5-cli/output/advisorylist.cpp

Similar to the repolist --json output, do it for listing advisories that apply to the system ("dnf advisory list") as well as for the references currently supported Bugzilla and CVE types of references.
(examples edited as of 417cb70e248cfe938de60a7bacc13ba3b5257ca6)
Example of advisory list --json:
```json
[
{
"name":"FEDORA-2024-143f0443e1",
"type":"unspecified",
"severity":"None",
"nevra":"yum-4.19.2-1.fc40.noarch",
"buildtime":"2024-04-19 21:20:20"
},
{
"name":"FEDORA-2024-1e8a70c30e",
"type":"enhancement",
"severity":"None",
"nevra":"zstd-1.5.6-1.fc40.aarch64",
"buildtime":"2024-04-19 21:20:20"
}
]
```
Example of advisory list --with-bz --json:
```json
[
{
"advisory_id":"FEDORA-2024-b05fbc1127",
"advisory_type":"enhancement",
"advisory_severity":"enhancement", …
```

Add JSON output to advisory list

---

doc/tutorial/install-build-deps.rst

The dnf5-testing-nightly is the official nightly now, dnf5-unstable is not maintained anymore.

docs: Update nightly copr repo name

---

doc/libdnf5_plugins/actions.8.rst
libdnf5-plugins/actions/actions.cpp

Argument `${conf.<repoid_pattern>.<option_name>[=<value_pattern>]}` is substituted by a list of "repoid.option=value" pairs for the matching repositories. Pairs are separated by ',' character. The ',' character in the value is replaced by escape sequence "\x2C".
The input `repoid_pattern` - is the repository id and can contain globs.
If `value_pattern` is used, only pairs with the matching value are listed. The `value_pattern` can contain globs.
Output line format for setting repository option:
`conf.<repoid_pattern>.<option_name>=<value>` - sets the value of option `option_name` for all matching repositories.
The `repoid_pattern` - is repository id and can contain globs.
Closes #1345

[libdnf, actions plugin] Support get/set repositories options, ver 1.1.0

---

dnf5/main.cpp

Keeping the last message something abou scriptlets is not clear message that everything passed correctly and program was terminated correctly. The commit uses the same message like DNF4. Contrary to DNF4, this commit does not add Complete! message when there is anything to perform - no transaction table.
Closes: https://github.com/rpm-software-management/dnf5/issues/613

Add "Complete!" message after succesfull transaction

---

dnf5/commands/debuginfo-install/debuginfo-install.cpp
dnf5/commands/debuginfo-install/debuginfo-install.hpp
dnf5/main.cpp
doc/changes.rst
doc/commands/debuginfo-install.rst
include/libdnf5/base/goal.hpp
include/libdnf5/base/goal_elements.hpp
include/libdnf5/repo/repo_sack.hpp
libdnf5/base/goal.cpp
libdnf5/base/goal_elements.cpp
libdnf5/repo/repo_sack.cpp

- Documentation
- Reporting when binary RPM does not have available debug package
Tests: [Enable several tests for debuginfo-install command](https://github.com/rpm-software-management/ci-dnf-stack/pull/1523)
Closes: https://github.com/rpm-software-management/dnf5/issues/846

Debuginfo-install command

---

.packit.yaml
CMakeLists.txt
dnf5-plugins/automatic_plugin/automatic.cpp
dnf5/CMakeLists.txt
dnf5/main.cpp
include/libdnf5-cli/CMakeLists.txt
include/libdnf5/CMakeLists.txt
include/libdnf5/base/base.hpp
include/libdnf5/base/goal.hpp
include/libdnf5/repo/repo.hpp
libdnf5-cli/CMakeLists.txt
libdnf5/CMakeLists.txt
libdnf5/base/base.cpp
libdnf5/base/base_impl.hpp
libdnf5/base/goal.cpp
libdnf5/base/transaction.cpp
libdnf5/base/transaction_impl.hpp
libdnf5/repo/repo.cpp
libdnf5/repo/repo_downloader.cpp
libdnf5/repo/repo_sack.cpp
libdnf5/system/state.cpp
libdnf5/system/state.hpp
libdnf5/utils/dnf4convert/dnf4convert.cpp
libdnf5/utils/dnf4convert/dnf4convert.hpp
test/libdnf5/module/test_module.cpp
test/libdnf5/module/test_module.hpp
test/libdnf5/repo/test_repo.cpp
test/libdnf5/system/test_state.cpp
test/shared/utils.hpp

For: https://github.com/rpm-software-management/dnf5/issues/1031
It also adds a copr build packit job to build with modules disabled to ensure the build keeps working.

Implement conditional compilation `-DWITH_MODULEMD=OFF`

---

dnf5/commands/history/history.cpp
dnf5/commands/history/history_rollback.cpp
dnf5/commands/history/history_rollback.hpp
include/libdnf5/base/goal_elements.hpp
libdnf5/base/goal.cpp
libdnf5/base/goal_elements.cpp
libdnf5/base/log_event.cpp
libdnf5/transaction/transaction_merge.cpp
libdnf5/transaction/transaction_merge.hpp
test/libdnf5/transaction/test_transaction_merge.cpp
test/libdnf5/transaction/test_transaction_merge.hpp
test/shared/utils.hpp

Merging is used to revert multiple transactions to achieve a rollback.
It includes extensive unit tests for merging various combinations of actions.

Add history rollback command and transaction merging

---

dnf5/context.cpp

If the path to the local package was specified absolutely (starting with '/'), filelists download was triggered.
Now, as in `Goal`, DNF5 checks if the path ends with the ".rpm" suffix. If it does, it is treated as the path to the local RPM package and filelists download is not triggered.
Closes: https://github.com/rpm-software-management/dnf5/issues/1577

Fix DNF5: Don't trigger filelists download if abs path to local RPM

---

doc/best_practices/index.rst
doc/best_practices/symbol_visibility.rst

Closes: https://github.com/rpm-software-management/dnf5/issues/1542

Documentation: ABI: Defining public (exported) symbols

---

dnf5/commands/offline/offline.cpp
dnf5daemon-client/commands/command.cpp
dnf5daemon-client/commands/command.hpp
dnf5daemon-client/commands/distro-sync/distro-sync.cpp
dnf5daemon-client/commands/distro-sync/distro-sync.hpp
dnf5daemon-client/commands/downgrade/downgrade.cpp
dnf5daemon-client/commands/downgrade/downgrade.hpp
dnf5daemon-client/commands/install/install.cpp
dnf5daemon-client/commands/install/install.hpp
dnf5daemon-client/commands/reinstall/reinstall.cpp
dnf5daemon-client/commands/reinstall/reinstall.hpp
dnf5daemon-client/commands/remove/remove.cpp
dnf5daemon-client/commands/remove/remove.hpp
dnf5daemon-client/commands/shared_options.cpp
dnf5daemon-client/commands/shared_options.hpp
dnf5daemon-client/commands/upgrade/upgrade.cpp
dnf5daemon-client/commands/upgrade/upgrade.hpp
dnf5daemon-server/dbus.hpp
dnf5daemon-server/dbus/interfaces/org.rpm.dnf.v0.Goal.xml
dnf5daemon-server/dbus/interfaces/org.rpm.dnf.v0.Offline.xml
dnf5daemon-server/services/goal/goal.cpp
dnf5daemon-server/services/offline/offline.cpp
dnf5daemon-server/services/offline/offline.hpp
dnf5daemon-server/session.cpp
dnf5daemon-server/session.hpp

Adds support for "offline" option to Goal::do_transaction() dbus API method.

dnfdaemon: Support to run transactions offline

---

doc/dnf5.conf.5.rst
libdnf5/base/goal.cpp
libdnf5/base/transaction.cpp
libdnf5/transaction/transaction.cpp
libdnf5/transaction/transaction_sr.cpp
libdnf5/transaction/transaction_sr.hpp
test/libdnf5/transaction/test_transaction_merge.cpp
test/shared/utils.hpp

This information is stored in system state for each group and is used during group upgrade.

TransactionReplay: handle group package types

---

dnf5/commands/history/history_store.cpp
libdnf5/transaction/transaction.cpp

For: https://github.com/rpm-software-management/ci-dnf-stack/pull/1527

Improvements and fixes for storing transactions

---

dnf5/context.cpp
include/libdnf5/base/transaction.hpp
libdnf5/base/transaction.cpp
libdnf5/base/transaction_impl.hpp
libdnf5/repo/package_downloader.cpp

Offline transactions now copy also local (command line repo) packages to the
cache.
Changes:
f30fd653 (Marek Blaha, 2 hours ago)
dnf5: Offline transactions work with local rpm files
9ab4e873 (Marek Blaha, 2 hours ago)
package_downloader: Handle local files
Local packages are not passed to librepo for download, but directly copied
to the destination directory.
74e01778 (Marek Blaha, 7 hours ago)
transaction: Flag whether download local packages
By default the transaction during the `download()` call does not copy local
packages to the destination directory. These packages are used directly
from their original location. For some use-cases (like offline transaction
involving the command line repo packages) we need to copy them to the
package cache.
Resolves: …

Make offline transactions work with local rpm files

---

doc/commands/repo.8.rst

While this example isn't for the `repo` command it could be useful to users looking into the man page.
For: https://github.com/rpm-software-management/dnf5/issues/1213

Add an example how to disable repo to `repo` command man page

---

dnf5daemon-client/commands/clean/clean.cpp
dnf5daemon-client/commands/clean/clean.hpp
dnf5daemon-client/commands/repoquery/repoquery.cpp
dnf5daemon-client/main.cpp
dnf5daemon-server/dbus/interfaces/org.rpm.dnf.v0.Base.xml
dnf5daemon-server/services/base/base.cpp
dnf5daemon-server/services/base/base.hpp

Changes:
39375118 (Marek Blaha, 46 seconds ago)
dnfdaemon-client: Clean command implemetation
70080460 (Marek Blaha, 20 hours ago)
dnfdaemon: D-Bus API for cleaning caches
Implements `clean()` method on `Base` interface to clean requested types of
caches. Supported types are "all", "packages", "metadata", "dbcache", and
also "expire-cache" for marking repository metadata expired.
Resolves: https://github.com/rpm-software-management/dnf5/issues/1179

dnfdaemon: implement D-Bus API for cleaning caches

---

doc/commands/environment.8.rst
doc/commands/group.8.rst
doc/commands/install.8.rst

This is not meant to stop implementing a nicer solution, but at least add some documentation on how it currently is.
I would be very happy to get the dnf-4 behaviour back, where `group` meant both env and group.
Related to #724 and #1559

Add some docs about environments

---

dnf5-plugins/automatic_plugin/emitters.cpp

When "dnf5 automatic" was configured to send e-mails via SMTP ("emit_via = email" in automatic.conf), it sometimes crashed:
#0  0x00007ff7fb955184 __memcpy_avx_unaligned_erms (libc.so.6 + 0x147184)
#1  0x00007ff7fb873bd4 fmemopen_read (libc.so.6 + 0x65bd4)
#2  0x00007ff7fb875813 _IO_file_underflow@@GLIBC_2.2.5 (libc.so.6 + 0x67813)
#3  0x00007ff7fb877e45 _IO_default_xsgetn (libc.so.6 + 0x69e45)
#4  0x00007ff7fb869a40 _IO_fread (libc.so.6 + 0x5ba40)
#5  0x00007ff7faceb1f7 cr_in_read (libcurl.so.4 + 0x541f7)
#6  0x00007ff7facf8608 cr_eob_read (libcurl.so.4 + 0x61608)
#7  0x00007ff7facf0f20 Curl_client_read (libcurl.so.4 + 0x59f20)
#8  0x00007ff7facf103d Curl_req_send_more (libcurl.so.4 + 0x5a03d)
#9  0x00007ff7fad068da Curl_readwrite (libcurl.so.4 + 0x6f8da)
#10 0x00007ff7face6258 …

Fix a use-after-free in EmitterEmail::notify()

---

dnf5.spec

ELF plugins of dnf5-plugins and dnf5-plugin-automatic subpackages link to libdnf and libdnf-cli libraries. Because the libraries come from the same source package, it is desired to pin the plugin subpackages to same release of the libraries subpackages.
This was hinted by rpminspect and already partially implemented in commit 97cdbe57c34259a0e0dc87431ac7c3e9a396aba7 ("Add explicit package version for libdnf5-cli").
An example of rpminspect failure <https://artifacts.dev.testing-farm.io/9c72a529-5c4b-4ff1-bf4b-21dc5403ff8d/>.

spec: Stricten a dependency on DNF libraries in plugin subpackages

---

dnf5/context.cpp
include/libdnf5-cli/progressbar/progress_bar.hpp
libdnf5-cli/progressbar/progress_bar.cpp

Changes:
d1ffe89f (Marek Blaha, 9 minutes ago)
dnf5: Reduce the noise around running scriptlets
If the scriptlet finishes successfully, do not print the
"Running scriptlet..." / "Stop scriptlet..." pair of messages in the 
transaction progress bar.
The "Running scriptlet" message is displayed during the scriptlet execution
to inform the user that a time-consuming operation is in progress. If the
scriptlet completes successfully, the message is removed. If it fails, the
message remains, and an error/warning message and the "Stop scriptlet"
message is printed to enable debugging.
b3163df9 (Marek Blaha, 12 minutes ago)
cli: Method to drop the last progress bar message
Useful to create "temporary" messages, will be used to reduce the
"Running scriptlet" / "Stop scriptlet" rpm transaction …

Reduce the noise around running scriptlets

---

dnf5-plugins/builddep_plugin/builddep.cpp
doc/dnf5_plugins/builddep.8.rst

This adds the same options used by `rpmbuild`, `mock`, etc. for setting macros to flip build-time conditional switches when parsing spec files.  It provides a consistent interface across related tools.
They are aliases in `rpmbuild`, I'm not sure if there is a better way to accomplish something like that here:
```
rpmbuild alias --with           --define "_with_!#:+     --with-!#:+" \
--POPTdesc=$"enable configure <option> for build" \
--POPTargs=$"<option>"
rpmbuild alias --without        --define "_without_!#:+  --without-!#:+" \
--POPTdesc=$"disable configure <option> for build" \
--POPTargs=$"<option>"
```

builddep: Support the --with/--without options to toggle bconds

---

dnf5daemon-client/commands/system-upgrade/system-upgrade.cpp
dnf5daemon-client/commands/system-upgrade/system-upgrade.hpp
dnf5daemon-client/main.cpp
dnf5daemon-server/dbus/interfaces/org.rpm.dnf.v0.rpm.Rpm.xml
dnf5daemon-server/services/rpm/rpm.cpp
dnf5daemon-server/services/rpm/rpm.hpp
doc/dnf_daemon/examples/print_upgrades_with_severities.py
doc/dnf_daemon/examples/system_upgrade.py

Changes:
c5831738 (Marek Blaha, 72 minutes ago)
doc: Add system-upgrade example using D-Bus API
960882be (Marek Blaha, 6 days ago)
dnf5daemon-client: system-upgrade command
fe4b380f (Marek Blaha, 7 weeks ago)
dnfdaemon: Add system_upgrade() method to Rpm interface
The method fills the goal to perform upgrade of the distribution to the new
release.

dnfdaemon: system-upgrade API and command

---

doc/dnf5.conf.5.rst

For: https://github.com/rpm-software-management/dnf5/issues/1150

Enhance docs for `system_cachedir`, `cachedir` and `logdir`

---

doc/dnf5.conf.5.rst
libdnf5/repo/repo_downloader.cpp
libdnf5/repo/repo_downloader.hpp

Backporting https://github.com/rpm-software-management/libdnf/pull/1662 and https://github.com/rpm-software-management/dnf/pull/2093
Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1501
Since the dnf5 code was identical to dnf4 code the patch is also almost exactly the same (only the names differ like: `get_system_epoch` vs `getSystemEpoch`).

Backport countme bucket calculation fix

---

doc/changes.rst
doc/dnf5.conf.5.rst
doc/misc/caching.7.rst
doc/tutorial/plugins/index.rst

First not every system has user's home directories under /home directory. Second DNF does not use USER variable at all. It uses HOME environment variable with a fallback to a home directory listed in passwd(5) entry.
Alternativelly, we could write "$HOME". But I find "~" shorter, more aesthetic, more understandible, and more correct in case the HOME variable does not exist.

doc: Use ~ instead of /home/$USER

---

dnf5/commands/install/install.cpp
dnf5/commands/remove/remove.cpp
dnf5/commands/upgrade/upgrade.cpp
doc/commands/group.8.rst
doc/commands/install.8.rst
doc/commands/remove.8.rst
doc/commands/upgrade.8.rst
doc/dnf5.conf.5.rst
doc/misc/specs.7.rst

For: https://github.com/rpm-software-management/dnf5/issues/1602
For: https://github.com/rpm-software-management/dnf5/issues/1498
Also adds some clarification to `group_package_types` docs.

doc: fix arguments for install, upgrade and remove

---

doc/dnf5.conf-todo.5.rst
doc/dnf5.conf.5.rst
include/libdnf5/repo/repo.hpp
libdnf5/repo/package_downloader.cpp
libdnf5/repo/repo.cpp
libdnf5/rpm/package.cpp

Changes:
1e83b073 (Marek Blaha, 9 minutes ago)
repo: New Repo.get_packages_download_dir() method
Currently, the path where a package should be downloaded is computed in 
several places. This patch introduces a single location for this 
computation to reduce code duplication. The patch also fixes usage of
incorrect package path in Package::get_package_path() call - the destdir
config option was not taken into account.
07105d0b (Marek Blaha, 2 hours ago)
doc: Document destdir main config option
Resolves: https://github.com/rpm-software-management/dnf5/issues/1620
Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1536

Use correct path when destdir option is set

---

dnf5.spec
doc/CMakeLists.txt
doc/api/c++/libdnf5_rpm_package_sack.rst
doc/conf.py.in
doc/dnf5.conf-todo.5.rst
doc/dnf5.conf.5.rst
doc/misc/filtering.7.rst
doc/misc/index.rst
doc/misc/modularity.7.rst

Resolves: https://github.com/rpm-software-management/dnf5/issues/1354

doc: Revise packages filtering doc section

---

dnf5.spec

This should fix the currently failing builds.
For f41 and rawhide they will still be failing because of the toml11 break.

spec: fix modularity man page

---

dnf5/CMakeLists.txt
dnf5/cmdline_aliases.cpp
libdnf5/CMakeLists.txt
libdnf5/repo/temp_files_memory.cpp
libdnf5/rpm/versionlock_config.cpp
libdnf5/system/state.cpp
test/libdnf5/system/test_state.cpp

This should fix the rawhide build.

Update toml11-devel usage for 4.0.0

---

dnf5.spec
doc/CMakeLists.txt
doc/conf.py.in
doc/dnf5.8.rst
doc/dnf5.conf.5.rst
doc/misc/index.rst
doc/misc/system-state.7.rst
libdnf5/system/state.cpp
libdnf5/system/state.hpp

Add a man page on DNF system state. This man page is then referenced in system state loading error messages.
Resolves: https://github.com/rpm-software-management/dnf5/issues/1550
Changes:
ac68a075 (Marek Blaha, 5 days ago)
doc: Add man page describing the system state
The page also contains information how to recover from corrupted system 
state files.
888d955c (Marek Blaha, 5 days ago)
state: Catch all errors during system state load
There are multiple exceptions that can occur during loading the system 
state from toml files. Now they are caught and wrapped in StateLoadError.

Better error messages for system state loading

---

dnf5/config/usr/share/dnf5/aliases.d/compatibility.conf
doc/changes.rst

We prefer the "--config" argument, for which we support bash completion. The short version "-c" is added to prevent problems with old scripts using dnf4 that may use "-c".
Closes: https://github.com/rpm-software-management/dnf5/issues/1622

[dnf5] Add argument "-c" - alias to "--config" (dnf4 compatibility)

---

dnf5/context.cpp
dnf5/include/dnf5/context.hpp
include/libdnf5/base/transaction.hpp
libdnf5/base/transaction.cpp
libdnf5/base/transaction_impl.hpp
libdnf5/rpm/transaction.cpp
libdnf5/rpm/transaction.hpp

Currently, the output of RPM scriptlets is somewhat hidden in the log. This patch introduces a new `libdnf5::base::Transaction::get_last_script_output()` method, which returns the outputs of the most recently executed RPM scriptlet. This method is then utilized in the transaction callbacks in DNF5 to display the output to the user.
Although it would be more intuitive to add the scriptlet output as a new parameter in script_end and script_error, doing so would break the existing API.
The scriptlet output is only printed in the event of a failure; it is not displayed when the execution is successful.
Resolves: https://github.com/rpm-software-management/dnf5/issues/522
Replaces: https://github.com/rpm-software-management/dnf5/pull/1645
Changes:
57715716 (Marek Blaha, 5 minutes ago)
dnf5: …

Show the output of failed scriptlets to the user

---

dnf5-plugins/automatic_plugin/automatic.cpp
dnf5-plugins/copr_plugin/copr_repo.cpp
dnf5/commands/history/history_store.cpp
dnf5/context.cpp
dnf5/download_callbacks.cpp
dnf5/include/dnf5/context.hpp
dnf5/main.cpp
dnf5daemon-client/callbacks.cpp
include/libdnf5-cli/progressbar/multi_progress_bar.hpp
include/libdnf5-cli/utils/userconfirm.hpp
libdnf5-cli/progressbar/multi_progress_bar.cpp

Resolves https://github.com/rpm-software-management/dnf5/issues/1361
This patchset changes many messages to be printed on stderr instead of stdout.
Opinions vary, but by general convention, the "useful output" of a program (that might be e.g. piped to a pager or consumed by a script), should be on stdout. All other messages, including warnings, progress bars, "Are you sure you want to continue?"-style prompts should be on stderr.
There are gray areas here, especially when you consider the same piece of output in different contexts. You could argue that the "Updating and loading repositories" message and multiprogressbar are "useful output" of the `makecache` command, but the same messages are not "useful output" of the `repoquery` command. And DNF 5 commands such as `install` and …

Print diagnostic messages on stderr, not stdout

---

dnf5/download_callbacks.cpp
dnf5daemon-server/callbacks.cpp
dnf5daemon-server/dbus/interfaces/org.rpm.dnf.v0.Goal.xml
dnf5daemon-server/services/goal/goal.cpp
dnf5daemon-server/services/goal/goal.hpp
dnf5daemon-server/session.cpp
dnf5daemon-server/session.hpp
include/libdnf5/repo/download_callbacks.hpp
libdnf5/repo/download_callbacks.cpp

Resolves: https://github.com/rpm-software-management/dnf5/issues/1660
Changes:
41f5a93e (Marek Blaha, 38 minutes ago)
dnfdaemon: API to cancel running Goal.do_transaction()
During the download phase, calling Goal.cancel() will cause all downloads
to abort and transaction will not be performed. Once the rpm transaction is
started, the cancel is not any more allowed and rpm transaction will
finish.
b8e03b20 (Marek Blaha, 39 minutes ago)
DownloadCallbacks: Enum for possible return codes
Instead of hard coded constants use enum as callbacks return values.

daemon: D-Bus API to cancel current transaction

---

dnf5-plugins/config-manager_plugin/addrepo.cpp

Comments and blank lines were interpreted as options in the configuration file validity test. Now they are ignored.
Closes: https://github.com/rpm-software-management/dnf5/issues/1603

config-manager: Fix addrepo from-repofile with empty/comment lines

---

dnf5/context.cpp
dnf5/main.cpp

Follow-up to https://github.com/rpm-software-management/dnf5/pull/1641, I forgot to push these two commits.
More details in the commit messages.
Fixes the following ci-dnf-stack tests:
- `dnf/install-file-conflicts.feature:8  An error is reported when a package with a file conflict is tried to be installed`
- `dnf/dnf-automatic/reboot.feature:95  dnf-automatic shows error message when reboot command failed`

Fix regressions from stderr/stdout changes

---

doc/api/c++/libdnf5_rpm.rst
doc/api/c++/libdnf5_rpm_transaction_callbacks.rst
doc/api/python/libdnf5_rpm.rst
doc/api/python/libdnf5_rpm_transaction_callbacks.rst
include/libdnf5/rpm/transaction_callbacks.hpp

Add missing documentation to rpm transaction callbacks.
Resolves: https://github.com/rpm-software-management/dnf5/issues/1658

doc: TransactionCallbacks class documentation

---

dnf5daemon-server/dbus/interfaces/org.rpm.dnf.v0.Goal.xml
dnf5daemon-server/session.hpp

See the two commits for more info.
Resolves: https://github.com/rpm-software-management/dnf5/issues/1646
Resolves: https://github.com/rpm-software-management/dnf5/pull/1665#discussion_r1745152462

dnfdaemon: Correct D-Bus signal argument type

---

dnf5-plugins/automatic_plugin/automatic.cpp
dnf5.spec
doc/changes.rst
doc/dnf5_plugins/automatic.8.rst

Since the automatic configuration file remains compatible, this change
makes the upgrade dnf4->dnf5 easier for the user.
Having so many automatic config files seems overly complicated so the
change also deprecates /etc/dnf/dnf5-plugins/automatic.conf location and
warns the user if they use it.
Resolves: https://github.com/rpm-software-management/dnf5/issues/1624

automatic: Use original dnf4 config file location

---

dnf5.spec

Tested F40 -> F41 upgrade using `dnf4 system-upgrade --releasever=40` and `dnf4 distro-sync --releasever=40`. If `dnf-plugins-core` is installed, then the system-upgrade (or distrosync) will install `dnf5-plugins` as a weak dependency. If `dnf-plugins-core` is missing, then `dnf5-plugins` will not be installed.
For https://bugzilla.redhat.com/show_bug.cgi?id=2309697

spec: Recommend dnf5-plugins if dnf-plugins-core installed

---

dnf5-plugins/automatic_plugin/transaction_callbacks_simple.cpp
dnf5-plugins/automatic_plugin/transaction_callbacks_simple.hpp
dnf5/commands/offline/offline.cpp
dnf5/context.cpp
dnf5/include/dnf5/context.hpp
dnf5daemon-server/callbacks.cpp
dnf5daemon-server/callbacks.hpp
include/libdnf5/rpm/transaction_callbacks.hpp
libdnf5/rpm/transaction.cpp
libdnf5/rpm/transaction.hpp
libdnf5/rpm/transaction_callbacks.cpp
test/tutorial/transaction/transaction.cpp

Given that there is another TransactionItem class in
libdnf5::transaction namespace, the alias libnf5::rpm::TransactionItem ->
libdnf5::base::TransactionPackage is confusing and does not add any
value to the user.
This patch deprecates it and uses directly TransactionPackage in all
places.

transaction_callbacks: Deprecate confusing alias

---

doc/api/c++/cpp.rst
doc/api/c++/libdnf5.rst
doc/api/c++/libdnf5_cli.rst
doc/api/c++/libdnf5_cli_argument_parser.rst
doc/api/c++/libdnf5_repo.rst
doc/api/c++/libdnf5_repo_repo_sack.rst
doc/api/c++/libdnf5_vars.rst
doc/api/python/libdnf5_conf.rst
doc/api/python/libdnf5_conf_vars.rst
doc/api/python/libdnf5_repo.rst
doc/api/python/libdnf5_repo_config_repo.rst
doc/api/python/libdnf5_repo_repo_sack.rst
doc/api/python/python.rst
doc/dnf5.conf.5.rst
doc/dnf5_workflow.rst
doc/index.rst

It also enables doc generation for couple classes.

doc: add typical dnf5 workflow

---

doc/misc/forcearch.7.rst
doc/tutorial/bindings/python3/session.rst
doc/tutorial/session.rst
test/python3/libdnf5/tutorial/session/force_arch.py
test/python3/libdnf5/tutorial/test_tutorial.py
test/tutorial/session/force_arch.cpp
test/tutorial/test_tutorial.cpp
test/tutorial/test_tutorial.hpp

We have documentation for CLI users (dnf5-forcearch(7)), but it's not
clear how to do the same thing through API. This patch fills the gap.
Resolves: https://github.com/rpm-software-management/dnf5/issues/1596

doc: Document arch override for API users

---

libdnf5-cli/output/transaction_table.cpp

Fixes `error: implicit conversion changes signedness: 'const int' to 'unsigned long' [-Werror,-Wsign-conversion]`
The bug was caused by commit https://github.com/rpm-software-management/dnf5/pull/1696

Fix: libdnf5-cli: TransactionSummary counters data type

---

dnf5/commands/list/list.cpp
libdnf5-cli/output/packageinfo.cpp

Related: https://github.com/rpm-software-management/dnf5/issues/1687

I18N: Mark messages in "dnf info" output for a translation

---

dnf5/context.cpp

A serialized offline transaction consists only of local packages
downloaded to the `<system state dir>/offline` location. Unfortunately,
PGP checks for these packages are disabled by default due to the
`localpkg_gpgcheck` option default value.
Instead of testing the serialized transaction, this patch performs an
RPM transaction test on the originally resolved transaction, which still
retains information about the repositories from which the packages were
downloaded.
This approach also saves time required for deserialization and resolving
the testing transaction.
Resolves: https://github.com/rpm-software-management/dnf5/issues/1668
Resolves: https://github.com/rpm-software-management/dnf5/issues/1667
Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1549

dnf5: Run transaction test for offline transactions

---

CMakeLists.txt
bindings/CMakeLists.txt
dnf5/main.cpp

This patch set adds -Wsign-conversion to compiler flags and fixes the code be compilable with it. It should prevent from surprises like in #1701.

Warn on sign conversion

---

dnf5/commands/clean/clean.cpp

If /var/cache/libdnf5 directory did not exist, "dnf clean all" reported and error:
Cannot iterate the cache directory: "/var/cache/libdnf5"
This patch optimizes this case to no operation. If there is no cache, there is nothing to remove.
If the iterator fails for a different reason, the message is ammended with an operating system error message, explaining the cause.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2313032

dnf clean: Do not report an error on a nonexistent cache directory

---

libdnf5/rpm/package_query.cpp

Without this patch, the i686 build fails due to `-Werror` and a sign conversion warning, introduced in https://github.com/rpm-software-management/dnf5/pull/1703.
I only noticed the error after making an upstream release and trying to build DNF 5.2.6.1 in Koji. It might be good to have builds for non-x86_64 architectures tested in our upstream CI so we can catch these issues sooner.

chore: static_cast to fix sign conversion warning

---

dnf5daemon-client/callbacks.cpp
dnf5daemon-server/session.cpp

1. Fix deserialization when checking signals `object_path`.
Since https://github.com/rpm-software-management/dnf5/pull/1679 `sdbus::ObjectPath` is send over to the client not `std::string`.
This was causing the check `signature_valid(sdbus::Signal &)` to crash, the client callback ended and the server kept waiting for result of the `key_import` userconfirm.
(I believe we should somehow handle when `DbusCallback::signature_valid()` returns `false` but I am not sure what would be the best approach. At least logging the event would be good (through the `context`?).)
2. The other commit fixes a bug for dnf5daemon offline transactions, analogous to https://github.com/rpm-software-management/dnf5/pull/1672.

Fix `sdbus::ObjectPath` when checking signals `object_path`

---

dnf5.spec
libdnf5/CMakeLists.txt

Bootc systems tend to prune /var directory
<https://containers.github.io/bootc/filesystem.html#var>. That breaks verifying integrity with "rpm --verify libdnf5".
This patch stops installing /var/cache/libdnf5 directory, but keeps tracking it by libdn5 RPM package. The directory is created by libdnf5 whenever it is needed.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2313032

Do not install /var/cache/libdnf5 directory

---

dnf5/main.cpp
dnf5daemon-client/main.cpp

Closes: https://github.com/rpm-software-management/dnf5/issues/1685

setlocale: If locale setting fails, try using C.UTF-8 as fallback

---

libdnf5-plugins/actions/CMakeLists.txt
libdnf5-plugins/actions/actions.cpp

Closes: https://github.com/rpm-software-management/dnf5/issues/1538
Introduces a "mode" option in the hook handler definition.
Option "mode" defines communication model between actions plugin and process.
Introduces 2 modes of communication: "plain" and "json".
Parameters are passed to the process only by arguments when it starts. Arguments may contain variables that are substituted before the process is started. A process can modify libdnf5 settings (main configuration, repository configuration, variables) and plugin actions variables by writing to standard
output.
**Output line format:**
- `tmp.<actions_plugin_variable_name>=<value>` - sets the value of action plugins variable `<actions_plugin_variable_name>`
-` tmp.<actions_plugin_variable_name>` - removes the action plugins variable …

Birectional communication of libdnf5 actions plugin with running processes - "json" mode

---

dnf5-plugins/copr_plugin/copr_repo.cpp

See https://github.com/fedora-copr/copr/issues/3375
When an alternative storage (such as Pulp) for Copr is used, the pubkey.gpg is still being stored on Copr backend. Therefore we can't always construct the correct pubkey URL here in the DNF plugin.

copr: use pubkey URL returned by Copr API

---

dnf5daemon-server/dbus/interfaces/org.rpm.dnf.v0.Goal.xml
dnf5daemon-server/services/goal/goal.cpp
dnf5daemon-server/services/goal/goal.hpp
dnf5daemon-server/session.cpp
dnf5daemon-server/session.hpp
libdnf5/base/goal.cpp

New D-Bus API to reset the goal.
Resolves: https://github.com/rpm-software-management/dnf5/issues/1653
Changes:
3cd0a6e3 (Marek Blaha, 5 minutes ago)
dnfdaemon: D-Bus API to reset the goal
With this patch the user can re-use the session to resolve multiple 
transactions without running them. The use case might be to check what 
dependencies would be installed with given package.
d77231b8 (Marek Blaha, 17 hours ago)
dnfdaemon: Add reset_goal() method
The method resets the current goal and transaction, which is necessary for
scenarios where the user wants to reuse the D-Bus session to resolve or
execute multiple transactions.
5dbe16a0 (Marek Blaha, 17 hours ago)
goal: Add missing members to reset() method
The reset() method currently does not reset all Goal members. This patch 
adds those …

daemon: Reset the goal

---

dnf5-plugins/automatic_plugin/transaction_callbacks_simple.cpp
dnf5/context.cpp
dnf5/main.cpp
dnf5/shared_options.cpp
dnf5daemon-client/callbacks.cpp
doc/commands/debuginfo-install.rst
doc/commands/distro-sync.8.rst
doc/commands/downgrade.8.rst
doc/commands/group.8.rst
doc/commands/install.8.rst
doc/commands/reinstall.8.rst
doc/commands/swap.8.rst
doc/commands/upgrade.8.rst
doc/dnf5_plugins/builddep.8.rst
libdnf5/rpm/solv/goal_private.cpp
libdnf5/rpm/transaction.hpp

A Fedora user noticed that an output of "dnf remove" command marks transaction actions as "Erasing" instead of "Removing" <https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/GL3RTOI5FUSZUQU3L2PVY2U5LQDB5BDI/>:
Package                          Arch      Version                          Repository             Size
Removing:
dontpanic                       x86_64    1.02-16.fc41                     f42-build          49.5 KiB
Transaction Summary:
Removing:           1 package
Is this ok [y/N]: y
Running transaction
[1/2] Prepare transaction                                      100% |  15.0   B/s |   1.0   B |  00m00s
[2/2] Erasing dontpanic-0:1.02-16.fc41.x8 100% [==================] | 225.0   B/s |  13.0   B | -00m00s
>>> Running trigger-post-uninstall …

Consistently use "removing" instead of "erasing" packages

---

dnf5/commands/download/download.cpp
dnf5/commands/download/download.hpp
doc/commands/download.8.rst

resolves: https://github.com/rpm-software-management/dnf5/issues/1734

Add --allmirros option for `dnf download --url`

---

libdnf5/comps/group/group.cpp

This commit addresses two memory issues that occur if saving of the
group XML file fails:
Memory leak: The `doc` variable is not properly freed before an error is
thrown, leading to a memory leak.
Use after free: The libxml2 error handler continues to reference the
`error_to_strings()` function, which uses the `xml_errors` vector that
is local to the `Group::serialize()` method. If the handler is invoked
later (e.g., during the serialization of an Environment), it may cause a
crash due to accessing freed memory.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2315789

comps: Fix memory issues in group serialization

---

dnf5/commands/offline/offline.cpp
dnf5/context.cpp
dnf5/include/dnf5/context.hpp
include/libdnf5/base/transaction.hpp
libdnf5/base/transaction.cpp
libdnf5/base/transaction_impl.hpp
libdnf5/rpm/rpm_log_guard.cpp
libdnf5/rpm/rpm_log_guard.hpp
libdnf5/rpm/transaction.cpp
libdnf5/rpm/transaction.hpp

The RPM messages contain vital information for debugging RPM transaction.
Currently are these messages only written to the dnf5.log file. This patch
also prints them to the user during the transaction execution.
Resolves: https://github.com/rpm-software-management/dnf5/issues/1710
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2312906

Print RPM messages to the user

---

.github/actions/weblate-pull-translations/action.yml

Translation template (*.pot) files were updated last time in year
2023. As a result msgmerge run during building DNF5 removed all newly added translated messages from message cataloges because the new messages were missing from the template files.
This patch fixes it by copying the templates together with messages catalogs from Weblate on every DNF5 release.
Resolves: #1744

i18n: Update translation templates from Weblate

---

libdnf5/base/transaction.cpp

Internationalization of "Warning: skipped PGP checks for {0} packages from repositories: {1}" message wwas wrong, especially for languages having more that one plural form. E.g. in Czech it could produced "Upozornění: vynechané PGP kontroly pro 5 balík z repozitářů: f42-build".
This patch fixes it.
Resolves #1171

i18n: Fix plural forms for "Warning: skipped PGP checks..." message

---

libdnf5/repo/repo_sack.cpp
libdnf5/solv/pool.hpp

When filelists are loaded and file provides are used it is much faster not to set `POOL_FLAG_ADDFILEPROVIDESFILTERED` because libsolv goes through all the files just once during `pool_addfileprovides_queue`.
This is based on: https://github.com/rpm-software-management/libdnf/issues/1674
Specifically this is an improvement for users that use repos with file provides outside of primary.xml and download filelsits.xml.

Set `POOL_FLAG_ADDFILEPROVIDESFILTERED` only when not loading filelists

---

libdnf5/repo/solv_repo.cpp
libdnf5/repo/solv_repo.hpp

In a repo filelists are stored in different `repodata`, limit the written `repodata` when writing main solv file.
Otherwise the filelists are stored twice: in the main solv file and in the filelists specific solvx file. (This happens when downloading both the primary.xml and filelists.xml at the same time.)
It also improves performance because when filelists were part of main solv file they were always loaded (regardless of the `optional_metadata_types` option).
Closes: https://github.com/rpm-software-management/dnf5/issues/1749

When writing main solv file (primary.xml) don't store filelists

---

dnf5/commands/history/arguments.hpp
dnf5/commands/history/history_store.cpp

1. Allow unlimited number of arguments for history `list` and `info`
Closes: https://github.com/rpm-software-management/dnf5/issues/1721
2. `history store` command: move arg verificion above user confirmation

Allow unlimited number of arguments for history `list` and `info`

---

bindings/CMakeLists.txt
bindings/libdnf5/utils.i
test/libdnf5/utils/test_patterns.cpp
test/libdnf5/utils/test_patterns.hpp
test/perl5/libdnf5/utils/test_patterns.t
test/python3/libdnf5/utils/test_patterns.py
test/ruby/libdnf5/utils/test_patterns.rb

`libdnf5::utils::is_glob_pattern` and `libdnf5::utils::is_file_pattern` are C++ public API functions.
Adds a new "utils" module to the bindings.
Includes `C++`, `Perl`, `Python` and `Ruby` unit tests for `is_glob_pattern` and `is_file_pattern` .
Closes: https://github.com/rpm-software-management/dnf5/issues/1563
Requires fix: https://github.com/rpm-software-management/dnf5/pull/1742

[swig] Bindings and tests for libdnf5::utils::[is_glob_pattern | is_file_pattern]

---

doc/changes_from_dnf4.7.rst

I also sorted the options on the line.
Related: #910

doc: "dnf repoquery --unsatisfied" is not supported

---

include/libdnf5/comps/environment/environment.hpp
include/libdnf5/comps/environment/query.hpp
include/libdnf5/comps/group/group.hpp
include/libdnf5/comps/group/query.hpp
libdnf5/comps/environment/environment.cpp
libdnf5/comps/environment/query.cpp
libdnf5/comps/group/group.cpp
libdnf5/comps/group/query.cpp
test/python3/libdnf5/comps/test_comps_iterators.py

This mirrors the similar classes in libdnf5::rpm that provide the same methods. This will help fedrq implement group querying functionality.

comps: add get_base() to {Group,Environment}{,Query}

---

dnf5-plugins/config-manager_plugin/config-manager.cpp
dnf5/commands/advisory/advisory.cpp
dnf5/commands/autoremove/autoremove.cpp
dnf5/commands/check-upgrade/check-upgrade.cpp
dnf5/commands/check/check.cpp
dnf5/commands/debuginfo-install/debuginfo-install.cpp
dnf5/commands/distro-sync/distro-sync.cpp
dnf5/commands/downgrade/downgrade.cpp
dnf5/commands/environment/environment.cpp
dnf5/commands/history/history.cpp
dnf5/commands/install/install.cpp
dnf5/commands/leaves/leaves.cpp
dnf5/commands/mark/mark.cpp
dnf5/commands/module/module.cpp
dnf5/commands/provides/provides.cpp
dnf5/commands/reinstall/reinstall.cpp
dnf5/commands/remove/remove.cpp
dnf5/commands/replay/replay.cpp
dnf5/commands/repo/repo.cpp
dnf5/commands/repoquery/repoquery.cpp
dnf5/commands/search/search.cpp
dnf5/commands/swap/swap.cpp
dnf5/commands/upgrade/upgrade.cpp
dnf5/commands/versionlock/versionlock.cpp
dnf5/main.cpp
dnf5daemon-client/commands/advisory/advisory.cpp
dnf5daemon-client/commands/distro-sync/distro-sync.cpp
dnf5daemon-client/commands/group/group.cpp
dnf5daemon-client/commands/repo/repo.cpp
dnf5daemon-client/commands/repoquery/repoquery.cpp

Use `_(msgId)` in `bgettext-lib.h` to mark text as eligible for
translation. This will allow translators to translate the short
descriptions of the commands in `dnf5 --help`. Further changes will be
required to make each command description translatable.
Related: #1736

Make most descriptions for `dnf5 --help` translatable.

---

dnf5/context.cpp

It was reported that --installroot with an explicit --repo option does not recognize given repository despite the repository is defined under /etc:
$ dnf --installroot /tmp/dnf5/ --releasever rawhide --repo koji makecache
No matching repositories for "*, koji". Add "--help" for more information about the arguments.
That's a feature, but a difference from DNF4.
This patchs recommeds using --use-host-config in that case. We already have a similar recommendation in main.cpp in case of no --repo option is used.
This patch also fixes formatting of the list of repository identifiers with respect to localization.
The code duplicates throws because libdnf5 exception construtors do not accept nonstatic arguments.
Resolves #1756

Recommend --use-host-config if --installroot is used and not all repositories can be enabled

---

libdnf5/logger/rotating_file_logger.cpp

There is an issue with RotatingFileLogger where log messages during an
RPM transaction in installroot fail to be recorded. When RPM enters a
chroot environment during the transaction, the path resolution changes,
and RotatingFileLogger attempts to reopen the log file from its disk
path for each message. However, once inside the chroot, the log file
path can no longer be resolved, leading to a failure in logging until
the RPM transaction completes.
This patch modifies the RotatingFileLogger behavior to keep the log file
descriptor open, ensuring continuous logging throughout the RPM
transaction.
Resolves: https://github.com/rpm-software-management/dnf5/issues/1717

log: Preserve log messages during RPM transaction

---

dnf5.spec

Fedora 37 was end-of-life on 2023-12-05.

chore: Clean up Fedora 37-related conditionals in RPM spec

---

dnf5/commands/offline/offline.cpp
dnf5/commands/repo/repo_info.cpp
dnf5/main.cpp
dnf5daemon-client/commands/repolist/repolist.cpp
dnf5daemon-client/wrappers/dbus_repo_wrapper.hpp
dnf5daemon-server/services/repo/repo.cpp
doc/dnf5.conf.5.rst
doc/dnf5_plugins/config-manager.8.rst
include/libdnf5-cli/output/interfaces/repo.hpp
include/libdnf5/base/transaction.hpp
include/libdnf5/conf/config_main.hpp
include/libdnf5/repo/config_repo.hpp
libdnf5-cli/output/repo_info.cpp
libdnf5/conf/config_main.cpp
libdnf5/repo/config_repo.cpp
libdnf5/rpm/rpm_signature.cpp
test/libdnf5/base/test_transaction.cpp
test/libdnf5/conf/test_conf.cpp
test/libdnf5/conf/test_conf.hpp
test/python3/libdnf5/base/test_transaction.py

Changes the name to a more apt `pkg_gpgcheck` but `gpgcheck` is still accepted. At this point I am not sure we will ever be able to drop it.
It adds new getter API to both main and repo: `get_pkg_gpgcheck_option` and depracates the old `get_gpgcheck_option`.
It also extends `libdnf5::cli::output::IRepoInfo` with `get_pkg_gpgcheck` and the `dnf5daemon-server` should also accept `pkg_gpgcheck` attribute.
For: https://github.com/rpm-software-management/dnf5/issues/1649

Change `gpgcheck` option to `pkg_gpgcheck` but stay compatible

---

doc/changes_from_dnf4.7.rst
doc/dnf5.conf-todo.5.rst
include/libdnf5/conf/config_main.hpp
libdnf5/conf/config_main.cpp

It isn't doing anything and it was deprecated in dnf < 5 probably since dnf was first created.

Drop `errorlevel` config option

---

bindings/ruby/CMakeLists.txt

Building Ruby binding with Swig 4.3.0 failed:
cd /home/test/dnf5/redhat-linux-build/bindings/ruby/libdnf5 && /usr/bin/cmake -E env SWIG_LIB=/usr/share/swig/4.3.0 /usr/bin/swig -ruby -DSWIGWORDSIZE64 -module advisory -ruby -outdir /home/test/dnf5/redhat-linux-build/bindings/ruby/libdnf5 -c++ -module advisory -I/home/test/dnf5/include -I/home/test/dnf5/common -I/usr/include -o /home/test/dnf5/redhat-linux-build/bindings/ruby/libdnf5/CMakeFiles/ruby_advisory.dir/advisoryRUBY_wrap.cxx /home/test/dnf5/bindings/libdnf5/advisory.i
Only one target language can be supported at a time (both -ruby and -ruby were specified).
The cause was an explcitit and unnecessary "-ruby" option in CMAKE_SWIG_FLAGS.
This patch removes it. The targetted langauge is already set with swig_add_library().
Resolves: …

build: Remove an explicit swig option -ruby

---

include/libdnf5/conf/config_main.hpp
libdnf5/conf/config_main.cpp

Keep the defunct options to preserve API.
Revert: https://github.com/rpm-software-management/dnf5/pull/1788
It keeps the docs update.

Revert "Drop `errorlevel` config option"

---

libdnf5/transaction/db/comps_group_package.cpp

When a package is included in a comps group multiple times, dnf5
attempts to insert that package multiple times into the
`comps_group_package table` of the transaction history database. However,
the table enforces a unique constraint on the (group_id, name_id) tuple.
This results in terminating dnf5 process.
This patch modifies the CompsGroupPackageDbUtils::comps_group_packages_insert()
method to track which packages have already been inserted and skip
duplicates.
Here is an example of such group with duplicated packages from rpmfusion
repository (see the `libavcodec-freeworld` package):
```
<group>
<id>multimedia</id>
<name>Multimedia</name>
<description>Audio/video framework common to desktops</description>
<default>false</default>
<uservisible>false</uservisible>
<packagelist> …
```

historydb: Prevent insertion of duplicate group packages

---

libdnf5/transaction/transaction_sr.cpp

Initialize the action, nevra, reason, repo_id, group_id, and package_path
fields to empty strings for each package, when parsing transaction JSON
file. Without this initialization, these fields may retain values
from the previous loop iteration, leading to an incorrect transaction.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2322527

Fix parsing of offline transaction JSON file

---

dnf5/commands/download/download.cpp
dnf5/context.cpp
dnf5/download_callbacks.cpp
dnf5daemon-client/callbacks.cpp
libdnf5-cli/progressbar/multi_progress_bar.cpp
test/libdnf5-cli/test_progressbar.cpp
test/libdnf5-cli/test_progressbar.hpp

The last line of `multi_progress_bar` can look like:
`[2/2] Total           100% |   0.0   B/s |  20.0   B |  00m00s`
or
`http://localhost:43223/api_3/rpmrepo 100% |  72.0 KiB/s | 295.0   B |  00m00s`
I don't think any client will ever want to append to that.
Instead of it needing to be printed by the client the
`multi_progress_bar` automatically ends with a new line.
This new line was missing on some places. For example in output of:
`dnf copr enable rpmsoftwaremanagement/dnf-nightly `
or
`dnf5 rq --repofrompath=test,https://www.not-available-repo.com/ --repo test --setopt=skip_if_unavailable=0`
There were also excessive new lines like in:
`dnf5 remove htop -y &> out`
Closes: https://github.com/rpm-software-management/dnf5/issues/1792

When `multi_progress_bar` finishes print new line automatically

---

libdnf5/repo/file_downloader.cpp
libdnf5/repo/package_downloader.cpp
test/libdnf5/repo/test_package_downloader.cpp

For every successful (ended without exception) call of `add_new_download` callback, the `end` callback is called once.
The code relied on librepo to call the `end` callback just once for each `lr_target`. Which works under normal conditions. But if there is an interruption in the librepo download (error, signal received) librepo will not call `end` callbacks for targets that have not yet started downloading. However, the `add_new_download` callback has already been called for them. For example, if a higher layer allocated resources on `add_new_download` and deallocated on `end`, resources would be lost. 
The new code tracks this and calls the appropriate `end` callbacks. Also, an assert has been added to monitor for any attempt to double call the `end` callback.

DownloadCallbacks: Ensure `end` for every successful `add_new_download`

---

doc/changes_from_dnf4.7.rst

It is still possible to have optional arguments.
That is both `dnf5 upgrade` and `dnf5 upgrade htop --best` are fine.
The way I understand it is:
`upgrade` = command
`htop` = argument
`--best` = option

Clear up changes doc about optional subcommands

---

libdnf5-cli/progressbar/multi_progress_bar.cpp

This is to avoid multiple small writes to the terminal, which can cause flickering.
On my machine (Fedora 41 GNOME) I can see that the new concurrent download status bar flickers quite a bit. I've tested this on gnome-terminal/xfce4-terminal/uterm and kitty. Only Kitty does not flicker. The flickering happens regardless if Wayland/X11 is used.
The old behaviour would issue multiple clear_line writes, followed by multiple writes to "draw" the new status bars.
The new behaviour buffers all of the screen updates for a single "frame" and then writes all of that out with a single syscall.
I've tested the code changes using gnome-terminal/xfce4-terminal/uterm and kitty. Wayland and X11 sessions. It works flawlessly for me now.
I've also tested resizing the terminal window during download, and …

MultiProgressBar now buffers the output text to a single write

---

libdnf5/repo/solv_repo.cpp

Check the solv_read_userdata() return code before creating a unique_ptr
with SolvUserdata.
In case the solv_read_userdata() failed, the solv_free would be called
on unitialized data causing undefined behavior.
Resolves: https://github.com/rpm-software-management/dnf5/issues/1845

repo: Fix invalid free()

---

libdnf5/rpm/rpm_log_guard.cpp
libdnf5/rpm/rpm_log_guard.hpp

This patch addresses undefined behavior that occurs when the RPM log
callback function is invoked after the RpmLogGuard object has been
destroyed. The issue arises because rpmlogCallbackData retains a
reference to the destroyed object.
The problem manifests during the execution of the builddep plugin command:
1. During Vars::detect_release, the RPM log callback is set via RpmLogGuard.
2. After the release version is detected, the RpmLogGuard object is destroyed.
3. A subsequent call to rpmSpecParse() by the builddep command may
trigger the previously set log callback.
4. This results in undefined behavior because the callback data still
points to the destroyed RpmLogGuard.
By resetting the RPM log callback upon RpmLogGuard destruction, this
patch ensures safe and predictable behavior. …

rpm: Reset RPM log callback upon RpmLogGuard destruction

---

bindings/libdnf5/repo.i
dnf5.spec
test/libdnf5/repo/test_package_downloader.cpp
test/perl5/CMakeLists.txt
test/perl5/libdnf5/BaseTestCase.pm
test/perl5/libdnf5/repo/test_package_downloader.t
test/perl5/libdnf5/repo/test_repo.t
test/perl5/libdnf5/rpm/test_package_query.t
test/python3/libdnf5/repo/test_package_downloader.py
test/python3/libdnf5/repo/test_repo.py
test/ruby/libdnf5/repo/test_package_downloader.rb
test/ruby/libdnf5/repo/test_repo.rb

Closes: https://github.com/rpm-software-management/dnf5/issues/1441
SWIG bindings for user_cb_data in `repo::DownloadCallbacks` in the C++ API, the user can return a pointer (`void *`) to user data in the `add_new_download` method of the `repo::DownlodCallbacks` class. This pointer is then passed as an argument to `void * user_cb_data` in other methods of the `repo::DownloadCallbacks` class.
There was a problem of how to use this mechanism in SWIG bindings.
I implemented and tested several solutions. In the case of passing a pointer, there was a problem with the ownership of the data the pointer points to. Users of Python and some other languages are used to the gargabe collector and automatically holding ownership of the passed data. While I've solved this for `user_cb_data`, passing …

SWIG bindings for user_cb_data in repo::DownloadCallbacks, unit tests

---

test/libdnf5-cli/test_progressbar.cpp

If the machine doing the testing is slow enough some non-negligible time can elapse and the speed will be non zero.
'?' matches any character.
Example in our nightly builds: https://download.copr.fedorainfracloud.org/results/rpmsoftwaremanagement/dnf-nightly/fedora-41-aarch64/08278595-dnf5/builder-live.log.gz

Make `test_multi_progress_bar` test more resilient

---

libdnf5/repo/package_downloader.cpp

Packages in repositories are typically stored in a multi-level directory
structure. Previously, the `download()` method only created the final
directory in the destination path, failing if any intermediate
directories were missing. This patch ensures the entire destination path
is created.

package_downloader: Ensure creation of intermediate directories

---

include/libdnf5/repo/repo.hpp

It's needed for `dnf5 reposync --download-metadata` command.

repo: Make Repo::download_metadata() method public

---

dnf5.spec

Fedora 41 has completed the migration to DNF5, so ELN (the future RHEL 11) is now ready to follow suit.
See also: https://github.com/rpm-software-management/dnf/pull/2161

spec: toggle dnf5_obsoletes_dnf for RHEL 11

---

include/libdnf5/rpm/rpm_signature.hpp
libdnf5/rpm/rpm_signature.cpp

Adds new RpmSignature::check_package_signature(std::string path)
overload to check PGP signatures of a local RPM file in given location.

rpm: New API to check PGP signature of RPM file

---

dnf5-plugins/changelog_plugin/changelog.cpp
dnf5/main.cpp
doc/dnf5.conf.5.rst
include/libdnf5/conf/const.hpp
libdnf5/repo/repo.cpp
libdnf5/repo/repo_downloader.cpp
libdnf5/repo/repo_sack.cpp

Needed for `dnf5 reposync --download-metadata` command.

repo: Add option to download all repository metadata

---

.packit.yaml

Requires: https://github.com/rpm-software-management/ci-dnf-stack/pull/1595

Add packit job to run ABI check on testing farm

---

dnf5/include/dnf5/CMakeLists.txt

Since 62b8503e52b832a4e9f39786493af8f2f8be9113 (dnf5 app, dnf5 plugins: Do not export private symbols) defs.h is included into dnf5 header files but it is not installed.
This patch fixes it.
Resolves: #1913

Install defs.h for /usr/include/dnf5/context.hpp

---

dnf5/commands/offline/offline.cpp
dnf5/main.cpp
doc/dnf5.8.rst
doc/dnf5.conf-todo.5.rst
doc/dnf5.conf.5.rst
doc/dnf5_workflow.rst
doc/misc/installroot.7.rst
include/libdnf5/repo/repo_callbacks.hpp
include/libdnf5/rpm/rpm_signature.hpp
libdnf5/rpm/rpm_signature.cpp

The public-key technology is called Pretty Good Privacy. GPG is a synonymous for GnuPG, a piece of software which DNF5 does not use.

doc: Use PGP instead of GPG

---

libdnf5-plugins/actions/actions.cpp

Fix compilation error:
error: conversion to ‘unsigned int’ from ‘int’ may change the sign of the result [-Werror=sign-conversion]

Fix libdnf5 actions plugin sign conversion compilation err

---

dnf5-plugins/builddep_plugin/builddep.cpp
dnf5-plugins/builddep_plugin/builddep.hpp
doc/changes_from_dnf4.7.rst
doc/dnf5_plugins/builddep.8.rst

By default, the type of positional argument (spec file, source RPM, or
package) is deduced based on its extension. However, when a file does
not have a traditional extension, the type can now be explicitly
specified using the following new options:
--spec: Treats subsequent arguments as spec files.
--srpm: Treats subsequent arguments as source RPMs.
Resolves: https://github.com/rpm-software-management/dnf5/issues/799

builddep: Add support for --spec and --srpm options

---

include/libdnf5-cli/progressbar/multi_progress_bar.hpp
include/libdnf5-cli/tty.hpp
libdnf5-cli/progressbar/multi_progress_bar.cpp
libdnf5-cli/tty.cpp
test/libdnf5-cli/test_progressbar.cpp
test/libdnf5-cli/test_progressbar.hpp
test/libdnf5-cli/test_progressbar_interactive.cpp
test/libdnf5-cli/test_progressbar_interactive.hpp
test/shared/utils.hpp

Fix couple of issues for `MultiProgressBar` printing.
Add testing for `MultiProgressBar` in interactive mode.

`MultiProgressBar` fixes and tests

---

doc/changes_from_dnf4.7.rst

Currently the points are all rendered on a single line: https://dnf5.readthedocs.io/en/latest/changes_from_dnf4.7.html

changes_from_dnf4: fix formatting of indented `list` points

---

bindings/libdnf5/repo.i

It's a backwards compatibility API.
Originally, return value support was not implemented in SWIG bindings for the `add_new_download` method and the method only accepted `None` as a return value.
Later, support was implemented for returning an integer, which is then passed in subsequent callbacks (`progress`, `end`, ...) as the `user_cb_data` argument. By expecting an integer instead of `None`, existing programs returning None are broken.
This PR adds the ability for Python programs to return None (it has the same meaning as returning the integer 0 in this case).

Python API: Method `DownloadCallbacks.add_new_download` can return `None`

---

dnf5.spec

This fixes a wrong RPM provide ("python3-libdnf" provided by "python3-libdnf5"; watch the digit) and removes unnecessary explicit provides which are already implicit by a package name.
Forwarded from <https://src.fedoraproject.org/rpms/dnf5/pull-request/91> downstream.

Fix python RPM provides

---

bindings/libdnf5/repo.i
test/dnf5-plugins/copr_plugin/CoprRepoTest.cpp
test/libdnf5/comps/test_group.cpp
test/libdnf5/repo/test_file_downloader.cpp
test/libdnf5/repo/test_file_downloader.hpp
test/libdnf5/repo/test_package_downloader.cpp
test/libdnf5/repo/test_repo.cpp
test/libdnf5/repo/test_temp_files_memory.cpp
test/libdnf5/rpm/test_transaction.cpp
test/perl5/libdnf5/BaseTestCase.pm
test/perl5/libdnf5/repo/test_file_downloader.t
test/perl5/libdnf5/repo/test_package_downloader.t
test/perl5/libdnf5/repo/test_repo.t
test/python3/libdnf5/repo/test_file_downloader.py
test/python3/libdnf5/repo/test_package_downloader.py
test/python3/libdnf5/repo/test_repo.py
test/ruby/libdnf5/repo/test_file_downloader.rb
test/ruby/libdnf5/repo/test_package_downloader.rb
test/ruby/libdnf5/repo/test_repo.rb
test/shared/base_test_case.cpp
test/shared/test_case_fixture.cpp
test/shared/test_case_fixture.hpp

Closes: https://github.com/rpm-software-management/dnf5/issues/1943
Adds support for the `user_data` argument to the `repo::DownloadCallbacks::add_new_download` method.
Its value can be set for different downloaders:
`repo::FileDownloader`: `user_data` can be passed as a parameter to the `add` method for the file being added.
`repo::PackageDownloader`: `user_data` can be passed as a parameter to the `add` method for the package being added.
The `repo::Repo::set_user_data` and `repo::Repo::get_user_data` methods to set/get `user_data` for each repository - used when downloading repository metadata.
Unit tests for all supported languages included.

SWIG bindings: Support DownloadCallbacks `user_data`, unit tests

---

libdnf5-cli/output/transaction_table.cpp

`Replacing:       {:4} package` -> `Replacing:       {:4} packages`

Fix plural typo

---

libdnf5-cli/progressbar/download_progress_bar.cpp
test/libdnf5-cli/test_progressbar_interactive.cpp
test/libdnf5-cli/test_progressbar_interactive.hpp

Add padding to fully fill the terminal_width, this is because `MultiProgressBar` overrides its own messages, it doesn't clear the lines. If the message is short some leftover characters could be still present after it.
The combination of adding/removing scriptlet messages and just overwriting `MultiProgressBar` lines is making this quite complicated.
Another approach to fix the issues could be reverting https://github.com/rpm-software-management/dnf5/commit/8fbbeb20f517f6bb160c0bc6592e3725f041d2c7 it would make our code simpler but I think this should still be more efficient though I have not tested it.
Follow up for: https://github.com/rpm-software-management/dnf5/pull/1925

Add padding to ProgressBar messages to avoid overlapping

---

test/python3/libdnf5/repo/test_package_downloader.py

`DownloadCallbacks.add_new_download` can now return either `None` or an `int`. This adds a regression test to check that `add_new_download` can still return `None`.

Python API: `add_new_download` return `None` regression test

---

test/libdnf5/run_tests.cpp
test/shared/base_test_case.cpp
test/shared/logger_redirector.hpp
test/shared/test_logger.cpp
test/shared/test_logger.hpp

Closes: https://github.com/rpm-software-management/dnf5/issues/1947
I found a nasty hack in the code. A pointer to the `CPPUnit::TestCaller` class was cast to a pointer to `HackTestCaller` using `reinterpret_cast`. The hack was used to make private members accessible in the original class for `LogCaptureListener`.
Additionally, `BaseTestCase` has been modified in the `LogCaptureListener` class.
The code has been rewritten to not need this hack. And the `BaseTestCase` modification was moved to
the `BaseTestCase::setUp` method.
Solves:
```
Start  1: test_libdnf
1/3 Test  #1: test_libdnf ......................***Failed    4.64 sec
/dnf5/test/libdnf5/run_tests.cpp:69:53: runtime error: member access
within address 0x50800001a7a0 which does not point to an object of type 'HackTestCaller' …
```

Unit tests: Fix problematic nasty hack in run_tests

---

dnf5/main.cpp

There was a bug in testing whether a difference of an installation size and a removal size fits into int64_t. E.g. on a pure package removal, the difference was negative, overflowing resulting unsigned type, leading to a very large positive value, larger than could fit into int64_t. As a result an existing range check failed and no report was printed.
This patch fixes it by preventing from a subtraction with a negative rusult.
(A fix which would compute the difference before the branching would either loose precision, or decide the branching twice.)
Resolves: #1938

Fix reporting disk space to be freed on a pure package removal

---

dnf5-plugins/automatic_plugin/automatic.cpp
dnf5-plugins/automatic_plugin/config/usr/share/dnf5/dnf5-plugins/automatic.conf
dnf5-plugins/automatic_plugin/config_automatic.cpp
dnf5-plugins/automatic_plugin/config_automatic.hpp
doc/dnf5_plugins/automatic.8.rst

Currently, we always emit messages every time automatic runs, even if it does nothing very interesting (the operation succeeds and there are no changed packages). This is flooding Fedora infra with boring emails that effectively just say "nothing happened".
This adds a setting to only emit if *something* interesting happened - the operation failed, or we saw package changes.

automatic: add a setting to not emit boring messages

---

.readthedocs.yaml

The old `ubuntu-22.04` uses version `swig4.0` which fails on C++11 attributes. We have started to use them in: https://github.com/rpm-software-management/dnf5/pull/1793 and the readthedocs build has been failing since then.
Use `24.04` (https://about.readthedocs.com/blog/2024/06/ubuntu-24-04/) because it uses `swig_4.2.0` which at least ignores the attributes.
According to the changelog the attributes should be ignored since version 4.1.0: https://www.swig.org/Release/CHANGES
```
2022-07-07: jmarrec
#1158 #2286 Add basic support for C++11 attributes.  These are now
crudely ignored by SWIG's parser's tokeniser, which is better than
failing with a parse error.
```

Bumb readthedocs ubuntu image version to fix the docs generation

---

dnf5-plugins/automatic_plugin/emitters.cpp

`{body}` was not substituted correctly in `command_format` for the command emitter.
Resolves https://github.com/rpm-software-management/dnf5/issues/1951

automatic: Substitute variables in command_format

---

libdnf5-cli/progressbar/widgets/time.cpp

Currently, the time estimates in our progress bars are displayed as negative numbers, e.g:
```
Fedora 42 on Koji                          1% [                  ] |   4.9 KiB/s | 854.1 KiB | -03h18m
```
This formatting makes sense if the user reads it as "the current time is T minus 3h18m", where T is the time my download will be done. And this is the convention in some contexts, e.g. rocket launches. But it is not idiomatic here, where a user is likely to expect the number to mean "time remaining".
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=2332931
Resolves https://github.com/rpm-software-management/dnf5/issues/1963

Display remaining time as nonnegative number

---

doc/changes_from_dnf4.7.rst

The replacement has already been recommended in dnf(8) manual of DNF4 project.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2335257

doc: "dnf history userinstalled" replaced with "dnf repoquery --userinstalled"

---

test/libdnf5-cli/output/test_repoquery.cpp

I discovered a resource leak while working on https://github.com/rpm-software-management/dnf5/issues/1893.
There was a missing "fclose()" in "libdnf5-cli/output/test_repoquery.cpp".
I wrapped `open_memstream` in "libdnf5-cli/output/test_repoquery.cpp" in the `MemStream` class to ensure automatic resource release in the destructor. I also made an optimization - replacing `std::string` with `std::string_view` with the `len` argument in the constructor.

Fix resource leak in unit test "libdnf5-cli/output/test_repoquery.cpp", optimization

---

dnf5.spec

DNF5 uses that directory at least for storing countme cookies.
This patch does not install that directory because /var is effemeral on bootc systems (see commit
5cc72c6c490c82604d83fc8d8ec262d854617d2d).
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2332856
Related: #1968

Own /var/lib/dnf by libdnf5

---

dnf5-plugins/copr_plugin/copr_config.cpp
dnf5-plugins/copr_plugin/copr_config.hpp

I discovered a resource leak while working on https://github.com/rpm-software-management/dnf5/issues/1893.
There was a missing `globfree` function call in the `CoprConfig::load_all_configuration()` method.
One can say that adding the line `globfree(&glob_result);` after the `for` loop is enough. But it's not true. The `load_copr_config_file` method called in the loop can generate an exception. So I rewrote the code to use `std::filesystem::directory_iterator`.

Copr plugin: Fix resource leak in load_all_configuration

---

libdnf5/repo/repo_sack.cpp

Previously, if a download error message line contained `{}`,
logger.warning would interpret it as a format string without any
arguments passed, causing the libdnf5::utils::sformat function to crash.
This commit addresses the issue by ensuring error messages are handled
safely.
Fixes: https://github.com/rpm-software-management/dnf5/issues/1919

repo: Fix logging metadata download errors handling

---

dnf5/commands/reinstall/reinstall.cpp
dnf5/commands/remove/remove.cpp
dnf5/commands/repoquery/repoquery.cpp
dnf5/commands/swap/swap.cpp
dnf5/context.cpp
dnf5/include/dnf5/context.hpp

Closes: https://github.com/rpm-software-management/dnf5/issues/1956
Originally, for packages, the NAME was offered in bash completion. In the case of multiple packages with the same NAME, there was an option to offer NEVRA instead of a NAME for those packages.
Now, bash completion always offers NEVRA for packages. There is an option to offer package NAME in addition to NEVRAs. This is useful, for example, when the user wants to install a package. Usually the user only wants to enter the package NAME and not the entire NEVRA. If multiple packages with the same NAME are available, the specific
package is then selected by the solver.
The DNF5 aplication now always offers both NEVRAs and NAMEs.

Bash completion: Always offer NEVRAs and NAMEs for packages

---

dnf5/bash-completion/dnf5

Closes: https://github.com/rpm-software-management/dnf5/issues/1982
Word completion may behave improperly if there is a colon in the word to be completed. The colon can be special to readline's word completion code: it can be one of the characters that breaks words for the completer.
The current set of completion word break characters is available in bash as the value of the `COMP_WORDBREAKS` variable.  Removing `:` from that value is enough to make the colon not special to completion: `COMP_WORDBREAKS=${COMP_WORDBREAKS//:}`
This fix is workaround for cases where `:` is a break character (it is contained in `COMP_WORDBREAKS`). A side effect in this case is the removal of the prefix containing the colon in the list of bash completion suggestions.

Fix colon in bash completion

---

test/libdnf5-cli/test_progressbar.cpp
test/libdnf5-cli/test_progressbar_interactive.cpp

The libdnf5-cli progressbar unit tests unnecessarily used the protected method `DownloadProgressBar::to_stream`. The libdnf5-cli library publicly provides the `<<` operator (API) for `DownloadProgressBar`. This operator does the same thing and internally uses the `to_stream` method.

libdnf5-cli unit tests: Use only public API methods

---

dnf5-plugins/automatic_plugin/emitters.cpp

Sendmail 8.18.1 started to reject e-mail messages without CRLF line endings:
libcurl error while sending e-mail: Weird server reply
sendmail[7095]: 508DXZbS007095: collect: relay=localhost, from=<root@localhost>, info=Bare linefeed (LF) not allowed, where=body, status=tempfail
This is a deliberate change in Sendmail 8.18.1. And the cause is that automatic plugin composes a message body with UNIX line endings and passes it to cURL library with CURLOPT_READDATA option.
While cURL automatically escapes leading dots in the body (".\r\n"), it does not normalize end-of-lines
<https://github.com/curl/curl/issues/15942>.
This patch fixes it by asking cURL to perform the normalization.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2335508

automatic: Fix end-of-lines in messages sent by email emitter

---

CMakeLists.txt
dnf5.spec
include/libdnf5/conf/const.hpp
include/libdnf5/repo/repo.hpp
libdnf5-plugins/CMakeLists.txt
libdnf5-plugins/appstream/CMakeLists.txt
libdnf5-plugins/appstream/appstream.conf
libdnf5-plugins/appstream/appstream.cpp
libdnf5/repo/repo.cpp
libdnf5/repo/repo_downloader.cpp
libdnf5/repo/repo_downloader.hpp
libdnf5/repo/solv_repo.cpp
libdnf5/repo/solv_repo.hpp
libdnf5/utils/library.cpp

Repositories can provide Appstream data for the packages they contain. This Appstream data is consumed by applications like gnome-software or KDE Discover, thus the users can see the packages (apps) in them.
This is to be in pair with PackageKit, which does download and install the repo's Appstream data.
As this adds a dependency on the `appstream` library, there is also a CMake option WITH_APPSTREAM to be able to turn the support off. The support is enabled by default.
-----------------------------------------
That is, the `/var/cache/libdnf5/$REPO_NAME/repodata/` directory can have downloaded also files with `appstream` in their name and, when installed, the data is stored under `/var/cache/swcatalog/xml/`.
CC @m-blaha @jan-kolarik

Support repo's Appstream data download and install

---

libdnf5-cli/output/transaction_table.cpp

Translators are recommend to align the messages to prevent from a broken table:
Podsumowanie transakcji:
Instalowanie:         6 pakietów
Aktualizowanie:         33 pakietów
Zastępowanie:         48 pakietów
Usuwanie:         199 pakietów
Relates: https://bugzilla.redhat.com/show_bug.cgi?id=2336561

I18N: Annotate indentation of the transaction summary

---

dnf5/commands/advisory/advisory_info.cpp
dnf5/commands/advisory/advisory_info.hpp
include/libdnf5-cli/output/advisoryinfo.hpp
libdnf5-cli/output/advisoryinfo.cpp

Enable --json for 'dnf advisory info'. The same information as would be displayed as text is included in the JSON output. While the libscols code could be adapted to produce JSON as well, without serious reworking of key_value_table (and all callers), the produced JSON is quite weird, so we instead choose to implement the JSON output separately.
Example output from `dnf5  advisory info --json FEDORA-2024-1ec4cd5fd3`:
```
{
"FEDORA-2024-1ec4cd5fd3":{
"Name":"FEDORA-2024-1ec4cd5fd3",
"Title":"libtirpc-1.3.6-1.fc41",
"Severity":"None",
"Type":"unspecified",
"Status":"stable",
"Vendor":"updates@fedoraproject.org",
"Issued":"2024-11-16 02:13:46",
"Description":"    - Fix regression in NVR\n    - Removed libtirpc-1-3-7-rc1 patch (bz 2325556)\n",
"Message":"",
"Rights":"Copyright (C) 2024 Red …
```

Add --json output to advisory info

---

CMakeLists.txt
common/CMakeLists.txt
dnf5-plugins/builddep_plugin/CMakeLists.txt
dnf5/CMakeLists.txt
dnf5daemon-client/CMakeLists.txt
dnf5daemon-server/CMakeLists.txt
libdnf5-cli/CMakeLists.txt
libdnf5/CMakeLists.txt
test/libdnf5/CMakeLists.txt

Closes: https://github.com/rpm-software-management/dnf5/issues/2003
The "libdnf5_static.a" object files archive was not packaged. It was only used in unit tests of the "libdnf5" library. The use of the archive in the "libdnf5" unit tests was intentional. The unit tests call private methods that have hidden symbols not exported by the shared library.
Now the `INTERFACE` library is defined instead of the object files archive. It specify usage requirements for dependents but does not produce a library artifact on disk. The "libdnf5" unit tests link directly to the object files without the need for an intermediate archive.

Optimize build process: Do not create object files archive library `libdnf5_static.a`

---

bindings/libdnf5/advisory.i
bindings/libdnf5/common.i
bindings/libdnf5/rpm.i
test/ruby/libdnf5/rpm/test_package_query.rb

Implement including Enumerable and the #each method for iterable collections.
This allows for example to iterate over a package query:
```ruby
require 'libdnf5/base'
base = Base::Base.new
base.setup()
repo_sack = base.get_repo_sack()
repo_sack.create_repos_from_system_configuration()
rq = Repo::RepoQuery.new(base)
rq.filter_id('rawhide')
repo_sack.load_repos(Repo::Repo::Type_AVAILABLE)
query = Rpm::PackageQuery.new(base)
query.filter_provides("rubygem(httparty)", Common::QueryCmp_EQ)
query.each # Returns => #<Enumerator: ...>
query.each do |pkg|
puts pkg.get_name
end
```
Related issue: #1780

Ruby Bindings: Implement Enumerable for iterable collections

---

dnf5/commands/history/arguments.hpp
dnf5/commands/history/history_info.cpp
dnf5/commands/history/history_info.hpp
dnf5/commands/history/history_list.cpp
dnf5/commands/history/history_list.hpp
doc/changes_from_dnf4.7.rst
doc/commands/group.8.rst
doc/commands/history.8.rst
doc/misc/specs.7.rst
include/libdnf5/transaction/transaction_history.hpp
libdnf5/transaction/db/trans.cpp
libdnf5/transaction/db/trans.hpp
libdnf5/transaction/transaction_history.cpp

Closes: https://github.com/rpm-software-management/dnf5/issues/667

Add --contains-pkgs=.. option to history list and info

---

doc/templates/command/arguments.hpp
doc/templates/command/template.cpp
doc/templates/command/template.hpp
doc/templates/template-command.rst
doc/templates/template-dnf5-plugin.rst

Recently on Fedora Discussions, [it was brought up / discovered](https://discussion.fedoraproject.org/t/dnf5-command-template-seems-to-have-bugs/141526) that the template source code in the DNF5 documentation had fallen a bit out of date, to the point where it wasn't even compilable because the internal APIs have changed so much in two years.
Since it actually says, right at the top of that page:
> #### Note
> This code is thought to be self explanatory. You should be able to copy the snippets, following the directory structure and naming shown above each one.
...It seemed clear that it was no longer remotely achieving that goal.
So, I went through and updated all of the included source code based on the current `dnf5/commands/` source and `dnf5/main.cpp`, built and tested the template …

Docs: Update template code, documentation page for the DNF5 Command Template

---

doc/changes_from_dnf4.7.rst

We have agreed that the new dnf5 behavior of simply listing all selected transactions is more expected.
Originally the merging was introduced 15 years ago in commits https://github.com/rpm-software-management/dnf/commit/6e949500aa3300c196f1cb82cef7d53795f79aac and
https://github.com/rpm-software-management/dnf/commit/b0581428c57a7ebfc1f6c9eb3d62ec5137e74e82

doc: `history info` no longer merges transactions

---

doc/commands/versionlock.8.rst

Document that the name = "<spec>" in the `/etc/dnf/versionlock.toml`
file supports globbing.
Resolves: https://github.com/rpm-software-management/dnf5/issues/1895

doc: Versionlock name specification supports globs

---

bindings/libdnf5/advisory.i
bindings/libdnf5/base.i
bindings/libdnf5/common.i
bindings/libdnf5/comps.i
bindings/libdnf5/conf.i
bindings/libdnf5/logger.i
bindings/libdnf5/plugin.i
bindings/libdnf5/repo.i
bindings/libdnf5/rpm.i
bindings/libdnf5/transaction.i
bindings/libdnf5/utils.i
bindings/ruby/CMakeLists.txt
test/ruby/libdnf5/base/test_base.rb
test/ruby/libdnf5/base_test_case.rb
test/ruby/libdnf5/logger/test_loggers.rb
test/ruby/libdnf5/repo/test_file_downloader.rb
test/ruby/libdnf5/repo/test_package_downloader.rb
test/ruby/libdnf5/repo/test_repo.rb
test/ruby/libdnf5/rpm/test_package_query.rb
test/ruby/libdnf5/rpm/test_package_query_set_operators.rb
test/ruby/libdnf5/utils/test_patterns.rb

See https://github.com/rpm-software-management/dnf5/issues/1779
The ruby/CMakeLists.txt also defined `-module` twice. Once "by hand" appending the raw `-module ${MODULENAME}` and then it is also added via the `set_property` for `SWIG_MODULE_NAME`. Once is enough, so I just deleted appending it to CLI and just adjusted the `set_property` call. This results in all constants in Ruby now prepended with `Libdnf5`, therefore preventing top-level constant collision (and allowing me to get on with my project).
By the way since setting SWIG_MODULE_NAME appends `-module` to swig CLI, it is overriding what is present in the files in the `%module` directive. Both Perl and Ruby are setting `-module` which makes specifying the module path via `%module` relatively useless even if there seems to be …

ruby bindings: Fix namespacing for libdnf5 classes/modules

---

dnf5-plugins/automatic_plugin/email_message.cpp
dnf5-plugins/automatic_plugin/email_message.hpp
dnf5-plugins/automatic_plugin/emitters.cpp
dnf5-plugins/automatic_plugin/emitters.hpp

The fix in 9a5cba8fbb0c95f5da1410803f9ff5093895252a (automatic: Fix end-of-lines in messages sent by email emitter) utilized cURL library for translating LF ending to CR-LF in content of SMTP DATA command. It fixed the problem with curl-8.11.1, but broke end-of-lines in e-mail headers with old curl-8.9.1.
I was unable to find what has changed in cURL, but the cause was that automatic plugin already separated headers by CR-LF, therefore cURL probably double-encoded them and that was again rejected by sendmail 8.18.1.
This patch reverts 9a5cba8fbb0c95f5da1410803f9ff5093895252a and instead performs the end-of-line normalization fully in dnf5::EmailMessage::str() method. Now the output of the method is completely valid e-mail message.
Implementation detail: I changed …

automatic: Translate end-of-lines in email emitter by DNF

---

include/libdnf5/common/impl_ptr.hpp
test/libdnf5/impl_ptr/test_impl_ptr.cpp

ImplPtr supports empty source (a source that owns nothing) in the copy and move constructor and in the move assignment operator. However, support for empty source in the copy assignment operator was missed.
Now there is support for empty source in the copy assignment operator as well. This makes the code consistent. In addition, the copy assigment operator can now be used for classes having an empty pointer to the implementation. For example, it is in the class as a placeholder for the future.
Unit tests included.

ImplPtr: Support for empty source in copy assignment operator, unit tests

---

bindings/libdnf5/utils.i
include/libdnf5/utils/bgettext/bgettext-mark-common.h
include/libdnf5/utils/format_locale.hpp
include/libdnf5/utils/locale.hpp
libdnf5/utils/bgettext/bgettext.c
libdnf5/utils/locale.cpp

New overloads of the `utils::format` method accept `BgettextMessage` as a format string. They allow to specify whether we want to translate the format string and define the `locale` used.

utils::format: Support for formatting localized messages (translation, localization of argument format) 

---

bindings/libdnf5/common.i
include/libdnf5/common/message.hpp
libdnf5/common/message.cpp

`common::Message`: A base abstract class for passing a message whose formatting, including localization (translation, argument format) is done at the destination.
`common::EmptyMessage`: class for passing an empty message
Closes: https://github.com/rpm-software-management/dnf5/issues/2034
Requires: https://github.com/rpm-software-management/dnf5/pull/2029
Requires: https://github.com/rpm-software-management/dnf5/pull/2031

Classes common::Message and common::EmptyMessage

---

dnf5/bash-completion/dnf5
dnf5/main.cpp
include/libdnf5-cli/argument_parser.hpp
libdnf5-cli/argument_parser.cpp

Closes: https://github.com/rpm-software-management/dnf5/issues/1990
- Added support for suggesting arguments for completion without adding a description in `cli:.ArgumentParser`
- Added support for suggesting command line arguments without descriptions in dnf5.
- Added support for "menu completion" in bash completion.

Argument completion without description, Bash completion "menu complete"

---

dnf5/library.cpp
dnf5/plugins.cpp
libdnf5/plugin/plugins.cpp
libdnf5/utils/library.cpp

Closes: https://github.com/rpm-software-management/dnf5/issues/2042
Fixes crash if plugin instantiation fails and returns a null pointer.

plugins: Check if the plugin instantiation was successful

---

doc/changes_from_dnf4.7.rst
libdnf5/repo/package_downloader.cpp

This translation will be used in a CI test which ensures upgrades work correctly with non-english locale and already downloaded packages.
https://github.com/rpm-software-management/ci-dnf-stack/blob/main/dnf-behave-tests/dnf/upgrade-cached.feature

Mark 'Already downloaded' for translations

---

dnf5.spec

Also add a dependency on the gpg command provider.

expired-pgp-keys: Install the plugin by default on Fedora 42+

---

bindings/libdnf5/plugin.i
dnf5-plugins/automatic_plugin/automatic_cmd_plugin.cpp
dnf5-plugins/builddep_plugin/builddep_cmd_plugin.cpp
dnf5-plugins/changelog_plugin/changelog_cmd_plugin.cpp
dnf5-plugins/config-manager_plugin/config-manager_cmd_plugin.cpp
dnf5-plugins/copr_plugin/copr_cmd_plugin.cpp
dnf5-plugins/needs_restarting_plugin/needs_restarting_cmd_plugin.cpp
dnf5-plugins/repoclosure_plugin/repoclosure_cmd_plugin.cpp
dnf5-plugins/reposync_plugin/reposync_cmd_plugin.cpp
dnf5/include/dnf5/iplugin.hpp
dnf5/plugins.cpp
include/libdnf5/plugin/iplugin.hpp
libdnf5-plugins/actions/actions.cpp
libdnf5-plugins/appstream/appstream.cpp
libdnf5-plugins/expired-pgp-keys/expired-pgp-keys.cpp
libdnf5-plugins/python_plugins_loader/python_plugins_loader.cpp
libdnf5-plugins/rhsm/rhsm.cpp
libdnf5/plugin/plugins.cpp

Closes: https://github.com/rpm-software-management/dnf5/issues/2047
To prevent function names from being mangled in the plugin API, these functions are linked as C language functions (extern "C"). We do not throw exceptions from these functions. Specifically, the `libdnf_plugin_new_instance` and
`dnf5_plugin_new_instance` functions return a null pointer on failure and discard the exception. Thus, the caller (libdnf library or dnf5 application) does not know the reason for the failure.
Changes:
- This modification extends the libdnf and dnf5 plugin APIs with new `libdnf_plugin_get_last_exception` and `dnf5_plugin_get_last_exception` functions. The plugin can save the exception instead of discarding it. The new functions allow access to the saved exception.
- All plugins have been modified …

Plugin API: *_plugin_get_last_exception: Return pointer to last exception

---

dnf5/plugins.cpp
libdnf5/plugin/plugins.cpp

Closes: https://github.com/rpm-software-management/dnf5/issues/1336
The original implementation threw an exception with a list of plugins that failed to load. We usually got the name of one configuration file. Information about the reason for the failure was not included in the exception.
Now the code throws an exception for the first failed plugin. Exception contains the full path (not just the filename) and includes the original exception from the source of the error.

load_plugins: Preserve original exception with failure information

---

CMakeLists.txt
bindings/CMakeLists.txt
bindings/go/CMakeLists.txt
bindings/python3/CMakeLists.txt

```cmake
set(FOO ${FOO} BAR BAZ)
set(FOO "${FOO};BAR;BAZ")
list(APPEND FOO BAR BAZ)
```
This PR replaces all remaining cargo-culted occurrences of `set()` being used to extend a list variable in CMake code, for which `list(APPEND)` is the appropriate command.
Not touched are calls like:
```cmake
set(FOO_STRING "${FOO_STRING} extended-string-stuff")
```
...which are not `list(APPEND)` equivalent.

CMake: Use list(APPEND FOO) over set(FOO ${FOO} ...)

---

doc/changes_from_dnf4.7.rst

The change happened in `from_repo` attribute of `Package`.
In dnf4 there was: https://github.com/rpm-software-management/dnf/blob/master/dnf/package.py#L82-L94

Document `list` command changed handling of installed packages repos

---

common/utils/deprecate.hpp
doc/api/c++/libdnf5.rst
doc/api/c++/libdnf5_config_main.rst
doc/api/deprecations.rst
doc/api/index.rst
doc/api/python/libdnf5_conf.rst
doc/api/python/libdnf5_conf_config_main.rst
include/libdnf5-cli/output/interfaces/repo.hpp
include/libdnf5/conf/config_main.hpp
include/libdnf5/repo/config_repo.hpp
include/libdnf5/repo/repo_sack.hpp
include/libdnf5/rpm/transaction_callbacks.hpp
libdnf5-plugins/expired-pgp-keys/expired-pgp-keys.cpp
libdnf5/conf/config_main.cpp
libdnf5/repo/config_repo.cpp
libdnf5/repo/repo_sack.cpp
test/libdnf5/conf/test_conf.cpp

It also adds `ConfigMain` to the docs (both cpp and python), mostly because it contains most of the deprecated API but it is an important class in general.
Closes: https://github.com/rpm-software-management/dnf5/issues/865

Unify marking of depraceted API, deprications page 

---

libdnf5/repo/repo_cache.cpp

Symlinks were followed when removing the libdnf5 cache. This is very dangerous.
Example:
A user extracted a package into the cache folder. And later runs `dnf clean all`. The package contained a recursive symlink, which terminated the deletion with a `filesystem error: status: too many levels of symbolic...` error.
Imagine what would happen if there was a symlink outside the cache. Like a link to "/home", "/"...
Closes: https://github.com/rpm-software-management/dnf5/issues/2059

Fix RepoCache::Impl::remove_recursive: Do not follow symlinks

---

libdnf5-plugins/rhsm/rhsm.cpp
libdnf5/base/transaction.cpp
libdnf5/rpm/package.cpp
libdnf5/utils/locker.cpp

An application that uses libdnf can create a child process (`fork`) in another thread and execute the program in it.  This will leak open descriptors to the newly executed program.
The close-on-exec flag (`O_CLOEXEC`) ensures that the descriptors are closed and not passed to the newly running program (they are closed).

Create a pipe and open files with the close-on-exec flag

---

dnf5/context.cpp

Normally, the script start callback is called after package verification has been done, so there is an active progress bar (created in the verification stage), however package verification can be disabled. If verification is disabled, then the script start callback is the first callback used (to run pre-trans scripts), and there will be no active progress bar, leading to a crash.
To handle the case of disabled verification, create a new progress bar in the script start callback for it to use in the future.
Fixes https://github.com/rpm-software-management/dnf5/issues/1949

Create progress bar in script callback if one doesn't already exist

---

dnf5/commands/offline/offline.cpp
dnf5/context.cpp

Before the transaction, the total number of steps needed and thus the progress bars needed is calculated. The original calculation assumed that if new packages enter the system through transactions, the first step would be to verify them. However, package verification can be disabled.
This modification will add the verification step to the total number of steps only if verification is performed.
Closes: https://github.com/rpm-software-management/dnf5/issues/2079

Fix total number of transaction progress bars

---

libdnf5-plugins/expired-pgp-keys/expired-pgp-keys.cpp

The gpg provider is now a hard dependency in the spec file.
Follow-up on: #2051.

expired-pgp-keys: Drop checking for gpg command

---

dnf5/commands/offline/offline.cpp

This patch resolves two issues:
- Incorrect creation of std::vector<std::string> from the D-Bus variant.
- Incorrect session handling in the offline command (notable with sdbus-cpp v2).
These issues caused the dnf offline reboot command to break.

Fix D-Bus Communication Issues

---

doc/changes_from_dnf4.7.rst

Document difference between dnf4 and dnf5 versions of the dnf automatic
behavior regarding to the `emitters.send_error_messages` configuration
option.
Fixes: https://github.com/rpm-software-management/dnf5/issues/1965

doc: Removal of send_error_messages in automatic

---

bindings/ruby/CMakeLists.txt
test/ruby/CMakeLists.txt

Since cmake 4.0.0 version.
https://cmake.org/cmake/help/git-stage/policy/CMP0185.html
https://cmake.org/cmake/help/latest/module/FindRuby.html

FindRuby no longer provides upper-case RUBY_* variables

---

dnf5/commands/system-upgrade/system-upgrade.cpp
dnf5daemon-client/commands/system-upgrade/system-upgrade.cpp
dnf5daemon-client/commands/system-upgrade/system-upgrade.hpp
dnf5daemon-server/services/rpm/rpm.cpp
libdnf5/base/goal.cpp
libdnf5/transaction/transaction_sr.cpp

Closes: https://github.com/rpm-software-management/dnf5/issues/1817
Test update: https://github.com/rpm-software-management/ci-dnf-stack/pull/1641

Add comps upgrade to system upgrade, comps improvements

---

doc/changes_from_dnf4.7.rst

Document that DNF5 stopped supporting a separator after a short option.
Resolves #1353

doc: No value separator after short options

---

libdnf5/repo/repo_sack.cpp

In `repo::RepoSack::update_and_load_repos`, log and ignore errors related to reading or downloading GPG keys if we are using `skip_if_unavailable=false`
Resolves https://github.com/rpm-software-management/dnf5/issues/2065

repo: ignore key download errors if `skip_if_unavailable`

---

dnf5/commands/system-upgrade/system-upgrade.cpp
dnf5/commands/system-upgrade/system-upgrade.hpp
doc/commands/system-upgrade.8.rst

This patch adds the --allowerasing option to the `dnf system-upgrade download`
command. It helps users resolve dependency issues during the system upgrade.
The use of this option is even documented in the Fedora documentation:
https://docs.fedoraproject.org/en-US/quick-docs/upgrading-fedora-offline/
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2349754

system-upgrade: Add --allowerasing switch

---

doc/changes_from_dnf4.7.rst
doc/dnf5.conf-todo.5.rst
include/libdnf5/conf/config_main.hpp
libdnf5/conf/config_main.cpp

The option (along with the metadata_timer_sync config option) was dropped in favor of systemd settings.
Fixes: https://github.com/rpm-software-management/dnf5/issues/812

doc: Document dropping of makecache --timer option

---

dnf5/commands/offline/offline.cpp
dnf5/context.cpp
dnf5/include/dnf5/context.hpp
dnf5/main.cpp
include/libdnf5/repo/repo_sack.hpp
libdnf5/base/goal.cpp
libdnf5/repo/repo.cpp
libdnf5/repo/repo_sack.cpp

This is alternative solution to https://github.com/rpm-software-management/dnf5/pull/2061
Currently, when replaying a stored transaction, all RPM files are placed
into a single `@stored_transaction` repository. The user can see this
artifitial repository when checking from which repositories the installed
packages came:
❯ dnf repoquery --installed --queryformat="%{full_nevra} %{from_repo}\n" 
vlc-plugin-gstreamer-1:3.0.21-15.fc40.x86_64 @stored_transaction
This can be confusing, especially during a system upgrade, which also uses
stored transactions.
With this patch, local RPM files from stored transactions are placed to the
repository they originally came from:
❯ dnf repoquery --installed --queryformat="%{full_nevra} %{from_repo}\n" 
vlc-plugin-gstreamer-1:3.0.21-15.fc40.x86_64 updates …

Use actual repository ID in stored transactions v2

---

libdnf5-cli/progressbar/download_progress_bar.cpp

Handle situations, when the message (or even the prefix) is wider than 
available terminal size.
Fixes: https://github.com/rpm-software-management/dnf5/issues/2085

progressbar: Messages printing on narrow terminal

---

dnf5-plugins/config-manager_plugin/CMakeLists.txt
dnf5-plugins/config-manager_plugin/addrepo.cpp
dnf5.spec

Replace the in-tree crc32() function with calls to zlib.  The only place I found the crc32 code was in was the config-manager plugin.
Fixes: SWM-1579

Replace in-tree crc32() with a call to zlib

---

.packit.yaml

This reverts commit b1b72a245f9fa30a378a78ca74007965a78b739a.
We use GitHub to autogenerate upstream release notes that list the PRs that were merged since the last release. But these release notes are not appropriate to include in downstream RPM changelogs; they include GitHub usernames, links to pull requests, possibly special characters that could be interpreted as RPM macros [1], and are long.
Let's use `copy_upstream_release_description: false` which will make a one-line changelog entry with `Update to version x.y.z.p` which is what you see on Fedora packages that use %autochangelog, which is recommended by the Fedora packaging guidelines.
[1] https://packit.dev/docs/configuration#copy_upstream_release_description

Revert "Packit: use GH's release notes for downstream changelog"

---

dnf5.spec

To reflect changes in df97dfb075b67b206a9c06dba49d2eef43b76f4e (Increase CMake minimum required version to 3.21).

spec: Set cmake minimal version to 3.21

---

dnf5/commands/offline/offline.cpp

Fixing the following error when building with WITH_SYSTEMD=OFF
> /build/source/dnf5/commands/offline/offline.cpp:54:7: error: 'sdbus' does not name a type
>    54 | const sdbus::ObjectPath SYSTEMD_OBJECT_PATH{"/org/freedesktop/systemd1"};

offline: only define systemd constants when building with systemd 

---

dnf5-plugins/copr_plugin/copr_repo.cpp
dnf5-plugins/copr_plugin/copr_repo.hpp

Constructing incomplete (with `base` set to `nullptr`) instances of `CoprRepo` is not a good idea. It is only a matter of time before someone uses this invalid `base`.
In fact, this is why PR https://github.com/rpm-software-management/dnf5/pull/2081 causes segfault in copr_plugin unit tests.

Fix dnf5 copr_plugin: always set `base` in `CoprRepo`

---

libdnf5-plugins/expired-pgp-keys/expired-pgp-keys.cpp
libdnf5/rpm/rpm_signature.cpp

headerGetAsString() returns a pointer which the caller must free. Also if the call fails, it will return NULL and later std::string == operator will exhibit an undefined behviour (confirmed with an address sanitizer).
There were two places of the flawed code in
libdnf5::rpm::rpmdb_lookup() and in expired-pgp-keys plugin. This patch fixes both. Though the latter will be reimplemented later.

Fix a memory leak when looking up for an OpenPGP key in RPM database

---

CMakeLists.txt
dnf5.spec
doc/changes_from_dnf4.7.rst
doc/conf.py.in

Some maintainers of Fedora presets would prefer that the dnf-makecache timer use the unversioned name so that the presets (and Ansible playbooks, etc) do not need to be updated to account for renaming it. This change would create a file conflict between the "dnf" and "dnf5" packages in Fedora, but it's already impossible to install them simultaneously because dnf5 "obsoletes" the old dnf package.
This PR will use the unit name "dnf-makecache" when "dnf5_obsoletes_dnf", and "dnf5-makecache" when it does not obsolete dnf.
@keszybz @Conan-Kudo

Rename dnf5-makecache timer to dnf-makecache when dnf5_obsoletes_dnf

---

dnf5-plugins/copr_plugin/copr_disable.cpp
dnf5-plugins/copr_plugin/copr_enable.cpp
dnf5-plugins/copr_plugin/copr_remove.cpp
dnf5-plugins/copr_plugin/copr_repo.cpp
dnf5-plugins/copr_plugin/copr_repo.hpp

This creates repofiles in `installroot` to respect its location. However `dnf4 copr` behaves the same way as `dnf5 copr` with `--use-host-config`:
```
[root@7223880ab7fc tmp]# dnf4 copr enable @copr/copr-ping --installroot=/tmp/dnf4 -y
...
[root@7223880ab7fc tmp]# tree
.
└── dnf4
├── usr
│   └── lib
│       └── sysimage
│           └── rpm
│               ├── rpmdb.sqlite
│               ├── rpmdb.sqlite-shm
│               └── rpmdb.sqlite-wal
└── var
├── cache
│   └── dnf
│       └── expired_repos.json
└── log
├── dnf.librepo.log
├── dnf.log
└── dnf.rpm.log
10 directories, 7 files
[root@7223880ab7fc tmp]#
```
the repofile is created inside `/etc/yum.repos.d`, the installroot is ignored.
```
[root@7223880ab7fc tmp]# ls /etc/yum.repos.d/ …
```

Fix: let copr plugin to respect the installroot option

---

dnf5.spec

That directory is used by libdnf5. dnf5daemon-client and dnf5daemon-server is independent on dnf5.

spec: Move /usr/lib/sysimage/libdnf5 from dnf5 to libdnf5

---

dnf5/plugins.cpp
include/libdnf5/common/exception.hpp
libdnf5-plugins/actions/actions.cpp
libdnf5/conf/config_parser.cpp
libdnf5/plugin/plugins.cpp
libdnf5/repo/file_downloader.cpp
libdnf5/repo/package_downloader.cpp
libdnf5/repo/repo_downloader.cpp

Throws an exception that also stores the currently active exception.
It does the same thing as `std::throw_with_nested(TException && ex)`, except that instead of an **unspecified** type that is publicly derived from both `std::nested_exception` and `std::decay<TException>::type`, it throws a type **`NestedException<std::decay<TException>::type>`** that is publicly derived from both `std::nested_exception` and `std::decay<TException>::type`.
In other words, it replaces the unspecified type (the type defined by the implementation in the standard library) with our specification. Knowing the type can simplify exception handling in some cases. For example, avoiding the need to define another type for SWIG.

Implement libdnf5::throw_with_nested: throws our nested exception type

---

libdnf5/repo/repo_sack.cpp

Resolves https://github.com/rpm-software-management/dnf5/issues/2134, which is a regression caused by commit 0f1242b0.
`std::rethrow_if_nested` is useless if we first slice the `std::nested_exception` to a `std::exception`. We must call `std::rethrow_if_nested` on a instance of a type derived from (or convertible to?) `std::nested_exception` [1].
[1] https://en.cppreference.com/w/cpp/error/rethrow_if_nested
We are still missing tests for repo_gpgcheck in ci-dnf-stack, but we should fix https://github.com/rpm-software-management/dnf5/issues/2134 and cut a new release ASAP.

repo: fix bad GPG error handling

---

dnf5/context.cpp
libdnf5-plugins/expired-pgp-keys/expired-pgp-keys.cpp

There was a flaw in what this plugin did: Instead of checking an expiration time of the keys in an RPM database, it downloaded keys of enabled repositories from the Internet and checked their expiration time. As a side effect, this plugin repeatedly downloaded the keys on every invocation.
This patch fixes both the issues by checking keys which are in the RPM database instead.
The new implementation removes all expired and confirmed keys in a single RPM transaction. It also removes the unnecessary crosscheck that a key obtained from an RPM database axtually exists in the database. All that speeds up the operation at the expense that reporting a success of the removal happens after the user selecting all the keys for the removal.
The user query now reports a fingerprint instead of a path …

expired-pgp-keys: Fix checking expiration of keys in RPM database

---

dnf5.spec

Ghost files (files tracked by RPM, but missing a content) default their file mode to 0000. Especially dnf5-plugin-automatic package has configuration files which we want to have 0644 mode to be readable for all users. Without specifying an explicit mode, "rpm --verify" failed for those files once a user crated them with a non-0000 mode.
This patch fixes this issue by specifying mode for all ghost files. That also implied listing all files under /usr/lib/sysimage/libdnf5 as there is a mix of regular files and directories. (Also a glob for ghost files cannot work because those do not exist when building the package.)
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2343342

spec: Set mode to ghost files

---

dnf5.spec

Those files brings a value for users wanting to know what has changed between DNF5 releases, or where to find more help.
I placed them into dnf5 binary package instead of libdnf5 binary package to minimize libdnf5 footprint and because /usr/share/doc/dnf5 is probably the first directory people search.

spec: Package CHANGELOG and other project documentation files

---

dnf5/main.cpp
doc/changes_from_dnf4.7.rst
doc/dnf5.8.rst
include/libdnf5-cli/tty.hpp
libdnf5-cli/output/argument_parser.hpp
libdnf5-cli/output/environmentinfo.cpp
libdnf5-cli/output/environmentlist.cpp
libdnf5-cli/output/groupinfo.cpp
libdnf5-cli/output/grouplist.cpp
libdnf5-cli/output/key_value_table.cpp
libdnf5-cli/output/modulelist.cpp
libdnf5-cli/output/package_list_sections.cpp
libdnf5-cli/output/packageinfo.cpp
libdnf5-cli/output/repolist.cpp
libdnf5-cli/output/transaction_table.cpp
libdnf5-cli/output/transactioninfo.cpp
libdnf5-cli/output/transactionlist.cpp
libdnf5-cli/progressbar/download_progress_bar.cpp
libdnf5-cli/tty.cpp

resolves: https://github.com/rpm-software-management/dnf5/issues/839
related: https://github.com/QubesOS/qubes-issues/issues/9482

Reimplement `--color` flag

---

doc/dnf5.8.rst

The list of variables for temporary files is copied from std::filesystem::temp_directory_path() as it the fuction which uses them.
I intentionally left out FORCE_CULUMNS. We should rename it to DNF5_FORCE_COLUMNS before documenting it and make a transaction table to respect it.
Resolve <https://bugzilla.redhat.com/show_bug.cgi?id=2353349>

doc: Environment variables for a terminal and temporary files

---

libdnf5/repo/librepo.cpp

resolves: https://github.com/rpm-software-management/dnf5/issues/1003

Improve missing `proxy_password` message

---

libdnf5/solv/pool.hpp

There is no guarantee that the considered map is valid during the swap. For example, in this scenario, the already invalid considered map is swapped to a nullptr and later restored to its original (invalid) value:
- If modules are enabled and available, one of the last steps in `load_repos()` is applying module_filtering, which also recomputes the considered map.
- During the goal resolution, command-line packages are added, increasing the number of solvables in the pool. This invalidates the `considered_map`, but it is not recomputed.
- After adding command-line packages, excludes are reloaded. As part of setting versionlock excludes, `make_provides_ready()` is called (via the `PackageQuery` constructor).
- At this point, the considered map is invalid and smaller than the current number …

solv: Drop the size check from swap_considered_map

---

dnf5.spec

Write "repo" in full and capitalize AppStream correctly.

spec: Correct libdnf5-plugin-appstream description

---

dnf5/commands/environment/environment_info.cpp
dnf5/commands/environment/environment_list.cpp
dnf5/commands/group/group_info.cpp
dnf5/commands/group/group_list.cpp
include/libdnf5/comps/environment/environment.hpp
include/libdnf5/comps/group/group.hpp
libdnf5-cli/output/environmentlist.cpp
libdnf5-cli/output/grouplist.cpp
libdnf5/comps/environment/environment.cpp
libdnf5/comps/group/group.cpp
test/libdnf5/comps/test_environment.cpp
test/libdnf5/comps/test_group.cpp

Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1655

comps: Respect the display_order with listing groups and environments

---

dnf5/commands/download/download.cpp
doc/commands/download.8.rst

resolves: https://github.com/rpm-software-management/dnf5/issues/1151

Disallow `dnf download non-sense` without `--skip-unavailable`

---

include/libdnf5/rpm/nevra.hpp

This PR adjsuts description of both functions to actual [one](https://github.com/rpm-software-management/rpm/blob/master/rpmio/rpmvercmp.cc):
```
/* return 1: a is newer than b */
/*        0: a and b are the same version */
/*       -1: b is newer than a */
int rpmvercmp(const char * a, const char * b);
```
Issue: https://github.com/rpm-software-management/dnf5/issues/2187

nevra: Fix description of evrcmp and rpmvercmp functions

---

dnf5/commands/environment/environment_info.cpp
dnf5/commands/environment/environment_list.cpp
dnf5/commands/group/group_info.cpp
dnf5/commands/group/group_list.cpp
dnf5daemon-client/commands/group/group_list.cpp
dnf5daemon-client/wrappers/dbus_environment_wrapper.hpp
dnf5daemon-client/wrappers/dbus_group_wrapper.hpp
dnf5daemon-server/group.cpp
dnf5daemon-server/group.hpp
dnf5daemon-server/services/comps/group.cpp
dnf5daemon-server/services/goal/goal.cpp
include/libdnf5-cli/output/adapters/comps_tmpl.hpp
include/libdnf5-cli/output/interfaces/comps.hpp
include/libdnf5/comps/environment/environment.hpp
include/libdnf5/comps/group/group.hpp

This is a follow up to: https://github.com/rpm-software-management/dnf5/pull/2164
It is also needed for: https://github.com/rpm-software-management/ci-dnf-stack/pull/1661
It also unifies duplicated handling of group attributes in the daemon which was need for it to compile after adding the `order_int`.

Add group ordering by orider_int to dnf5daemon

---

libdnf5/repo/solv_repo.cpp

The debug message in `SolvRepo::load_system_repo()` did not respect the
value of the `installroot` option, always logging misleading "/" as the
root directory for loading the rpmdb.
This patch updates the message to correctly reflect the configured
installroot path.

repo: Log correct path when loading system repo

---

dnf5.spec
dnf5daemon-server/CMakeLists.txt
dnf5daemon-server/config/etc/dnf/dnf5daemon-server.conf
dnf5daemon-server/const.hpp
dnf5daemon-server/session.cpp
doc/dnf_daemon/dnf5daemon_server.8.rst
include/libdnf5/conf/option.hpp
libdnf5/repo/repo.cpp
libdnf5/repo/repo_sack.cpp

Introduce a separate dnfdaemon configuration file for daemon specific config overrides - currently it overrides only the `cachedir` option.

dnfdaemon: Configure separate cache directory

---

.github/workflows/do-release.yaml

`RELEASEBOT_GITHUB_TOKEN` has expired or for whatever reason no longer has access to the DNF 5 GitHub repository, so our "Create a GitHub release once a PR is merged" workflow has been failing. Instead, use a private key for the RSM CI GitHub App to dynamically create a GitHub token and use that to authenticate. The RSM CI private key should never expire [1]. This pattern is already used in `backport.yml`.
[1] https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/managing-private-keys-for-github-apps

ci: Use RSM_CI_APP_PRIVATE_KEY in do-release.yaml

---

include/libdnf5/repo/repo_cache.hpp
libdnf5/repo/repo_cache.cpp
libdnf5/repo/repo_cache_private.hpp

On 32-bit systems, size_t is not large enough to represent the amount of freed space if it exceeds 4GiB. We should use a uintmax_t here instead.
Supersedes https://github.com/rpm-software-management/dnf5/pull/2213.

RepoCacheRemoveStatistics::get_bytes_removed return uintmax_t

---

doc/changes_from_dnf4.7.rst
doc/dnf5.conf-deprecated.5.rst
doc/dnf5.conf.5.rst
include/libdnf5/conf/config_main.hpp
include/libdnf5/repo/config_repo.hpp
libdnf5/repo/config_repo.cpp

Following options are deprecated: `retries`, `deltarpm`, `deltarpm_percentage`.
Resolves: https://github.com/rpm-software-management/dnf5/issues/1928

Deprecate deltarpm support in dnf5

---

bindings/libdnf5/rpm.i

This would simplify comparison of Nevra objects:
```python
import libdnf5
def parse_nevra(nevra_str):
form_nevra = libdnf5.rpm.VectorNevraForm(1, libdnf5.rpm.Nevra.Form_NEVRA)
nevra = libdnf5.rpm.Nevra.parse(nevra_str, form_nevra)[0]
return nevra
def less(lhs, rhs):
for attr in ["get_epoch", "get_version", "get_release"]:
r = libdnf5.rpm.rpmvercmp(getattr(lhs, attr)(), getattr(rhs, attr)())
if r != 0:
return r == -1
return False
if __name__ == "__main__":
old = parse_nevra("foo-1.2.2-1.fc41.x86_64")
new = parse_nevra("foo-1.2.3-2.fc41.x86_64")
assert(less(old, new) and libdnf5.rpm.cmp_nevra(old, new) == True)
assert(less(old, old) or libdnf5.rpm.cmp_nevra(old, old) == False)
assert(less(new, old) or libdnf5.rpm.cmp_nevra(new, old) == False)
```

bindings: Add Python cmp_nevra binding

---

dnf5/commands/download/download.cpp

The "Downloading Packages:" header was printed irresspective of --quiet option:
Downloading Packages:
#
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2362032

download: Do not print "Downloading Packages:" header in quiet mode

---

libdnf5/rpm/transaction_callbacks.cpp

For clarity, the names of the scriptlet types should match how they are defined in spec files.
For https://github.com/rpm-software-management/dnf5/issues/2170.

Change scriptlet names to match spec designators

---

doc/changes_from_dnf4.7.rst

Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2270024

doc: "dnf4 config-manager" dropped --dump and --dump-variables options

---

dnf5.spec
libdnf5-plugins/expired-pgp-keys/CMakeLists.txt
libdnf5-plugins/expired-pgp-keys/expired-pgp-keys.cpp

RPM 6 warns on removing a key by a gpg-pubkey package name:
warning: erasing gpg-pubkey packages is deprecated; use rpmkeys --delete 326785684e6adf5ac523b673c77c028403690624
RPM 6 has rpmtxnDeletePubkey() as a replacement.
This patch keeps using the old way on RPM < 6 and uses
rpmtxnDeletePubkey() on RPM 6 because rpmtxnDeletePubkey() is
available since RPM 5.99.90. The RPM version is detected at build time
and enforced at run-time with a dependency on
libdnf5-plugin-expired-pgp-keys package level.
I successfully tested it on Fedora 43 and Fedora 41.

expired-pgp-keys: Do not use a deprecated way of removing keys with RPM v6

---

CMakeLists.txt
dnf5.spec
libdnf5/CMakeLists.txt

We already require librepo 1.18.0 which contains the needed fixes related to zchunk.
https://github.com/rpm-software-management/librepo/commit/66c99da1206c96fefc1b8279f777afefb79dc614, https://github.com/rpm-software-management/librepo/commit/e2abd5dd2c1bf3a644de3bcb08c874185a0bd1e9
For: https://github.com/rpm-software-management/dnf5/issues/1233

Remove unused `WITH_ZCHUNK` option

---

dnf5/commands/offline/offline.cpp

That prevents the translators from rearanging words in the messages.

I18N: Do not glue sentences in offline command messages

---

dnf5/main.cpp

When setting --no-gpgchecks, dnf5 fails to override localpkg_gpgcheck which is not the expectation.  This breaks compatibility with dnf4.
$ dnf4 --version | head -n1
4.23.0
$ dnf4 config-manager --dump | grep gpgcheck
gpgcheck = 1
localpkg_gpgcheck = 1
repo_gpgcheck = 0
$ dnf4 --nogpgcheck config-manager --dump | grep gpgcheck
gpgcheck = 0
localpkg_gpgcheck = 0
repo_gpgcheck = 0
$ dnf5 --version | head -n1
dnf5 version 5.2.13.1
$ dnf5 --dump-main-config | grep gpgcheck
gpgcheck = 1
localpkg_gpgcheck = 1
pkg_gpgcheck = 1
repo_gpgcheck = 0
$ dnf5 --nogpgcheck --dump-main-config | grep gpgcheck
gpgcheck = 0
localpkg_gpgcheck = 1
pkg_gpgcheck = 0
repo_gpgcheck = 0
$ dnf5 --no-gpgchecks --dump-main-config | grep gpgcheck
gpgcheck = 0
localpkg_gpgcheck = 1
pkg_gpgcheck = 0
repo_gpgcheck = 0 …

dnf5: --no-gpgchecks overrides localpkg_gpgcheck

---

dnf5/commands/advisory/advisory_subcommand.cpp
dnf5/commands/advisory_shared.hpp
dnf5/commands/check-upgrade/check-upgrade.cpp
dnf5/commands/install/install.cpp
dnf5/commands/repoquery/repoquery.cpp
dnf5/commands/upgrade/upgrade.cpp
doc/_shared/options/advisories.rst
doc/_shared/options/bzs.rst
doc/_shared/options/cves.rst
include/libdnf5/base/goal_elements.hpp
libdnf5/base/goal.cpp
libdnf5/base/log_event.cpp

Resolves two use-cases:
1. The user is informed if there is no existing advisory in the `--advisories=...` list. Additionally, the transaction commands that support this option (install, upgrade) will fail with exit code 1.
```
❯ dnf5 install --advisories=foo hello
Repositories loaded.
No advisory found matching the requested name: "foo"
```
2. If the user tries to install or upgrade a package not present in the requested (and existing) advisories, the command prints a warning and fails with exit code 1 (unless the `--skip-unavailable` switch is present).
```
❯ dnf install --advisories=FEDORA-2025-77ace1a41b hello
Repositories loaded.
Failed to resolve the transaction:
No match for argument 'hello' in advisories
```
Resolves: https://github.com/rpm-software-management/dnf5/issues/784 …

Report specs filtered out by advisories

---

bindings/ruby/CMakeLists.txt

The clang build is failing due to a deprecation warning, reported to swig: https://github.com/swig/swig/issues/3170.
Temporarily disable the warning to have a working clang build.
I would like to wait for: https://github.com/rpm-software-management/dnf5/pull/2238 so we can verify it fixes the problem and that the build uses the PR. However technically this doesn't depend on the linked PR.

Fix clang build by disabling ruby deprecation warning

---

.packit.yaml

This can sometimes be useful when one package (libdnf5) depends on a new unreleased release of another (librepo).

Include dnf-nightly in packit copr builds

---

doc/changes_from_dnf4.7.rst
doc/commands/repoquery.8.rst

"dnf5 repoquery --qf" does not append newlines. This change was documented, but it was not mentioned how to achieve the newlines.
Related: #2249

doc: Document '\n' sequence in repoquery --queryformat string

---

dnf5/commands/do/do.cpp
dnf5/commands/do/do.hpp
dnf5/main.cpp

Closes: https://github.com/rpm-software-management/dnf5/issues/1223
Required modification of CI tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1677
Example - Installing "pkg1" and "pkg2" from repositories whose repoid matches "my_repo*", installing "pkg3" from the "fedora" repository, and upgrading "pkg4" from the "my_repo_updates" repository. The required dependencies can be taken from all enabled repositories:
`dnf do --action=install --use-repo='my_rep*' pkg1 pkg2 --use-repo=fedora pkg3 --action=upgrade --use-repo=my_repo_updates pkg4`

dnf5: Command "do"

---

doc/changes_from_dnf4.7.rst

Resolves https://bugzilla.redhat.com/show_bug.cgi?id=2324177.
See also https://github.com/rpm-software-management/dnf/issues/2242.

changes_from_dnf4: makecache doesn't always refresh

---

dnf5daemon-server/dbus/interfaces/CMakeLists.txt
doc/dnf_daemon/dnf5daemon_dbus_api.8.rst

Updates the dnf5daemon doc to include the missing interfaces
org.rpm.dnf.v0.Base
org.rpm.dnf.v0.Offline
Also reorded the order of the interfaces in a more logical order of how the API will med used
Ex. SessionManager is the first one to be used.
I have made a local build with
```
cmake -B .build
cmake --build .build -t doc
```
An everything looks fine.

Add missing interfaces and re-order interfaces in a more logical order

---

dnf5-plugins/reposync_plugin/reposync.cpp

DNF5 calls the signature technology OpenPGP.

reposync: Spell "GPG" as "OpenPGP" in the usage text

---

dnf5-plugins/automatic_plugin/email_message.cpp
test/dnf5-plugins/CMakeLists.txt
test/dnf5-plugins/automatic_plugin/CMakeLists.txt
test/dnf5-plugins/automatic_plugin/EmailMessage.cpp
test/dnf5-plugins/automatic_plugin/EmailMessage.hpp
test/dnf5-plugins/automatic_plugin/test.cpp

"email" emitter produced Date: header with fractional seconds:
Date: Sat, 31 May 2025 10:28:45.162419022 +0000
That violates RFC 5322 and some SMTP implementations reject messages with this mistake.
The cause was in fmt::format("{%S}") which formats non-integral seconds as a fractional number
<https://fmt.dev/11.1/syntax/#chrono-format-specifications>.
This patch fixes it by using std::chrono::time_point with second precision before passing it to fmt::format().

automatic: email emitter: Do not use fractional seconds in e-mail Date headers

---

dnf5.spec

Since it only provides a plain text file, there's no need to distribute
an arch specific package.

Mark dnf5daemon-server-polkit as noarch

---

dnf5/cmdline_aliases.cpp

Added missing `plural_form` argument to format function. Also included exception output to stderr for more detailed error reporting.

[dnf5] cmdline_aliases: Fix TOML syntax err msg in build TOML11_COMPAT

---

dnf5-plugins/automatic_plugin/emitters.cpp

If /etc/dnf/automatic.conf has:
[emitters]
emit_via = command_email
[command_email]
email_to = root,test
a command incompatible with s-nail-14.9.25, a "mail" command implementation, was executed:
execve("/bin/sh", ["sh", "-c", "--", "mail -Ssendwait -s "[fedora-43] dnf5-automatic: 49 new upgrades have been downloaded." -r "root" "root test""], ...)
The cause was that s-nail does not support multiple recipients in a single argument.
This patch changes how "{email_to}" expands in command_format formatting string. Now it expands into multiple, space separated arguments. The new syntax is also accepted by mailx tool.
This patch also amends a documentation to explain how to configure multiple recipients.
A test will be added to ci-dnf-stack repository.
Resolve: #2273
Test: …

automatic: Expand emit_via in command_email emitter to individual arguments

---

test/python3/libdnf5/base/test_goal.py
test/python3/libdnf5/conf/test_option.py
test/python3/libdnf5/logger/test_global_logger.py

Building dnf5 with Arch Linux's build tooling fails as an absolute path is recorded instead of an absolute path:
AssertionError: "^libdnf5/logger/global_logger.cpp:[0-9]+: libdnf5::GlobalLogger::GlobalLogger\(\): API Assertion 'librepo_logger == nullptr' failed: Only one GlobalLogger can exist at a time" does not match
"/usr/src/debug/dnf5/dnf5-5.2.13.0/libdnf5/logger/global_logger.cpp:33: libdnf5::GlobalLogger::GlobalLogger(): API Assertion 'librepo_logger == nullptr' failed: Only one GlobalLogger can exist at a time"
Closes: #2250

test: ease path assertions in tests

---

README.md

Users reporting mistakes in translations needs to be directed to Fedora Weblate.

doc: Handling translations

---

dnf5daemon-server/dbus.hpp
dnf5daemon-server/dbus/interfaces/CMakeLists.txt
dnf5daemon-server/dbus/interfaces/org.rpm.dnf.v0.History.xml
dnf5daemon-server/services/history/history.cpp
dnf5daemon-server/services/history/history.hpp
dnf5daemon-server/session.cpp
doc/dnf_daemon/dnf5daemon_dbus_api.8.rst
include/libdnf5/advisory/advisory_query.hpp
include/libdnf5/advisory/advisory_set.hpp
libdnf5/advisory/advisory_package_private.hpp
libdnf5/advisory/advisory_query.cpp
libdnf5/advisory/advisory_set.cpp
test/libdnf5/advisory/test_advisory_query.cpp
test/libdnf5/advisory/test_advisory_query.hpp

Create a new D-Bus interface to retrieve information from the dnf5
transaction history. The new History interface currently supports only
one method: "recent_changes". This method retrieves information from the
history database about changes in the installed package set since the
specified point in time.
Resolves: https://github.com/rpm-software-management/dnf5/issues/773

dnfdaemon: Add new History interface

---

dnf5daemon-server/services/goal/goal.cpp

The method does not return any output parameters.
Resolves: https://github.com/rpm-software-management/dnf5/pull/2317

dnfdaemon: Removed incorrect output parameter names

---

dnf5daemon-server/services/base/base.cpp
dnf5daemon-server/services/offline/offline.cpp

Change permissions required for:
- clean cache
- clean or cancel offline transaction (only before the rpm transaction begins)
- set finish action after offline transaction (reboot or poweroff)
Currently the main user of these APIs is gnome software which can (if
the dnf5daemon-server-polkit package is installed) allow wheel group
users to install/upgrade packages from configured repositories without
being prompted for passwords. We need to set the same checks also for
offline transaction management APIs. Otherwise the user is allowed to
prepare an offline transaction, but is prompted for a password anyway
due to the `set_finish_action()` call that is executed after the
packages are downloaded and the offline transaction is prepared and
stored.
This change is needed to unblock gnome …

dnfdaemon: Make permission check more consistent

---

README.md

The POT files are actually generated by GitHub and pushed to dnf5-l10n and the translations are commited into this repository.

doc: Correct handling the translations

---

dnf5.spec

Add the base package dependency for the dnf5daemon-server-polkit
subpackage to ensure that dnf5daemon-server also gets updated when the
polkit rule changes.
Resolves: https://github.com/rpm-software-management/dnf5/issues/2313

Add dnf5daemon-server requirement for polkit subpkg

---

dnf5/commands/distro-sync/distro-sync.cpp
dnf5/commands/distro-sync/distro-sync.hpp
doc/commands/distro-sync.8.rst
libdnf5/base/goal.cpp

The `--from-repo` argument allows the user to run `distro-sync` on packages in the specified repositories. However, any dependency resolution takes into account packages from all allowed repositories.
Multiple repository ids can be specified, separated by commas, and globs can be used. Usage is similar to the `install` command.
Unit tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1695

dnf5: distro-sync: Argument "--from-repo"

---

dnf5-plugins/repoclosure_plugin/repoclosure.cpp

Similar to autodetect_unsatisfied_installed_weak_dependencies (in fact I stole the code from there). repoclosure can give bogus failures for dependencies like (foo if bar). If nothing provides foo in the repo(s) under test, but also bar is not present, that should not be considered a repoclosure failure, but repoclosure reports it as an "unresolved dep". See:
https://github.com/rpm-software-management/dnf-plugins-core/issues/549
Ideally we should handle rich dependencies correctly, but I cannot see how to do that, so I'm sending this as an alternative that's at least less-bad than the current state.

repoclosure: skip rich dependencies

---

libdnf5/repo/repo_sack.cpp

For: https://github.com/rpm-software-management/dnf5/issues/2323
Unfortunaly the errors from librepo parallel downloading API are reported only as strings (to improve that we would have to break librepo ABI).
https://github.com/rpm-software-management/librepo/blob/master/librepo/metadata_downloader.h#L61-L62
This approach also works with the nested exceptions (still used by local repo loading) because we check the suffix (the inner most exception).
Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1692

Adapt missing gpg key check for parallel downloading

---

bindings/libdnf5/rpm.i
test/libdnf5/rpm/test_nevra.cpp
test/python3/libdnf5/rpm/test_nevra.py

Resolves: https://github.com/rpm-software-management/dnf5/issues/1644

swig: Add bindings for templated functions that convert nevra to string

---

test/data/build-rpms-and-repos.sh

With /bin/sh that is not bash:
test/data/build-rpms-and-repos.sh: 4: Syntax error: "(" unexpected

tests: fix compat with dash and other shellcheck warnings

---

test/python3/libdnf5/rpm/test_nevra.py

Unfortunately without any change it is currently failing on all PRs.
The code can be formatted in multiple shapes (that autopep8 accepts). This versions seems the most acceptable to me.
This is a follow up to https://github.com/rpm-software-management/dnf5/pull/2347.

test_nevra.py: change formatting to satisfy autopep8

---

dnf5/commands/do/do.cpp
dnf5/commands/do/do.hpp

CI tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1708

dnf5: Support `--installed-from-repo=` for command `do`

---

.github/workflows/weblate-sync-pot.yml

This will reduce the number of secrets we have to manage. We already use the `RSM_CI_APP_ID` and `RSM_CI_APP_PRIVATE_KEY` in `do-release.yaml`.

actions: Replace `L10N_SSH_KEY` secret with RSM CI GitHub token

---

libdnf5/repo/temp_files_memory.cpp
test/libdnf5/repo/test_temp_files_memory.cpp
test/libdnf5/repo/test_temp_files_memory.hpp

Use toml::find_or to safely read file paths from temp files toml,
returning an empty vector if the "files" key is missing.
Resolves: https://github.com/rpm-software-management/dnf5/issues/1001
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2330306

repo: Do not fail on empty temporary files toml

---

dnf5daemon-server/callbacks.cpp

While the DownloadCB::create_signal_download() may not always have set the `user_data`, the D-Bus signal signature is not that flexible and requires to be always the same, with all the declared arguments, thus pass an empty string as the `download_id` when it's not available.
Fixes https://github.com/rpm-software-management/dnf5/issues/2338

dnfdaemon: Obey downloader D-Bus signal signature

---

doc/commands/group.8.rst
doc/commands/install.8.rst
doc/dnf5.8.rst
doc/dnf5_plugins/automatic.8.rst
doc/dnf5_plugins/config-manager.8.rst
doc/misc/system-state.7.rst

Some doc pages were referring to dnf5-conf(5), which doesn't exist. Fix those references to point to dnf5.conf(5) instead.

doc: fix references to dnf5.conf(5)

---

dnf5daemon-server/services/repo/repo.cpp

There had been missing the "options" argument declaration in the branch for the sdbus-cpp 2.
Incomplete in the https://github.com/rpm-software-management/dnf5/pull/2333

dnf5daemon-server: Correct repo::confirm_key_with_options D-Bus signature

---

doc/index.rst
doc/migrating_to_dnf5.7.rst

Try to retell the story of moving Fedora to dnf5 by default and what the migration process was like.  Note this is different from the chapter explaining the differences between dnf4 and dnf5.
Resolves: #1739
Resolves: SWM-4363

doc: Add a chapter about migrating to dnf5

---

libdnf5/base/transaction.cpp

If a package requires a dependency which cannot be satisfied, a transaction error is formatted and printed to an error output and a log file.
If the error message contained curly brackets, e.g. the dependency was "a{}", "argument not found" was printed instead of the transaction error:
Updating and loading repositories:
Repositories loaded.
argument not found
Expected output:
Updating and loading repositories:
Repositories loaded.
Failed to resolve the transaction:
Problem: conflicting requests
- nothing provides a{} needed by test2-0-0.fc44.noarch from @commandline You can try to add to command line: --skip-broken to skip uninstallable packages
The cause was formatting the transaction error twice: An already formatted output from LogEvent.to_string() was passed again to logger.log() …

libdnf5: Don't double format a transaction error

---

libdnf5/repo/repo.cpp

This is important in case `metadata_expire = 0`.
It means that repo is always expired not that it is expired after 1 sec.

repo: When repo age matches `metadata_expire` exactly expire it

---

include/libdnf5/conf/config_main.hpp
libdnf5/conf/config_main.cpp
test/libdnf5/conf/test_conf.cpp
test/libdnf5/conf/test_conf.hpp

Supersedes https://github.com/rpm-software-management/dnf5/pull/2389.
Adds a new method, `ConfigMain::load_from_config` which enables copying config values from one `ConfigMain` to another.
```
/// For each option, set the option value to the value from `other`. An option
/// will only be set if its priority in `other` is greater or equal to the
/// current priority and the option in `other` is not empty.
void load_from_config(const libdnf5::ConfigMain & other);
```
An outstanding question: should we also load the `locked` status of each config option from the source config?

Add `ConfigMain::load_from_config`

---

dnf5/main.cpp
dnf5daemon-client/context.cpp
dnf5daemon-client/context.hpp
dnf5daemon-client/main.cpp
dnf5daemon-server/session.cpp
doc/dnf5.8.rst
doc/dnf5_plugins/config-manager.8.rst
include/libdnf5/conf/vars.hpp
libdnf5/conf/vars.cpp
test/libdnf5/conf/test_vars.cpp

Resolves https://github.com/rpm-software-management/dnf5/issues/2400.
DNF5 counterpart to https://github.com/rpm-software-management/dnf/pull/2198. See that PR for more background information.
@m-blaha are the dnf5daemon changes I made here correct? It's not clear to me how `cfg["releasever_major"]` and `cfg["releasever_minor"]` will be eventually used.

Override releasever_{major,minor} with system-release provides

---

doc/dnf5.conf.5.rst
include/libdnf5/conf/config_main.hpp
include/libdnf5/repo/config_repo.hpp
libdnf5-cli/output/repo_info.cpp
libdnf5/conf/config_main.cpp
libdnf5/repo/config_repo.cpp
libdnf5/repo/repo_downloader.cpp

This is a forward port of the implementation in libdnf4 (libdnf4 commit [67440807f4cb7eb0887f3e08de6ea589a2e2c823](https://github.com/rpm-software-management/libdnf/commit/67440807f4cb7eb0887f3e08de6ea589a2e2c823), pull request https://github.com/rpm-software-management/libdnf/pull/1532).
In many cases the librepo default of 3 concurrent downloads per mirror is sufficient, as there are multiple mirrors, and the max of 3 per mirror is cumulative up until max_parallel_downloads. However, in some situations you don't necessarily want to have other mirrors, and want to have more than 3 parallel downloads.
Such a situation could be where not all mirrors have equal cost, and can handle more simultaneous downloads to saturate the available network bandwidth - so it's beneficial to only list the …

Expose librepo max_downloads_per_mirror configuration (forward port to dnf5)
